### ISSUE TITLE
Simdna install failing?

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1029]
I'm seeing some tests failing with the following:

```
find ./deepchem | grep .py$ |xargs python -m doctest -v
Traceback (most recent call last):
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/doctest.py", line 2817, in <module>
    sys.exit(_test())
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/doctest.py", line 2806, in _test
    m = __import__(filename[:-3])
  File "./deepchem/molnet/dnasim.py", line 4, in <module>
    import simdna
ImportError: No module named simdna
```

I think the conda-forge install might be failing.

CC @lilleswing

**Comment by lilleswing** [comment]
is this local?  Did you install simdna manually or recreate your environment?

```python
conda install -c conda-forge simdna=0.4.2
```

**Comment by rbharath** [comment]
This was on a Travis build.

**Comment by lilleswing** [comment]
Can I get a link?

**Comment by rbharath** [comment]
https://travis-ci.org/deepchem/deepchem/builds/330622313

Should have included in original posting. My bad :)

**Comment by lilleswing** [comment]
You need to merge master into your feature branch.  You are in an inconsistent state where you have some code from master but not others.

https://github.com/rbharath/deepchem/blob/deprem/scripts/install_deepchem_conda.sh

**Comment by rbharath** [comment]
Ack! This one is on me for trying to resuscitate an old PR in a spare half hour. Will clean up and get up to master properly. Thanks for pointers!
