### ISSUE TITLE
Validation loss

### ISSUE THREAD

**Issue by fuzunyun** [deepchem/deepchem#1040]
I have a question, I use the TensorflowMultiTaskClassifier model,and I want to output the loss of validation set and test set, but I do not how to do this
Thanks

**Comment by lilleswing** [comment]
You are right it is hard right now!  Thanks for bringing it up.  I generally use model performance on the validation set for monitoring the overfitting vs the loss function so the dev team hasn't noticed.

The easiest way right now is to run a fit on the valid_dataset and then restore the checkpoint from the fitting process.

```python
"""
Script that trains multitask models on Tox21 dataset.
"""
# Load Tox21 dataset
n_features = 1024
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()
train_dataset, valid_dataset, test_dataset = tox21_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

model = dc.models.MultiTaskClassifier(
    len(tox21_tasks),
    n_features,
    layer_sizes=[1000],
    dropouts=[.25],
    learning_rate=0.001,
    batch_size=50,
    use_queue=False)

# Fit trained model
model.fit(train_dataset, nb_epoch=1)

# checkpoint_interval causes the model not to save a checkpoint.
valid_loss = model.fit(valid_dataset, checkpoint_interval=0)
print(valid_loss)
# This will restore the model to the fit from the train dataset
model.restore()
```

This is not idea.  The API we want to have is 
``` python
model.fit(train_dataset, nb_epoch=1)
valid_loss = model.predict(valid_dataset, outputs=model.loss)
print(np.mean(valid_loss))
```
However there are currently some assumptions on labels not existing for predict.  I can fix that in a PR.  The first code snippet should work for you right now.

**Comment by fuzunyun** [comment]
Copy that! Many thanks to you for your helpful solution. I will try it and any further questions I will let you know. Thank you again for your help.

**Comment by unsterbliche** [comment]
I have tried 
 `model.fit(train_dataset, nb_epoch=1)
valid_loss = model.predict(valid_dataset, outputs=model.loss)`
in my dc.models.MultiTaskClassifier model. 
There are 1227 tasks in the model, and this function got some errors said logits and labels must be same size. How do I print out the validation loss in MultiTaskClassifier model? Thanks.
Here is the traceback message.
`Traceback (most recent call last):

  File "<ipython-input-123-e141dc94a8ac>", line 1, in <module>
    test_loss = model.predict(test_dataset, outputs=model.loss)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorflow_models/fcnet.py", line 180, in predict
    outputs)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 423, in predict
    return self.predict_on_generator(generator, transformers, outputs)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 340, in predict_on_generator
    feed_results = self.session.run(outputs, feed_dict=feed_dict)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)

  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)

InvalidArgumentError: logits and labels must be same size: logits_size=[122700,2] labels_size=[0,2]
	 [[Node: SoftMaxCrossEntropy_7/SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](SoftMaxCrossEntropy_7/Reshape_2, SoftMaxCrossEntropy_7/Reshape_3)]]

Caused by op 'SoftMaxCrossEntropy_7/SoftmaxCrossEntropyWithLogits', defined at:
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/spyder/utils/ipython/start_kernel.py", line 268, in <module>
    main()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/spyder/utils/ipython/start_kernel.py", line 264, in main
    kernel.start()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 478, in start
    self.io_loop.start()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 281, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 232, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 397, in execute_request
    user_expressions, allow_stdin)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2856, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-120-515036de9e36>", line 1, in <module>
    model.fit(test_dataset,epoch=1)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 147, in fit
    max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 179, in fit_generator
    self.build()
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 474, in build
    layer.create_tensor(training=self._training_placeholder)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/layers.py", line 1436, in create_tensor
    logits=logits, labels=labels)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1783, in softmax_cross_entropy_with_logits
    precise_logits, labels, name=name)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 4364, in _softmax_cross_entropy_with_logits
    name=name)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/deepchem/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): logits and labels must be same size: logits_size=[122700,2] labels_size=[0,2]
	 [[Node: SoftMaxCrossEntropy_7/SoftmaxCrossEntropyWithLogits = SoftmaxCrossEntropyWithLogits[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](SoftMaxCrossEntropy_7/Reshape_2, SoftMaxCrossEntropy_7/Reshape_3)]]
`

**Comment by fuzunyun** [comment]
I've tried the code you provided but failed. Attached please find the error information. Could please help me find the problem and give some guidance?
Will appreciate it a lot.
Best Regards,
![default](https://user-images.githubusercontent.com/32700274/35385241-a0a0ce52-0202-11e8-8560-dae7de04d7eb.png)
![default](https://user-images.githubusercontent.com/32700274/35385260-b410c5c8-0202-11e8-8d15-1b6d71993aff.png)

**Comment by lilleswing** [comment]
This is most surprising.  Are you on DC 1.3.1?  
Can I get the full script that you are running?  We no longer close the tf.Session after fit calls, and when we did we reopened and restored it before each new fit call.

I'm sorry again for your troubles.

**Comment by fuzunyun** [comment]
Well, not your fault, you already have been quite helpful.  I do write the script on DC 1.3.1 and attached is my full script. 
Thanks again for your help.
Regards,
np.random.seed(123)

# Load datasets

predict_task, Pro_datasets, transformers = load_hERG(split='random')
(train_dataset, test_dataset) = Pro_datasets
print("Number of compounds in train_dataset")
print(len(train_dataset))
print("Number of compounds in test_dataset")
print(len(test_dataset))
#evaluate metric
metric = [dc.metrics.Metric(dc.metrics.roc_auc_score),
          dc.metrics.Metric(dc.metrics.prc_auc_score),
          dc.metrics.Metric(dc.metrics.balanced_accuracy_score)]   
n_features = train_dataset.get_data_shape()[0]
# Fit models
model = dc.models.TensorflowMultiTaskClassifier(1,n_features, learning_rate=0.0001,
	layer_sizes=[1000,500],
	weight_init_stddevs=[0.02,0.02],
	bias_init_consts=[1.0,1.0],
	dropouts=[0.5,0.5], batch_size=32, penalty_type="l2", optimizer="adam")

print("About to fit model")
model.fit(train_dataset, nb_epoch=70)
test_loss = model.fit(test_dataset, checkpoint_interval=0)
print(test_loss)
model.restore()
# print score
dnn_training_csv_out = "dnn_training_classifier.csv"
dnn_train_evaluator = Evaluator(model, train_dataset, transformers)
dnn_train_score = dnn_train_evaluator.compute_model_performance(metric,dnn_training_csv_out)
print("DNN Train set AUC %f" % (dnn_train_score["roc_auc_score"]))
print("DNN Train set PRC %f" % (dnn_train_score["prc_auc_score"]))
print("DNN Train set BUC %f" % (dnn_train_score["balanced_accuracy_score"]))
dnn_test_csv_out = "dnn_test_classifier.csv"
dnn_test_evaluator = Evaluator(model, test_dataset, transformers)
dnn_test_score = dnn_test_evaluator.compute_model_performance(
    metric, dnn_test_csv_out)
print("DNN Test set AUC %f" % (dnn_test_score["roc_auc_score"]))
print("DNN Test set PRC %f" % (dnn_test_score["prc_auc_score"]))
print("DNN Test set BUC %f" % (dnn_test_score["balanced_accuracy_score"]))

**Comment by fuzunyun** [comment]
Well, not your fault, you already have been quite helpful.  I do write the script on DC 1.3.1 and attached is my full script. 
Thanks again for your help.
Regards,
[1.pdf](https://github.com/deepchem/deepchem/files/1666307/1.pdf)

**Comment by fuzunyun** [comment]
Well, not your fault, you already have been quite helpful.  I do write the script on DC 1.3.1, but I noticed that your model is MultiTaskClassifier while I use the TensorflowMultiTaskClassifier. Could this be where the problem lies in?
Attached is my full script. 
Thanks again for your help.
Regards,
[1.pdf](https://github.com/deepchem/deepchem/files/1666344/1.pdf)

**Comment by rbharath** [comment]
I'm going to close this old issue. @fuzunyun Let me know if you're still struggling with these issues and we can re-open.
