### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by selcukorkmaz** [deepchem/deepchem#1065]
I could not import rdkit package.

I followed the instruction from [http://www.rdkit.org/docs/Install.html](url)
```
$ conda create -c rdkit -n my-rdkit-env rdkit
$ source activate my-rdkit-env 
```
I also tried to install it through `brew`, using the instructions from [https://github.com/rdkit/homebrew-rdkit](url).

`brew install rdkit`

This actually installed the rdkit. However, I keep getting the following error in python 3.6

`>>> from deepchem.molnet import load_pcba`

`Traceback (most recent call last):`
 ` File "<stdin>", line 1, in <module>`
`  File "/Users/selcukkorkmaz/miniconda3/lib/python3.6/site-packages/deepchem/__init__.py", line 10, in <module>`
`    import deepchem.data`
`  File "/Users/selcukkorkmaz/miniconda3/lib/python3.6/site-packages/deepchem/data/__init__.py", line 9, in <module>`
`    from deepchem.data.datasets import pad_features`
  `File "/Users/selcukkorkmaz/miniconda3/lib/python3.6/site-packages/deepchem/data/datasets.py", line 13, in <module>`
   ` from deepchem.utils.save import save_to_disk, save_metadata`
  `File "/Users/selcukkorkmaz/miniconda3/lib/python3.6/site-packages/deepchem/utils/__init__.py", line 17, in <module>`
   ` from rdkit import Chem`
`ModuleNotFoundError: No module named 'rdkit'`

Any help would be appreciated.

**Comment by lilleswing** [comment]
@selcukorkmaz your first statement 
```bash
conda create -c rdkit -n my-rdkit-env rdkit
source activate my-rdkit-env 
```
This installs rdkit in an environment called "my-rdkit-env".  Your code example is using no the default conda environment, not any environment that you have installed packages into.

This will create a new conda environment "deepchem" and install deepchem with rdkit in it.

``` bash
git clone https://github.com/deepchem/deepchem.git      # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
yes | pip install tensorflow-gpu==1.5.0      # If you want GPU support
python setup.py install                                # Manual install
```

**Comment by srinu844** [comment]
Hello 

I installed deepchem using the below mentioned procedure. 

git clone https://github.com/deepchem/deepchem.git      # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
yes | pip install tensorflow-gpu==1.6.0      # If you want GPU support
python setup.py install                                # Manual install
nosetests -a '!slow' -v deepchem --nologcapture        # Run tests

This installed the packages required but not rdkit. so I installed rdkit using conda-forge. The following version was installed. 

rdkit                     2020.03.1        py36h8e01224_1    conda-forge

I also installed all the dependencies mentioned in requirements page. 

After installing all the dependencies, I tried the example tox21 dataset. I activated the deepchem environment using conda activate deepchem.  When I ran benchmark.py using the python 3.6, I am getting the following error:

(deepchem) DRSetty@SETE-CHEM-4 examples % python3 benchmark.py
Traceback (most recent call last):
  File "benchmark.py", line 39, in <module>
    import deepchem as dc
  File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/__init__.py", line 6, in <module>
    import deepchem.data
  File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/data/__init__.py", line 14, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 17, in <module>
    from deepchem.feat import UserDefinedFeaturizer
  File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/feat/__init__.py", line 11, in <module>
    from deepchem.feat.graph_features import ConvMolFeaturizer
  File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/feat/graph_features.py", line 2, in <module>
    from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'


Can I get any help on this error.

**Comment by rbharath** [comment]
@srinu844 It looks like you're installing from source which is always a little trickier. I'd recommend installing from the last stable release. You can do this with:

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.3.0
```

For your current installation, my guess is that rdkit installed for a different python. Try running 
```
>>> import rdkit
```
in python and seeing what happens. My guess is that rdkit isn't installed in the same python environment as deepchem. If you're still having trouble, my recommendation would be to use Google colab for your experiments. The deepchem tutorials show how to get deepchem installed on colab and you don't need to worry about managing a local environment

**Comment by srinu844** [comment]
Thank you for the response. The following installed worked in local environment.  I will explore google colab as well.
