### ISSUE TITLE
cannot joblib.load 'shard-0-w.joblib'

### ISSUE THREAD

**Issue by xiaohongniua** [deepchem/deepchem#1222]
I write out  train dataset to disk and get 4 files 'shard-0-w.joblib' 'shard-0-y.joblib' 'shard-0-ids.joblib' 'shard-0-X.joblib'
I can joblib.load 'shard-0-ids.joblib' file , however, the other 3 files got an KeyError, what is wrong?

 >>> a=joblib.load('shard-0-ids.joblib')
>>> a
array(['1_1_13', '1_1_24', '1_1_39', ..., '10_63_70', '10_63_84',
       '10_63_90'], dtype=object)
>>> type(a)
<class 'numpy.ndarray'>
>>> a=joblib.load('shard-0-y.joblib')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn\externals\joblib\numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "C:\ProgramData\Anaconda3\lib\pickle.py", line 1050, in load
    dispatch[key[0]](self)
KeyError: 0

**Comment by rbharath** [comment]
Could you provide us a minimal failing code sample for us to look at?

**Comment by rbharath** [comment]
Closing due to inactivity. Feel free to reopen if still an issue
