### ISSUE TITLE
Error in saving a ProgressiveMultitaskClassifier model

### ISSUE THREAD

**Issue by zhengmin317** [deepchem/deepchem#1262]
when deepchem/examples/tox21/tox21_tf_progressive.py is added with model.save(), it throws the following error:

> Traceback (most recent call last):
  File "tox21_tf_progressive.py", line 39, in <module>
    model.save()
  File "/anaconda3/envs/py3.5/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 904, in save
    raise e
  File "/anaconda3/envs/py3.5/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 901, in save
    pickle.dump(self, fout)
_pickle.PicklingError: Can't pickle <class 'module'>: attribute lookup module on builtins failed

**Comment by rbharath** [comment]
CC @miaecle, @lilleswing

I believe this is due to the use of submodel. Is there a good way we could add save features for submodel?

**Comment by peastman** [comment]
This should be pretty easy to fix.  We just need to clear fields in the Submodel object before saving.
