### ISSUE TITLE
AttributeError: 'numpy.ndarray' object has no attribute 'get_num_atoms'

### ISSUE THREAD

**Issue by ha01994** [deepchem/deepchem#1277]
Hello,
I have Deepchem 2.0.0 and Numpy 1.13.3 and Tensorflow-gpu 1.5.0.
I am trying to run graph convolution model with my own dataset, and I keep coming across this error:

Traceback (most recent call last):
  File "run_benchmark_edit.py", line 305, in <module>
    benchmark_model("graphconv", all_dataset, transformers, metric='roc_auc_score', test=False)
  File "run_benchmark_edit.py", line 291, in benchmark_model
    model.fit(train_dataset)
  File "/home/ha01994/miniconda2/envs/project/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 150, in fit
    max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
  File "/home/ha01994/miniconda2/envs/project/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 207, in fit_generator
    for feed_dict in self._create_feed_dicts(feed_dict_generator, True):
  File "/home/ha01994/miniconda2/envs/project/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 840, in _create_feed_dicts
    for d in generator:
  File "/home/ha01994/miniconda2/envs/project/lib/python2.7/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 786, in default_generator
    multiConvMol = ConvMol.agglomerate_mols(X_b)
  File "/home/ha01994/miniconda2/envs/project/lib/python2.7/site-packages/deepchem/feat/mol_graphs.py", line 267, in agglomerate_mols
    atoms_per_mol = [mol.get_num_atoms() for mol in mols]
AttributeError: 'numpy.ndarray' object has no attribute 'get_num_atoms'

If my code is needed I will attach it here. Also I am using a custom csv file with smiles and IC50 data.
Any help would be very much appreciated. Thank you!

**Comment by rbharath** [comment]
@ha01994 Could you attach a minimal failing code sample? If you could simplify it so we can run it locally without any additional information needed that would be very useful.
