### ISSUE TITLE
How could I fully turn the tox21 GraphConvModel example into a single-task model?

### ISSUE THREAD

**Issue by herbert0525** [deepchem/deepchem#1284]
** I have modified the load_tox21 function, deleted redundant labels in order to use a single-labeled dataset. It went well when I just proceeded with the default GraphConvModel. However, when I tried the instruction of building TensorGraph in the tutorial with the data, there was an error at the stage of evaluating the model. Traceback is given below. So how could I deal with that? Thanks.**

- DeepChem Version:2.0.0
- Platform: Ubuntu 16.04 LTS Server

```
Starting epoch 0
Evaluating model
Traceback (most recent call last):
  File "alejandro.py", line 168, in <module>
    train_scores = metric.compute_metric(train_dataset.y, train_predictions, train_dataset.w)
  File "/home/lab/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/metrics/__init__.py", line 232, in compute_metric
    metric_value = self.compute_singletask_metric(y_task, y_pred_task, w_task)
  File "/home/lab/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/metrics/__init__.py", line 268, in compute_singletask_metric
    y_pred = np.array(np.squeeze(y_pred[w != 0]))
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 4204

```

**Comment by rbharath** [comment]
Could you provide us a minimal failing code sample? It's not clear what's happening here.

**Comment by herbert0525** [comment]
@rbharath I guess this is what you would like to see. The data I tried came from a single column of the tox21 dataset, i.e. the 'SR-ARE' column, with mol_id and smiles attatched.

![image](https://user-images.githubusercontent.com/31651783/40894586-53b63fc8-67dd-11e8-8991-63918d11bd1b.png)
