### ISSUE TITLE
WeaveTensorGraph Cannot create a model

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1285]
I tried using WeaveTensorGraph to create models and train them, but I got the wrong information in the source code.
This is my code:

```
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21(featurizer='Weave', reload=False)
train_dataset, valid_dataset, test_dataset = tox21_datasets
model_dir = "/home/zh/0601"
model = WeaveTensorGraph(n_tasks=len(tox21_tasks), mode="classfication", learning_rate=0.01, model_dir=model_dir)
model.fit(train_dataset)
model.save()
```

But this code can run:

```
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21(featurizer='Weave', reload=False)
train_dataset, valid_dataset, test_dataset = tox21_datasets
model_dir = "/home/zh/0601"
# model = WeaveTensorGraph(n_tasks=len(tox21_tasks),model_dir=model_dir)
model.fit(train_dataset)
model.save()
```

This is a mistake:

```
Traceback (most recent call last):
File "/home/zh/桌面/project/deepchem框架/生物标靶毒性测量/WeaveModel/WeaveModel.py", line 30, in <module>
weave_train()
File "/home/zh/桌面/project/deepchem框架/生物标靶毒性测量/WeaveModel/WeaveModel.py", line 16, in weave_train
model=WeaveTensorGraph(n_tasks=len(Tasks),mode="classfication",learning_rate=0.01,model_dir=model_dir)
 File "/home/zh/anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 56, in __init__
self.build_graph()
File "/home/zh/anaconda3/envs/deep2.0.0/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 123, in build_graph
loss = WeightedError(in_layers=[all_cost, self.weights])
UnboundLocalError: local variable 'all_cost' referenced before assignment

Process finished with exit code 1
```

This is the error in the source code, it shouldn't be.I'm using the formal version of deepchem2.0.0, python3.6

**Comment by rbharath** [comment]
Interesting. This line seems to have been replaced in HEAD:

https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/models/graph_models.py#L140

You could try upgrading to HEAD perhaps. I'd recommend doing this in a new conda environment, since some folks are having segfault issues with HEAD due to conda/rdkit.

**Comment by zhouhao-learning** [comment]
@rbharath 
According to what you said, I recreated a new environment and installed it through source code. Then my training was still wrong.

This is my code:

```
from __future__ import division
from __future__ import unicode_literals
from deepchem.feat.mol_graphs import ConvMol
from deepchem.metrics import to_one_hot
from deepchem.models.tensorgraph.models.graph_models import WeaveTensorGraph, WeaveModel
import logging as logs
import deepchem
import numpy as np


logger = logs.getLogger(__name__)


def load_datasets(data_file,split, K=None):
	tasks = ['NR-AR', 'NR-AR-LBD']
	featurizer = deepchem.feat.WeaveFeaturizer()
	loader = deepchem.data.CSVLoader(tasks=tasks, smiles_field="smiles", featurizer=featurizer)
	dataset = loader.featurize(data_file, shard_size=8192)
	# transformers = [deepchem.trans.BalancingTransformer(transform_w=True, dataset=dataset)]
	
	logger.info("About to transform data")
	# for transformer in transformers:
	#     dataset = transformer.transform(dataset)
	
	if split == None:
		return tasks, (dataset, None, None)
	
	splitters = {'index': deepchem.splits.IndexSplitter(),
				'random': deepchem.splits.RandomSplitter(),
				'scaffold': deepchem.splits.ScaffoldSplitter(),
				'butina': deepchem.splits.ButinaSplitter(),
				'task': deepchem.splits.TaskSplitter()}
	
	splitter = splitters[split]
	if split == 'task':
		fold_datasets = splitter.k_fold_split(dataset, K)
		all_dataset = fold_datasets
	else:
		train, valid, test = splitter.train_valid_test_split(dataset)
		all_dataset = (train, valid, test)
	return tasks, all_dataset

def train_generator(dataset,n_tasks,n_classes, mode="classification",epochs=5,batch_size=100,
					predict=False, labels=None,task_weights=None,atom_features=None,pair_features=None,
					n_pair_feat=None):
	for epoch in range(epochs):
		if not predict:
			print('Starting epoch %i' % epoch)
		for (X_b, y_b, w_b, ids_b) in dataset.iterbatches(
				batch_size=batch_size,
				deterministic=True,
				pad_batches=False):

			feed_dict = dict()
			if y_b is not None:
				if mode == 'classification':
					feed_dict[labels[0]] = to_one_hot(y_b.flatten(),n_classes).reshape(
						-1, n_tasks,
						n_classes)
				else:
					feed_dict[labels[0]] = y_b
			if w_b is not None:
				feed_dict[task_weights[0]] = w_b

			atom_feat = []
			pair_feat = []
			atom_split = []
			atom_to_pair = []
			pair_split = []
			start = 0
			for im, mol in enumerate(X_b):
				n_atoms = mol.get_num_atoms()
				# number of atoms in each molecule
				atom_split.extend([im] * n_atoms)
				# index of pair features
				C0, C1 = np.meshgrid(np.arange(n_atoms), np.arange(n_atoms))
				atom_to_pair.append(
					np.transpose(
						np.array([C1.flatten() + start, C0.flatten() + start])))
				# number of pairs for each atom
				pair_split.extend(C1.flatten() + start)
				start = start + n_atoms

				# atom features
				atom_feat.append(mol.get_atom_features())
				# pair features
				pair_feat.append(
					np.reshape(mol.get_pair_features(), (n_atoms * n_atoms, n_pair_feat)))
			feed_dict[atom_features] = np.concatenate(atom_feat, axis=0)
			feed_dict[pair_features] = np.concatenate(pair_feat, axis=0)
			feed_dict[pair_split] = np.array(pair_split)
			feed_dict[atom_split] = np.array(atom_split)
			feed_dict[atom_to_pair] = np.concatenate(atom_to_pair, axis=0)
			yield feed_dict

Tasks, data = load_datasets(data_file="/home/zh/桌面/project/deepchem框架/生物标靶毒性测量/tox21.csv",split="index")
	model = WeaveModel(n_tasks=len(Tasks),mode="classification",learning_rate=0.01,model_dir=model_dir)
	train_gene = train_generator(dataset=data[0], n_tasks=len(Tasks),n_classes=model.n_classes,epochs=2,
								batch_size=model.batch_size,labels=model.labels,
								atom_features=model.atom_features,
                                                                task_weights=model.task_weights,
								pair_features=model.pair_features, n_pair_feat=model.n_pair_feat)

	model.fit_generator(train_gene)
	print("end")
	model.save()

```
But I got the following error. Isn't this generator in your source code? I just extracted it individually and got the result wrong:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/zh/anaconda3/envs/deepchem2.0.0/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/zh/anaconda3/envs/deepchem2.0.0/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/home/zh/anaconda3/envs/deepchem2.0.0/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1291, in _enqueue_batch
    for feed_dict in generator:
  File "/project/deepchem框架/生物标靶毒性测量/WeaveModel/tox21_generator.py", line 114, in train_generator
    feed_dict[pair_split] = np.array(pair_split)
TypeError: unhashable type: 'list'


```

**Comment by rbharath** [comment]
Sorry for the lack of response here. Lost track of this old issue in my inbox. I'm going to go ahead and close, but please re-open if this is still an issue
