### ISSUE TITLE
Cannot modify parameter values of the WeaveTensorGraph model

### ISSUE THREAD

**Issue by Running-z** [deepchem/deepchem#1345]
When I modified the n_atom_feat parameter of the WeaveTensorGraph model, I got the following error：
```
Traceback (most recent call last):
  File "/atlas/home/hzhou/project/SG_PB/WeaveModel/weave_train.py", line 41, in <module>
    train_model()
  File "/atlas/home/hzhou/project/SG_PB/WeaveModel/weave_train.py", line 29, in train_model
    model.fit_generator(train_gene)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 224, in fit_generator
    fetched_values = self.session.run(fetches, feed_dict=feed_dict)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1113, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (3003, 75) for Tensor 'Feature_9/Placeholder:0', which has shape '(?, 80)'

```
this is my code:

```
# -*- coding: utf-8 -*-
from __future__ import absolute_import
from __future__ import print_function
from deepchem.models.tensorgraph.models.graph_models import WeaveTensorGraph
from data_out import load_datasets
import numpy as np
import deepchem as dc


model = WeaveTensorGraph(n_tasks=len(n_tasks),
					     n_atom_feat=80,
					     n_pair_feat=14,
					     n_hidden=50,
					    n_graph_feat=128,
					    dropout=0.2,
					    batch_size=50,
					    learning_rate=0.001,
					   mode="regression",
					   model_dir=model_dir,
					  tensorboard=True, use_queue=False)
```
Why is this? How can I modify this parameter?

**Comment by rbharath** [comment]
This parameter corresponds to the output of the weave featurizer. Since this featurizer outputs 75 atom features, a model with `n_atom_feat=80` won't work with the featurizer. You'd need to make your own custom featurizer with 80 atom features if you wanted to set `n_atom_feat=80`

**Comment by Running-z** [comment]
@rbharath 
What you mean is that unless I rewrite a feature extractor myself, the Weavemodel feature extractor in deepchem must have n_atom_feat=75?

**Comment by rbharath** [comment]
Yes, that's correct.

**Comment by rbharath** [comment]
Going to close since question answered. Feel free to re-open if you have further questions.
