### ISSUE TITLE
Cannot create classification model for 'test_graph_conv_atom_features' in deepchem/models/tensorgraph/models/test_graph_models.py

### ISSUE THREAD

**Issue by h-midlothian** [deepchem/deepchem#1375]
I applied the example of 'test_graph_conv_atom_features' to add atom properties for ```ConvMolFeaturizer```  and managed to add atom(or molecule) properties through my data. But if I change the mode of GraphConvModel from 'regression' to 'classification', there would be an Index Error, reading 'index XX is out of bounds for axis 1 with size 2', where XX is a random integer between 10 and 50. I also have tried a customized GraphConv classification model, and resulted in the same error. And code is presented below. @lilleswing 

- Git hash: commit 1b171da623799b47871b95349b96ff2b139e3f41
- DeepChem Version: 2.0.0 GPU
- Platform: Ubuntu 16.04 lts server

```
    def add_graph_conv_atom_properties(self):
        tasks, dataset, transformers, metric = self.get_dataset(
            'classification', 'Raw', num_tasks=1)
        with open('celltox.csv') as csvDataFile:
            data = list(csv.reader(csvDataFile))
            f = []
            for i in range(1,5759):
                phe = float(data[i][7])
                f.append(phe)
        atom_property_name = 'tpsa'
        y = []
        for j in range(0,10):
            mol = dataset.X[j]
            atom_props = []
            for atom in mol.GetAtoms():
                val = f[j]
                mol.SetProp("atom %08d %s" % (atom.GetIdx(), atom_property_name), str(val))
                atom_props.append(float(val))
            y.append([np.sum(atom_props)])
```
And the fit process
```
model = GraphConvModel(
            len(tasks),
            number_atom_features=featurizer.feature_length(),
            batch_size=batch_size,
            mode='classification')

        model.fit(dataset, nb_epoch=1)
        y_pred1 = model.predict(dataset)
        model.save()
```
The error:
```
Traceback (most recent call last):
  File "addfeat.py", line 232, in <module>
    b = a.add_graph_conv_atom_properties()
  File "addfeat.py", line 138, in add_graph_conv_atom_properties
    model.fit(dataset, nb_epoch=1)
  File "/home/cuda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 153, in fit
    max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
  File "/home/cuda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 231, in fit_generator
    for feed_dict in self._create_feed_dicts(feed_dict_generator, True):
  File "/home/cuda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1093, in _create_feed_dicts
    for d in generator:
  File "/home/cuda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 704, in default_generator
    d[self.labels[0]] = to_one_hot(y_b.flatten(), self.n_classes).reshape(
  File "/home/cuda/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/metrics/__init__.py", line 29, in to_one_hot
    y_hot[np.arange(n_samples), y.astype(np.int64)] = 1
IndexError: index 31 is out of bounds for axis 1 with size 2

```

**Comment by rbharath** [comment]
Sorry for the very slow response. We've refactored the graph conv models quite a bit. I think this failure should no longer happen so I'm going to close this issue. Please feel free to re-open if you're still seeing problems.
