### ISSUE TITLE
Deepchemm Using Estimator

### ISSUE THREAD

**Issue by saurabhclusterone** [deepchem/deepchem#1379]
Hey Everyone,

We are trying to run Deepchem membrane_permeability example in distributed training mode using TensorFlow Estimator. I followed the example as given on the Deepchem repo (https://deepchem.io/docs/notebooks/Estimators.html) . The example is outdated because the dc.models.MultiTaskClassifier is outdated as of now since the MultiTaskClassifier is deprecated.

Now the error I am getting while running is in the make_estimator function. The problem is that DAGModel I derived from Tensor_Graph and within Tensor_Grpah the input feature length and the feature length as formed in the model are compared.

I am running this example on local conda environment with Deepchem= 2.1.0. 

I don't know how to control the creation of feature set of the model as DAGModel is in my control but not the TensorGraph . I checked the feature getting created from the dataset are of length 5 although in those features I find two features having value None. The internal model seems to always expect 6 features. So, the core issue is the model expects 6 features always and I don't know how is that. Any help would be great!

Could you please tell me how to get around this error? Following is the run logs:

1
TIMING: dataset construction took 1.524 s
Loading dataset from disk.
TIMING: dataset construction took 24.357 s
Loading dataset from disk.
TIMING: dataset construction took 0.202 s
Loading dataset from disk.
TIMING: dataset construction took 3.444 s
Loading dataset from disk.
Traceback (most recent call last):
  File "membrane_permeability_graph_conv.py", line 76, in <module>
    model_dir='estimator')
  File "/anaconda3/envs/celgene_distributed/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1158, in make_estimator
    'This model requires %d feature column(s)' % len(self.features))
ValueError: This model requires 6 feature column(s)
(celgene_distributed) Saurabhs-MBP:membrane_permeability_examples_distributed saurabhmarathe$

**Comment by saurabhclusterone** [comment]
Thank You for the reply @peastman !

I ran the following note
<img width="1253" alt="screen shot 2018-08-21 at 3 22 28 pm" src="https://user-images.githubusercontent.com/41808263/44432652-c7f10780-a557-11e8-9e18-5dbfd1aaf238.png">
book from your website: https://deepchem.io/docs/notebooks/Estimators.html
It gives me "'module' object has no attribute MultiTaskClassifer" error.
I have attached the screenshot showing the same. Also I am referencing the issue #1142 

Hence, can you please give me a sure shot list of the models that support the estimator as of now? That would be really helpful for me to run the deepchem models in distributed mode.

Thank You!

**Comment by peastman** [comment]
>  It gives me "'module' object has no attribute MultiTaskClassifer" error.

In the current version of the code, the capitalization has changed to `MultitaskClassifier`.

> Hence, can you please give me a sure shot list of the models that support the estimator as of now?

MultitaskClassifier, MultitaskRegressor, RobustMultitaskClassifier, RobustMultitaskRegressor, Sequential.  Possibly some others too.  Anything that subclasses TensorGraph and doesn't override `default_generator()`.  Any models you create yourself by directly creating a TensorGraph and adding layers to it.
