### ISSUE TITLE
About "dc.molnet.load_pdbbind()"  I got some errors.

### ISSUE THREAD

**Issue by s-fukushima-a42** [deepchem/deepchem#1394]
**Description:**

- DeepChem Version: 2.1.1
- Platform: Linux Mint

I tried the dc.molnet.load_pdbbind(), according to the tutorial.
Then, some error came out. (Unable to add hydrogens math domain error?)
It looked like it was working fine along the way.

Is there anything I can do?

(I will try to featurize the original pdnbind data.)

Thank you.

```
...
Featurizing 174 / 195
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.016 s
WARNING:root:Unable to add hydrogens math domain error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in add_hydrogens_to_mol(mol)
     54     fixer.addMissingAtoms()
---> 55     fixer.addMissingHydrogens(7.4)
     56 

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py in addMissingHydrogens(self, pH)
   1018         modeller = app.Modeller(self.topology, self.positions)
-> 1019         modeller.addHydrogens(pH=pH)
   1020         self.topology = modeller.topology

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py in addHydrogens(self, forcefield, pH, variants, platform)
    751                                             break
--> 752                                         if isHbond(ne2Pos, he2Pos, acceptorPos):
    753                                             ne2IsBonded = True

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py in isHbond(d, h, a)
    680             deltaHA /= norm(deltaHA)
--> 681             return acos(dot(deltaDH, deltaHA)) < 50*degree
    682 

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/unit/unit_math.py in acos(x)
    102     """
--> 103     return math.acos(x) * radians
    104 

ValueError: 

During handling of the above exception, another exception occurred:

MoleculeLoadException                     Traceback (most recent call last)
<ipython-input-4-0feb7be32557> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind()

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, split, subset, reload)
    213   print("Featurizing Complexes")
    214   features = featurizer.featurize_complexes(
--> 215       ligand_files, protein_files, log_every_n=1)
    216   dataset = deepchem.data.DiskDataset.from_numpy(features, labels)
    217   # No transformations of data

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in featurize_complexes(self, mol_files, protein_pdbs, log_every_n)
   1325         protein_pdb_lines = protein_file.readlines()
   1326       features += self._featurize_complex(ligand_ext, mol_lines,
-> 1327                                           protein_pdb_lines)
   1328     features = np.asarray(features)
   1329     return features

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in _featurize_complex(self, ligand_ext, ligand_lines, protein_pdb_lines)
   1300     ############################################################## TIMING
   1301 
-> 1302     features_dict = self._transform(protein_pdb_file, ligand_file)
   1303     shutil.rmtree(tempdir)
   1304     return features_dict.values()

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in _transform(self, protein_pdb, ligand_file)
   1347 
   1348     protein_xyz, protein_rdk = load_molecule(
-> 1349         protein_pdb, calc_charges=True, sanitize=self.sanitize)
   1350     ############################################################## TIMING
   1351     time2 = time.time()

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in load_molecule(molecule_file, add_hydrogens, calc_charges, sanitize)
    121 
    122   if add_hydrogens or calc_charges:
--> 123     my_mol = add_hydrogens_to_mol(my_mol)
    124   # TODO: mol should be always sanitized when charges are calculated
    125   # can't change it now because it would break a lot of examples

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in add_hydrogens_to_mol(mol)
     64   except ValueError as e:
     65     logging.warning("Unable to add hydrogens %s", e)
---> 66     raise MoleculeLoadException(e)
     67   finally:
     68     try:

MoleculeLoadException: 
```
DeepChem Versio

**Comment by peastman** [comment]
The immediate error is that it tried to compute the `acos()` function, and the argument wasn't in the range [-1,1].  In order for that to happen, the atom positions must be messed up in some way.  For example, if two atoms were at exactly the same location, that would cause the error you're seeing.  But I don't know why that would be the case.

**Comment by rbharath** [comment]
I've seen a few of these errors before. I think some of the PDBBind PDBs are corrupted in some fashion. This has been on my TODO list to fix (by dropping the messed up PDBs). Will stick a bug tag on this issue and use to track

**Comment by s-fukushima-a42** [comment]
Additional Information:

- I tried featurize(rdkit_grid_fearutizer) the original PDB bind (core) dataset.
- The core dataset(ver.2017, CASF-2013-updated) was obtained from PDB bind webpage.
- The featurizing process stopped at some following proteins.
- PDB ID: **_3mss, 1hfs, 2jdy, 2jdu_**
- After I removed them and tried again, and I could get the results similar to the tutorial. The protein-ligand pairs were 191/195.

**Comment by s-fukushima-a42** [comment]
Additional Information - II (refined set version 2017)

_**5cep, 5cbs, 3tza, 2fqy, 4xit, 3si4, 3dyo, 3egt, 1ksn, 1px4, 
4cwq, 2f2h, 4jia, 3f37, 4cwp, 3i3b, 3qx5, 2ccc, 1sl3, 4wiv
3t2q, 3vd4, 5igm, 1k9s, 3t09, 3t0d, 2whp, 4cwo, 3vw2, 3mv0,
3t0x, 4cwt, 1n5r, 3vd9, 4cwr, 3t0b, 4cwn, 3t08, 3muz, 3qto,
3f34, 4cws, 3qwc, 4bps, 1q84, 4cwf, 3vdb, 3f33, 3arp, 2e94
1z71, 4kcx, 3qtv, 1mue**_

**Comment by s-fukushima-a42** [comment]
I tried "grid" featurizer.
It seems that it works well.

**Comment by s-fukushima-a42** [comment]
I tried this...
`PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="atomic", split="random", subset="core")`

However, I met the following errors.


```
Featurizing Complexes
WARNING:root:Unable to add hydrogens math domain error
WARNING:root:Some molecules cannot be loaded by Rdkit. Skipping

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/base_classes.py", line 18, in _featurize_complex
    return featurizer._featurize_complex(mol_pdb_file, protein_pdb_file)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 231, in _featurize_complex
    frag2_coords, frag2_mol = rdkit_util.load_molecule(protein_pdb_file)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 123, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 55, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 896, in addHydrogens
    LocalEnergyMinimizer.minimize(context, 1.0, 50)
  File "/home/satoshi/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 2631, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Particle coordinate is nan
"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-5-668939d284c9> in <module>()
      1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="atomic",
      2                                                                                                   split="random",
----> 3                                                                                                   subset="core")

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, split, subset, reload)
    236   print("Featurizing Complexes")
    237   features, failures = featurizer.featurize_complexes(ligand_files,
--> 238                                                       protein_files)
    239   # Delete labels for failing elements
    240   labels = np.delete(labels, failures)

~/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     53     failures = []
     54     for ind, result in enumerate(results):
---> 55       new_features = result.get()
     56       # Handle loading failures which return None
     57       if new_features is not None:

~/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

Exception: Particle coordinate is nan
```


(Does this have a cause in my environment?)

Thank you.

**Comment by rbharath** [comment]
Can you try again now with #1411 merged in?

**Comment by s-fukushima-a42** [comment]
After reflection, I tried it again.

The situation did not change, the same error occurred.
In both cases of "atomic" and "grid."

However, featurizing for the pdbbind dataset, which we downloaded from the original by ourselves, works fine (except for some files).

**Comment by bbrighttaer** [comment]
I also got a similar error while trying to load the pdbbind database:


/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py:1033: UserWarning: sanitize is set to False, pi_stack feature will be ignored
  feature_type)
/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py:1033: UserWarning: sanitize is set to False, cation_pi feature will be ignored
  feature_type)
Featurizing Complexes
WARNING:root:Unable to add hydrogens math domain error
WARNING:root:Some molecules cannot be loaded by Rdkit. Skipping
Traceback (most recent call last):
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/base_classes.py", line 16, in _featurize_complex
    return featurizer._featurize_complex(mol_pdb_file, protein_pdb_file)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 1243, in _featurize_complex
    protein_pdb_file, calc_charges=True, sanitize=self.sanitize)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 128, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 52, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 901, in addHydrogens
    LocalEnergyMinimizer.minimize(context, 1.0, 50)
  File "/home/bbrighttaer/anaconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 2631, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Particle coordinate is nan
"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-7-13013ef4197c> in <module>()
----> 1 pdbbind_tasks, pdbbind_datasets, transformers = dc.molnet.load_pdbbind(featurizer="grid", split="random", subset="core")
      2 train_dataset, valid_dataset, test_dataset = pdbbind_datasets

~/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, split, subset, reload)
    238   print("Featurizing Complexes")
    239   features, failures = featurizer.featurize_complexes(ligand_files,
--> 240                                                       protein_files)
    241   # Delete labels for failing elements
    242   labels = np.delete(labels, failures)

~/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     51     failures = []
     52     for ind, result in enumerate(results):
---> 53       new_features = result.get()
     54       # Handle loading failures which return None
     55       if new_features is not None:

~/anaconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

Exception: Particle coordinate is nan

**Comment by Iron4dam** [comment]
Same error here. @s-fukushima-a42 Does it work fine if we delete the set of data you mentioned above?

**Comment by Iron4dam** [comment]
For the core 2013 dataset, remove PDB ID: 2v7a, 2xbv.
