### ISSUE TITLE
Error in Conv1D

### ISSUE THREAD

**Issue by S-Dutta1** [deepchem/deepchem#1443]
Hello,

 I am using DeepChem 2.1.0. On running the source code provided in [Solving the RNA design problem with reinforcement learning](https://journals.plos.org/ploscompbiol/article/file?id=10.1371/journal.pcbi.1006176&type=printable), the following error occurs. The authors mention that it was tested with DeepChem 1.3.1. Is there some fix to run it on the latest version ?

The following command is used : python solve_one_puzzle.py "(((((((.(.(.(.(((((((....)))))))))))))))))"

```
Traceback (most recent call last):
  File "solve_one_puzzle.py", line 12, in <module>
    a3c = dc.rl.A3C(env, policy, model_dir='best_model')
  File "/home/srijit/miniconda3/lib/python3.5/site-packages/deepchem/rl/a3c.py", line 159, in __init__
    fields = self._build_graph(None, 'global', model_dir)
  File "/home/srijit/miniconda3/lib/python3.5/site-packages/deepchem/rl/a3c.py", line 181, in _build_graph
    policy_layers = self._policy.create_layers(features)
  File "/home/srijit/Desktop/SI/rnalib.py", line 176, in create_layers
    conv1 = create_conv7(state[0], self.length, indices, width)
  File "/home/srijit/Desktop/SI/rnalib.py", line 149, in create_conv7
    return layers.Conv1D(width=w, stride=w, out_channels=n_outputs, in_layers=gather)
TypeError: __init__() missing 2 required positional arguments: 'filters' and 'kernel_size'

```

**Comment by peastman** [comment]
Those arguments have just gotten renamed.  Change `width` to `kernel_size` and `out_channels` to `filters` and it should work.

**Comment by S-Dutta1** [comment]
Thank you for the response. That issue is resolved on making the changes, however, another error occurs 

```
Traceback (most recent call last):
  File "solve_one_puzzle.py", line 12, in <module>
    a3c = dc.rl.A3C(env, policy, model_dir='best_model')
  File "/home/srijit/miniconda3/lib/python3.5/site-packages/deepchem/rl/a3c.py", line 159, in __init__
    fields = self._build_graph(None, 'global', model_dir)
  File "/home/srijit/miniconda3/lib/python3.5/site-packages/deepchem/rl/a3c.py", line 181, in _build_graph
    policy_layers = self._policy.create_layers(features)
  File "/home/srijit/Desktop/SI/rnalib.py", line 177, in create_layers
    conv2 = create_residual(conv1, self.length, indices, width)
  File "/home/srijit/Desktop/SI/rnalib.py", line 154, in create_residual
    conv = create_conv7(parent, length, indices, n_outputs)
  File "/home/srijit/Desktop/SI/rnalib.py", line 148, in create_conv7
    w = gather.shape[1]//length
  File "/home/srijit/miniconda3/lib/python3.5/site-packages/deepchem/models/tensorgraph/layers.py", line 140, in shape
    "%s: shape is not known" % self.__class__.__name__)
NotImplementedError: GatherBonds: shape is not known
```

**Comment by peastman** [comment]
I'm not sure what's changed to cause that.  I'll have to debug it.  In the mean time, it might be easiest to use the version of DeepChem the script was originally written with.  All past versions are available at https://github.com/deepchem/deepchem/releases.  Or if you want to install with conda, you can just specify the version number you want, as in https://github.com/deepchem/deepchem#easy-install-via-conda.

**Comment by S-Dutta1** [comment]
I tried installing the previous version, downloaded the source code form [https://github.com/deepchem/deepchem/releases/tag/1.3.1](https://github.com/deepchem/deepchem/releases/tag/1.3.1) then ran ```bash scripts/install_deepchem_conda.sh deepchem``` and ```source activate deepchem```

However, ```python setup.py install``` fails with the following error message 

```
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/core.py", line 96, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/util.py", line 259, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/home/srijit/miniconda3/envs/deepchem/lib/python3.5/site-packages/pbr/packaging.py", line 839, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name deepchem was given, but was not able to be found.
error in setup command: Error parsing /home/srijit/Downloads/deepchem-1.3.1/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name deepchem was given, but was not able to be found.
```

As per installing with conda via ```conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.1```, following error occurs

```
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - deepchem=1.3.1 -> icu==56.1
  - libboost
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by VIGS25** [comment]
@peastman: The current implementation of Conv1D doesn't seem to have `self._shape` at all. In fact, there's a TODO on the same.

**Comment by S-Dutta1** [comment]
Any other alternatives to install version 1.3.1 ?

**Comment by farezaur** [comment]
still having the same issues while installing codes for ( Solving the RNA design problem with reinforcement learning). Any way around these issues?

**Comment by rbharath** [comment]
@farezaur Are you on the latest version of DeepChem with #1450 merged in?
