### ISSUE TITLE
MPNNTensorGraph training gets unexpected errors

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1449]
When I used the MPNNTensorGraph model to train HIV.csv data, I got an unexpected error in training on the cluster:
```
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1361, in _do_call
    return fn(*args)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[186446,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: gradients/MessagePassing_6/mul_8_grad/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/MessagePassing_6/Sum_2_grad/Tile, MessagePassing_6/Reshape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: Adam/update/_1112 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29917_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/worker/bin/run.py", line 375, in task_main
    await module_run(api) if iscoroutinefunction(module_run) else module_run(api)
  File "/worker/package/smiles_package_MPNN_y6Kzr/train_model/__init__.py", line 134, in run
    callbacks=[processcallback])
  File "/worker/package/smiles_package_MPNN_y6Kzr/MPNN_tensorgraph.py", line 223, in fit_generator
    fetched_values = self.session.run(fetches, feed_dict=train_generator)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[186446,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: gradients/MessagePassing_6/mul_8_grad/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/MessagePassing_6/Sum_2_grad/Tile, MessagePassing_6/Reshape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: Adam/update/_1112 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29917_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.


Caused by op 'gradients/MessagePassing_6/mul_8_grad/mul', defined at:
  File "main.py", line 32, in <module>
    main()
  File "main.py", line 28, in main
    router.task_run()
  File "/worker/bin/router.py", line 129, in task_run
    p.start()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 80, in _launch
    code = process_obj._bootstrap()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/anaconda3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/worker/bin/router.py", line 111, in run_worker
    run([worker])
  File "/atlas/home/test/.local/lib/python3.6/site-packages/autobahn/asyncio/component.py", line 373, in run
    loop.run_forever()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/usr/local/anaconda3/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/worker/bin/router.py", line 38, in onJoin
    api = await task_main(task_id)
  File "/worker/bin/run.py", line 375, in task_main
    await module_run(api) if iscoroutinefunction(module_run) else module_run(api)
  File "/worker/package/smiles_package_MPNN_y6Kzr/train_model/__init__.py", line 117, in run
    model = MPNN_fit.load_from_dir(model_dir)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 818, in load_from_dir
    tensorgraph.restore()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 785, in restore
    self.build()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 486, in build
    self._get_tf('train_op')
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 742, in _get_tf
    self.loss.out_tensor, global_step=global_step)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 359, in minimize
    grad_loss=grad_loss)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 460, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 611, in gradients
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 377, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 611, in <lambda>
    lambda: grad_fn(op, *out_grads))
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py", line 797, in _MulGrad
    return (array_ops.reshape(math_ops.reduce_sum(grad * y, rx), sx),
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 934, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1161, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2789, in _mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'MessagePassing_6/mul_8', defined at:
  File "main.py", line 32, in <module>
    main()
[elided 18 identical lines from previous traceback]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 785, in restore
    self.build()
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 476, in build
    layer.create_tensor(training=self._training_placeholder)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/graph_layers.py", line 886, in create_tensor
    message = self.message_function.forward(out, atom_to_pair)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/deepchem/models/tensorgraph/graph_layers.py", line 928, in forward
    out = tf.reduce_sum(out * self.A, axis=1)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 934, in binary_op_wrapper
    return func(x, y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py", line 1161, in _mul_dispatch
    return gen_math_ops._mul(x, y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_math_ops.py", line 2789, in _mul
    "Mul", x=x, y=y, name=name)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3271, in create_op
    op_def=op_def)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[186446,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[Node: gradients/MessagePassing_6/mul_8_grad/mul = Mul[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/MessagePassing_6/Sum_2_grad/Tile, MessagePassing_6/Reshape)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[Node: Adam/update/_1112 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_29917_Adam/update", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

```

What is the problem? Is it OOM? But I used two GPU training to get the following mistakes:
```
2018-11-12 17:23:28.477701: F ./tensorflow/core/util/cuda_launch_config.h:127] Check failed: work_element_count > 0 (-2110267296 vs. 0)
srun: error: node2: task 0: Aborted
```

@raphtown 
Can you give me some good suggestions?

**Comment by Iron4dam** [comment]
Have you succeeded? I got a different error while training MPNN on the same dataset. Here's my error:
```
2019-02-05 23:02:55.096153: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1373, in _enqueue_batch
    for feed_dict in generator:
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 954, in default_generator
    (n_atoms * n_atoms, self.n_pair_feat)))
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 36414 into shape (2601,8)
```

Here's my code:
```
hiv_tasks, (train_wv, valid_wv, test_wv), transformers = load_hiv(featurizer='Weave')
model = deepchem.models.MPNNModel(
		len(hiv_tasks),
		mode="classification")
model.fit(train_wv)
```

**Comment by gack951** [comment]
@Iron4dam Hi, have you succeeded? I think you should specify the number of features for MPNNModel to use featurizer='Weave' like an example code below.
```
hiv_tasks, (train_wv, valid_wv, test_wv), transformers = load_hiv(featurizer='Weave')
model = deepchem.models.MPNNModel(
		len(hiv_tasks),
		mode="classification",
		n_atom_feat=75,
		n_pair_feat=14)
model.fit(train_wv)
```

**Comment by gack951** [comment]
I'm trying MPNNModel and I encountered an OOM error same as the first comment of this issue when I use a large dataset.
My code (oom_test.py):
```
import deepchem as dc

featurizer=dc.feat.graph_features.WeaveFeaturizer()
loader=dc.data.SDFLoader(tasks=["value1"], featurizer=featurizer, clean_mols=True)
dataset_file="chembl_26_value1_10000.sdf"
dataset=loader.featurize(dataset_file)
train_dataset, _, _=dc.splits.ScaffoldSplitter().train_valid_test_split(dataset)
transformer=dc.trans.NormalizationTransformer(transform_y=True, dataset=train_dataset)
train_dataset=transformer.transform(train_dataset)

model=dc.models.MPNNModel(1, n_atom_feat=75, n_pair_feat=14, batch_size=1)
model.fit(train_dataset, 10)
```
then I got:
```
2020-04-29 02:49:43.473931: W tensorflow/core/common_runtime/bfc_allocator.cc:271] **********************_****************************************************************_____________                           2020-04-29 02:49:43.473975: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at batch_matmul_op_impl.h:582 : Resource exhausted: OOM when allocating tensor with shape[57121,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "/miniconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/miniconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/miniconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[57121,100,100] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node gradients/MessagePassing_7/MatMul_grad/MatMul}} = BatchMatMul[T=DT_FLOAT, adj_x=false, adj_y=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](gradients/MessagePassing_7/Squeeze_grad/Reshape, MessagePassing_7/ExpandDims)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

During handling of the above exception, another exception occurred:
...
```
The dataset file "chembl_26_value1_10000.sdf" contains 10000 molecules I extracted from ChEMBL database release 26, and I added "value1" for prediction.
chembl_26_value1_10000.sdf:
```
CHEMBL4
     RDKit          2D

 26 29  0  0  0  0  0  0  0  0999 V2000
   -0.8793    0.0317    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
   -0.8793    0.8567    0.0000 C   0  0  0  0  0  0  0  0  0  0  0  0
...
    2.6930    2.0942    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
    3.4075    0.8567    0.0000 O   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0
  2  3  2  0
...
 24 25  1  0
 24 26  2  0
M  END
> <chembl_id>
CHEMBL4

> <value1>
0.2041199827

$$$$
CHEMBL5
...
```
My code worked with smaller datasets (1000 and 4000 molecules), but does not with large ones (8000 and 10000). I already reduced batch_size to only 1 for 4000 molecules.

I'm using the official docker image like
```
$ docker run -it --gpus '"device=0"' deepchemio/deepchem
# python oom_test.py
```
My setup:
* Ryzen Threadripper 3960X (24/48)
* 64GM RAM
* RTX 2080 Ti (11GB memory)
* Debian 10 buster
* docker version 19.03.8
* docker image: deepchemio/deepchem:latest (released on 5/4/2019 3:04 am)
    * Python 3.6.6
    * Tensorflow 1.12.0
    * deepchem 2.1.1

I found a "TODO" comment in the source by @rbharath
models/models.py:115
```
  def fit(self, dataset, nb_epoch=10, batch_size=50, **kwargs):
    """
    Fits a model on data in a Dataset object.
    """
    # TODO(rbharath/enf): We need a structured way to deal with potential GPU
    #                     memory overflows.
```
So @rbharath do you have any idea for this issue? Is docker image not the best way? I'm just a noob in deep learning, so I'm happy if you give me some help. Thanks in advance!

**Comment by rbharath** [comment]
@gack951 Sorry for the slow response! This slipped through my inbox (in general if I'm slow to respond, feel free to ping me on the gitter).

A couple ideas here. The docker image is a little out of date. I'll try to get a more recent docker image up alongside the 2.4.0rc but that'll probably be a month out. In the meanwhile, could you try installing 2.3.0 DeepChem using conda or the source install?

It might also be useful to try running your example on Colab so you can run 2.3.0 without having to install locally (https://forum.deepchem.io/t/getting-deepchem-running-in-colab/81). 

There's likely still a deeper problem of memory management here. I'm deep in the middle of some other refactoring, but I'll try to circle back to this later once I get a chance.

**Comment by gack951** [comment]
@rbharath Thank you for your reply and suggestions. I'm trying the GPU and TPU runtimes in Colab, and surprised by the powerful computing without payment... Also, I'm going to use the conda or source install locally.

I hope I will be able to run those models with big datasets in personal GPUs, so I'm looking forward to the good news about the problems. Thanks again!
