### ISSUE TITLE
IndexError when running MoleculeNet

### ISSUE THREAD

**Issue by Iron4dam** [deepchem/deepchem#1502]
**Description:**

- DeepChem Version: 2.1.1
- Platform: MacOS 10.14.2

I encountered an IndexError when running random forest regression in MoleculeNet on the PDBbind dataset. The error appears in deepchem/models/multitask.py line 71.  Here's my code:

```
from deepchem.molnet.run_benchmark_models import benchmark_regression
from deepchem.molnet.load_function.pdbbind_datasets import featurize_pdbbind, load_pdbbind_grid, load_pdbbind
from deepchem.metrics import rms_score, mae_score
import os, tempfile

pdbbind_tasks, all_dataset, transformers = load_pdbbind(subset="core", featurizer="grid")
(train, valid, test) = all_dataset

train_scores, valid_scores, test_scores = benchmark_regression(train, valid, test, pdbbind_tasks, transformers, n_features=1024, metric=rms_score, model='rf_regression', test=False, hyper_parameters=None, seed=123)
```

Here's the error I got:

```
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
About to initialize singletask to multitask model
Initializing directory for task -logKd/Ki
-----------------------------
Start fitting: rf_regression
About to create task-specific datasets
Splitting multitask dataset into singletask datasets
TIMING: dataset construction took 0.007 s
Loading dataset from disk.
Processing shard 0
	Task 0
Traceback (most recent call last):
  File "testing.py", line 10, in <module>
    train_scores, valid_scores, test_scores = benchmark_regression(train, valid, test, pdbbind_tasks, transformers, n_features=1024, metric=rms_score, model='rf_regression', test=False, hyper_parameters=None, seed=123)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/molnet/run_benchmark_models.py", line 763, in benchmark_regression
    model.fit(train_dataset)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/multitask.py", line 95, in fit
    task_datasets = self._create_task_datasets(dataset)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/multitask.py", line 48, in _create_task_datasets
    task_datasets = self._to_singletask(dataset, task_data_dirs)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/multitask.py", line 71, in _to_singletask
    w_task = w[:, task_num]
IndexError: too many indices for array
```

Seems the `w` and `y` at that place (multitask.py line 71) shouldn't be 2 dimensional arrays. Could someone help me out? Many thanks.

**Comment by VIGS25** [comment]
@Iron4dam, will have a look at this!

**Comment by VIGS25** [comment]
I was unable to reproduce the error. Your script has two bugs which are fixed here:

``` 
from deepchem.molnet.run_benchmark_models import benchmark_regression
from deepchem.molnet.load_function.pdbbind_datasets import featurize_pdbbind, load_pdbbind_grid, load_pdbbind
from deepchem.metrics import rms_score, mae_score
   
pdbbind_tasks, all_dataset, transformers = load_pdbbind(subset="core", featurizer="grid")
(train, valid, test) = all_dataset

train_scores, valid_scores, test_scores = benchmark_regression(train, valid, test, pdbbind_tasks, transformers, n_features=1024, metric=[dc.metrics.Metric(rms_score)], model='rf_regression', test=False, hyper_parameters=None, seed=123) 
```

**Comment by Iron4dam** [comment]
@VIGS25 Many thanks for your help!
