### ISSUE TITLE
MPNN Value Error

### ISSUE THREAD

**Issue by Iron4dam** [deepchem/deepchem#1505]
**Description:**

- DeepChem Version: 2.1.1
- Platform: MacOS 10.14.2

Encountered a dimensionality error when the model tried to reshape pair features. My sample code:
```
import deepchem 
from deepchem.molnet.load_function.hiv_datasets import load_hiv

hiv_tasks, (train_wv, valid_wv, test_wv), transformers = load_hiv(featurizer='Weave')
model = deepchem.models.MPNNModel(
		len(hiv_tasks),
		mode="classification")
model.fit(train_wv)
```

The error I got:
```
2019-02-05 23:02:55.096153: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1373, in _enqueue_batch
    for feed_dict in generator:
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 954, in default_generator
    (n_atoms * n_atoms, self.n_pair_feat)))
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 279, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 36414 into shape (2601,8)
```

**Comment by VIGS25** [comment]
The error is happening, because `WeaveFeaturizer` computes `pair_features` of shape `(51, 51, 14)`, but the `n_pair_feat` argument supplied is 8. The code below should run without errors:

```import deepchem 
from deepchem.molnet.load_function.hiv_datasets import load_hiv

hiv_tasks, (train_wv, valid_wv, test_wv), transformers = load_hiv(featurizer='Weave')
model = deepchem.models.MPNNModel(
		len(hiv_tasks),
                n_pair_feat=14,
		mode="classification")
model.fit(train_wv)
```

**Comment by Iron4dam** [comment]
@VIGS25 Many thanks for your reply. The first time I added `n_pair_feat = 14` I got the following error:
```
2019-02-06 09:43:42.236702: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1384, in _enqueue_batch
    sess.run(tg.input_queue.out_tensor, feed_dict=enq)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (2461, 75) for Tensor 'Feature_9_pre_q/Placeholder:0', which has shape '(?, 70)'
```

Then I further added  `n_atom_feat = 75` and this error was gone. But I got another error at the start of training:
```
2019-02-06 09:47:13.618577: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/Users/iron4dam/anaconda3/envs/rdkit/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
2019-02-06 09:47:45.856832: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-06 09:47:46.163422: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-06 09:47:47.753486: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-06 09:47:47.939601: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
```
Should I fix `n_pair_feat = 14` and `n_atom_feat = 75` in the future? And is the graph featurized by Weave undirected so that it couldn't be sorted in topological order?

**Comment by VIGS25** [comment]
Hi, 
Sorry for the delayed response.
I'll have to look into the mechanics of the `WeaveMol` object, and check this.

**Comment by Iron4dam** [comment]
@VIGS25 Many thanks for your help! I'm trying to reproduce molnet results and doing some multi class classifications. Is the mpnn model runnable on your system? I'll take a look into the featurizer source code as well.

**Comment by VIGS25** [comment]
@Iron4dam: I wouldn't think so, but I'll try getting it running over the next couple of days. I also have to check if the `WeaveFeaturizer` and MPNN model are meant to be compatible.

**Comment by Iron4dam** [comment]
@VIGS25 There're four featurizers that molnet implemented for this dataset: `ECFP`, `GraphConv`, `Weave` and `Raw`. I tried the last three but both `GraphConv` and `Raw` featurizers raised a similar error that `ConvMol` or `Mol` has no attribute `get_pair_features`:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-379-b7e7fa1f8aae> in <module>
      1 tic = time.time()
      2 mp_model, epoch = load_model('mpnn', multiclass=False)
----> 3 mp_model.fit(train_gc, nb_epoch=1)
      4 toc = time.time()
      5 print('time taken %.2fs' %(toc-tic))

~/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, submodel, **kwargs)
    153         self.default_generator(
    154             dataset, epochs=nb_epoch, deterministic=deterministic),
--> 155         max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
    156 
    157   def fit_generator(self,

~/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in fit_generator(self, feed_dict_generator, max_checkpoints_to_keep, checkpoint_interval, restore, submodel)
    231                   self.session, n_enqueued, final_sample))
    232         enqueue_thread.start()
--> 233       for feed_dict in self._create_feed_dicts(feed_dict_generator, True):
    234         if self.queue_installed:
    235           # Don't let this thread get ahead of the enqueue thread, since if

~/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py in _create_feed_dicts(self, generator, training)
   1144         yield {self._training_placeholder: train_value}
   1145     else:
-> 1146       for d in generator:
   1147         feed_dict = {}
   1148         for key, value in d.items():

~/anaconda3/envs/rdkit/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py in default_generator(self, dataset, epochs, predict, deterministic, pad_batches)
    951           # pair features
    952           pair_feat.append(
--> 953               np.reshape(mol.get_pair_features(),
    954                          (n_atoms * n_atoms, self.n_pair_feat)))
    955 

AttributeError: 'ConvMol' object has no attribute 'get_pair_features'
```
So I think the only possible one should be `Weave`.

**Comment by VIGS25** [comment]
@Iron4dam, even though four featurizers are implemented with the HIV Dataset, they are not necessarily all compatible with the `MPNNModel`. So I agree, that Weave should only work.

Can you give me sometime to look into this?

**Comment by Iron4dam** [comment]
@VIGS25 no problem, thanks so much for your help!

**Comment by VIGS25** [comment]
```
import deepchem
from deepchem.molnet.load_function.hiv_datasets import load_hiv
import numpy as np

hiv_tasks, (train_wv, valid_wv, test_wv), transformers = load_hiv(featurizer='Weave')

X = train_wv.X[:1]
y = train_wv.y[:1]

new_dataset = deepchem.data.NumpyDataset(X, y)
model = deepchem.models.MPNNModel(
  len(hiv_tasks),
  n_pair_feat=14,
  n_atom_feat=75,
  n_hidden=75,
  T=1, M=1,
  mode="classification")

metric = deepchem.metrics.Metric(deepchem.metrics.roc_auc_score, np.mean, mode="classification")
model.fit(new_dataset, nb_epoch=10)

scores = model.evaluate(test_wv, [metric], transformers)
print(scores['mean-roc_auc_score'])```

The script above ran on my laptop with no errors, but I was able to train with only a single sample, otherwise my `TensorFlow` was getting killed.

**Comment by Iron4dam** [comment]
@VIGS25 Many thanks! It ran successfully on my computer as well except for a few error messages in the middle which are same as above that the graph couldn't be sorted in topological order. I guess these might occur because the `WeaveFeaturizer` output undirected graphs. I will have a double check the original message passing paper to see what featurizing method they're using. Also I could actually run 10 samples and get the output.

```
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
2019-02-12 23:37:43.243944: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-02-12 23:37:45.013865: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-12 23:37:45.043837: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-12 23:37:45.198550: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2019-02-12 23:37:45.215290: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:666] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
computed_metrics: [0.4196032859886457]
0.4196032859886457
```

**Comment by VIGS25** [comment]
I think it has more to do with TensorFlow's computation graph rather than the Weave Featurizer, as the message seems to be from Tf optimizers.

**Comment by Iron4dam** [comment]
@VIGS25 yeah I think you're right. I'm thinking the `Weave` featurizer might not be a good choice for MPNN, since the original dataset was about quantum chemistry and they used some other quantum featurizers. Have you tried using MPNN with non-quantum chemistry dataset before?

**Comment by VIGS25** [comment]
Nope, I have never used the MPNN model before. To be honest, I haven't gone through its paper as well.
Also, could you close this issue? - Feel free to reopen if necessary?

**Comment by JonathanBroadbent** [comment]
Hi I am reopening this issue because I am having trouble which featurizer to use with MPNN model.
The [docs page](https://deepchem.readthedocs.io/en/latest/api_reference/models.html#model-cheatsheet) says to use MolGraphConvFeaturizer
When I try that I receive the following error:
``` 
/tmp/ipykernel_12793/853907312.py in train(model, train_data, val_data, epochs, patience)
      8     print("Training MPNN...")
      9     for i in range(epochs):
---> 10         model.fit(train_data, nb_epoch=10, checkpoint_interval=0)
     11         train_pred = model.predict(train_data).squeeze()[:, 1]
     12         train_scores.append(log_loss(train_data.y, train_pred))

~/storage/mambaforge/envs/deepchem/lib/python3.7/site-packages/deepchem/models/keras_model.py in fit(self, dataset, nb_epoch, max_checkpoints_to_keep, checkpoint_interval, deterministic, restore, variables, loss, callbacks, all_losses)
    354                                deterministic=deterministic),
    355         max_checkpoints_to_keep, checkpoint_interval, restore, variables, loss,
--> 356         callbacks, all_losses)
    357 
    358   def fit_generator(self,

~/storage/mambaforge/envs/deepchem/lib/python3.7/site-packages/deepchem/models/keras_model.py in fit_generator(self, generator, max_checkpoints_to_keep, checkpoint_interval, restore, variables, loss, callbacks, all_losses)
    427     # Main training loop.
...
-> 1190           n_atoms = mol.get_num_atoms()
   1191           # number of atoms in each molecule
   1192           atom_split.extend([im] * n_atoms)

AttributeError: 'GraphData' object has no attribute 'get_num_atoms'
```
Then when I try to use WeaveFeaturizer I stumble upon the same errors as stated above. Is there a fix for this yet?
