### ISSUE TITLE
Inconsistent array sizes in QM7

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1531]
`TestMolnet.test_qm7_multitask()` is currently failing in the master branch:

```
Traceback (most recent call last):
  File "/Users/peastman/workspace/deepchem/deepchem/molnet/tests/test_molnet.py", line 64, in test_qm7_multitask
    reload=False)
  File "/Users/peastman/workspace/deepchem/deepchem/molnet/run_benchmark.py", line 154, in run_benchmark
    featurizer=featurizer, split=split, reload=reload)
  File "/Users/peastman/workspace/deepchem/deepchem/molnet/load_function/qm7_datasets.py", line 88, in load_qm7_from_mat
    dataset)
  File "/Users/peastman/workspace/deepchem/deepchem/splits/splitters.py", line 153, in train_valid_test_split
    train_dataset = dataset.select(train_inds, train_dir)
  File "/Users/peastman/workspace/deepchem/deepchem/data/datasets.py", line 1255, in select
    generator(), data_dir=select_dir, tasks=tasks, verbose=self.verbose)
  File "/Users/peastman/workspace/deepchem/deepchem/data/datasets.py", line 565, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/Users/peastman/workspace/deepchem/deepchem/data/datasets.py", line 1238, in generator
    y_sel = y[shard_inds]
IndexError: index 4 is out of bounds for axis 0 with size 1
```

This is caused by the following code in qm7_datasets.py:

```python
  if featurizer == 'CoulombMatrix':
    dataset_file = os.path.join(data_dir, "qm7.mat")

    if not os.path.exists(dataset_file):
      deepchem.utils.download_url(
          'http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/qm7.mat'
      )
    dataset = scipy.io.loadmat(dataset_file)
    X = dataset['X']
    y = dataset['T']
```

It's just downloading the data from AWS and loading `X` and `y`.  Unfortunately, they have inconsistent shapes.  `X` is (7165, 23, 23), and `y` is (1, 7165).  I'm assuming `y` really ought to be (7165, 1)?  I can work around this by adding a call to `reshape()`, but is this something that ought to be fixed in the original data file?

**Comment by peastman** [comment]
Fixed by #1535.
