### ISSUE TITLE
Message "mkl-random 1.0.1 requires cython, which is not installed." shows up in installation, and first test failed

### ISSUE THREAD

**Issue by ZuoyiLi** [deepchem/deepchem#1543]
**Description:**
Hi, I am not very experienced with git yet, I ran the following commands to install deepchem:
    git clone https://github.com/deepchem/deepchem.git  
    cd deepchem/
    gpu=0 bash scripts/install_deepchem_conda.sh deepchem
    source activate deepchem
    python setup.py install                                # Manual install
    nosetests -a '!slow' -v deepchem --nologcapture        # Run tests

- DeepChem Version: 2.1.0(Latest as of March 22nd, 2019)
- Platform: linux 4.15.0-46-generic

In the installation process, the red message "mkl-random 1.0.1 requires cython, which is not installed." shows up in following part. 

`## Package Plan ##

  environment location: /u/z/u/zuoyi/anaconda3/envs/deepchem

  added / updated specs: 
    - pdbfixer=1.4

The following NEW packages will be INSTALLED:

    blas:           1.0-mkl                     
    fftw3f:         3.3.4-2                omnia
    intel-openmp:   2019.3-199                  
    libgfortran-ng: 7.3.0-hdf63c60_0            
    mkl:            2018.0.3-1                  
    mkl_fft:        1.0.6-py35h7dd41cf_0        
    mkl_random:     1.0.1-py35h4414c95_1        
    numpy:          1.15.2-py35h1d66e8a_0       
    numpy-base:     1.15.2-py35h81de0dd_0       
    openmm:         7.3.1-py35_cuda92_rc_2 omnia
    pdbfixer:       1.4-py35_0             omnia

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting pip
  Using cached https://files.pythonhosted.org/packages/d8/f3/413bab4ff08e1fc4828dfc59996d721917df8e8583ea85385d51125dceff/pip-19.0.3-py2.py3-none-any.whl
mkl-random 1.0.1 requires cython, which is not installed.
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.0.3
Solving environment: ...working... done
`

And after the installation was finished, I ran the following command: 
source activate deepchem
python setup.py install                                # Manual install
nosetests -a '!slow' -v deepchem --nologcapture        # Run tests

The following message showed up:

`$ nosetests -a '!slow' -v deepchem --nologcapture
Failure: ModuleNotFoundError (No module named 'joblib') ... ERROR

======================================================================
ERROR: Failure: ModuleNotFoundError (No module named 'joblib')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/site-packages/nose/loader.py", line 417, in loadTestsFromName
    addr.filename, addr.module)
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/u/z/u/zuoyi/anaconda3/lib/python3.7/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/afs/cs.wisc.edu/u/z/u/zuoyi/deepchem/deepchem/__init__.py", line 9, in <module>
    import deepchem.data
  File "/afs/cs.wisc.edu/u/z/u/zuoyi/deepchem/deepchem/data/__init__.py", line 9, in <module>
    from deepchem.data.datasets import pad_features
  File "/afs/cs.wisc.edu/u/z/u/zuoyi/deepchem/deepchem/data/datasets.py", line 13, in <module>
    from deepchem.utils.save import save_to_disk, save_metadata
  File "/afs/cs.wisc.edu/u/z/u/zuoyi/deepchem/deepchem/utils/save.py", line 9, in <module>
    import joblib
ModuleNotFoundError: No module named 'joblib'

----------------------------------------------------------------------
Ran 1 test in 0.017s

FAILED (errors=1)
`

What should I do to fix the installation? Thank you!

```
Your code sample here
```

**Comment by ZuoyiLi** [comment]
I reinstalled the environment with command "bash scripts/install_deepchem_conda.sh deepchem" instead of "gpu=0 bash scripts/install_deepchem_conda.sh deepchem" fixed this issue. The nosetest could finish although I met one error.
