### ISSUE TITLE
Number of features calculated does not match model

### ISSUE THREAD

**Issue by fredrikszm** [deepchem/deepchem#1565]
DeepChem Version: 2.1.0
Platform: OS; python 3.5

I have trained a Grid-Random Forest regression model on the PDBBind core dataset that has been featurized with the grid featurizer (loaded disk dataset). I now want to have this model make predictions on a new protein and ligand so I used the RdkitGridFeaturizer on the files. The problem I'm having is that the number of features calculated using this featurizer (19968) does not match the number of features the model was trained on (2052). 

Any advice on what I'm missing or how I can fix this problem would be greatly appreciated!

**This is the featurizer:**
grid_featurizer = dc.feat.RdkitGridFeaturizer(
    voxel_width=2.0, feature_types=['hbond', 'salt_bridge', 'pi_stack','ecfp','cation_pi', 'splif'], 
    sanitize=True, flatten=True)

**This is how I loaded in the pre-featurized dataset:**
PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(featurizer="grid", reload=False)

**Comment by VIGS25** [comment]
What did you use as input to train the model?

**Comment by fredrikszm** [comment]
I used the train_dataset loaded in from dc.molnet.load_pdbbind_grid

**Comment by VIGS25** [comment]
Why don't you try running `dc.molnet.load_pdbbind` and run the featurization there instead of `load_pdbbind_grid`. The dataset is already featurized, and I'm not sure of the arguments used.

**Comment by fredrikszm** [comment]
I ran it using load_pdbbind and it gave me the following error:


FileNotFoundError                         Traceback (most recent call last)
<ipython-input-282-2f95ec528bc3> in <module>()
      1 #PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(featurizer="grid", reload=False)
----> 2 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="grid", reload=False)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, load_binding_pocket, split, subset, reload)
    188   # Extract locations of data
    189   pdbs = []
--> 190   with open(index_file, "r") as g:
    191     lines = g.readlines()
    192     for line in lines:

FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T/v2015/INDEX_core_name.2013'

**Comment by fredrikszm** [comment]
I deleted pdbbind_v2015.tar.gz and the v2015 folder from /var/folders/bh/37q8tg8s5lzdynsgpklkf_k00000gn/T. Then I ran the function again so it would reload the dataset. I got output for it featurizing many pdb files, then it stopped due to the following error (this is the same error that I mentioned in the other issue I opened, when trying to run load_pdb using 'atomic' featurization):

WARNING:root:Unable to add hydrogens math domain error

ValueError                                Traceback (most recent call last)
~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in add_hydrogens_to_mol(mol)
     54     fixer.addMissingAtoms()
---> 55     fixer.addMissingHydrogens(7.4)
     56 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/pdbfixer/pdbfixer.py in addMissingHydrogens(self, pH)
   1018         modeller = app.Modeller(self.topology, self.positions)
-> 1019         modeller.addHydrogens(pH=pH)
   1020         self.topology = modeller.topology

~/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/openmm/app/modeller.py in addHydrogens(self, forcefield, pH, variants, platform)
    751                                             break
--> 752                                         if isHbond(ne2Pos, he2Pos, acceptorPos):
    753                                             ne2IsBonded = True

~/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/openmm/app/modeller.py in isHbond(d, h, a)
    680             deltaHA /= norm(deltaHA)
--> 681             return acos(dot(deltaDH, deltaHA)) < 50*degree
    682 

~/miniconda2/envs/mypy/lib/python3.5/site-packages/simtk/unit/unit_math.py in acos(x)
    102     """
--> 103     return math.acos(x) * radians
    104 

ValueError: 

During handling of the above exception, another exception occurred:

MoleculeLoadException                     Traceback (most recent call last)
<ipython-input-2-2f95ec528bc3> in <module>()
      1 #PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind_grid(featurizer="grid", reload=False)
----> 2 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="grid", reload=False)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(featurizer, load_binding_pocket, split, subset, reload)
    275   print("Featurizing Complexes")
    276   features, failures = featurizer.featurize_complexes(ligand_files,
--> 277                                                       protein_files)
    278   # Delete labels for failing elements
    279   labels = np.delete(labels, failures)

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in featurize_complexes(self, mol_files, protein_pdbs, log_every_n)
   1325         protein_pdb_lines = protein_file.readlines()
   1326       features += self._featurize_complex(ligand_ext, mol_lines,
-> 1327                                           protein_pdb_lines)
   1328     features = np.asarray(features)
   1329     return features

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in _featurize_complex(self, ligand_ext, ligand_lines, protein_pdb_lines)
   1300     ############################################################## TIMING
   1301 
-> 1302     features_dict = self._transform(protein_pdb_file, ligand_file)
   1303     shutil.rmtree(tempdir)
   1304     return features_dict.values()

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py in _transform(self, protein_pdb, ligand_file)
   1347 
   1348     protein_xyz, protein_rdk = load_molecule(
-> 1349         protein_pdb, calc_charges=True, sanitize=self.sanitize)
   1350     ############################################################## TIMING
   1351     time2 = time.time()

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in load_molecule(molecule_file, add_hydrogens, calc_charges, sanitize)
    121 
    122   if add_hydrogens or calc_charges:
--> 123     my_mol = add_hydrogens_to_mol(my_mol)
    124   # TODO: mol should be always sanitized when charges are calculated
    125   # can't change it now because it would break a lot of examples

~/miniconda2/envs/mypy/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py in add_hydrogens_to_mol(mol)
     64   except ValueError as e:
     65     logging.warning("Unable to add hydrogens %s", e)
---> 66     raise MoleculeLoadException(e)
     67   finally:
     68     try:

MoleculeLoadException:

**Comment by VIGS25** [comment]
Can you put this on hold for a while?
Unfortunately, I'm right now very busy to look into pdbbind and fix all issues, but I will do it in a couple of weeks.

**Comment by fredrikszm** [comment]
@VIGS25 I completely understand that you are busy. Unfortunately, I need to use pdbbind for a project I'm doing for my internship that needs to be completed as soon as possible. Can you put me in touch with someone who has more time to fix these issues please?

**Comment by rbharath** [comment]
@fredrikszm Can you try upgrading to DeepChem 2.2? I think we fixed some of these loading errors in the latest DeepChem version

**Comment by fredrikszm** [comment]
@rbharath I have version 2.1 and I just tried upgrading to 2.2 but it is saying that it doesn't exist. Has 2.2 been officially released for conda install?
I have previously tried to install directly from source but it kept failing the tests and was not stable when I tried to use it. I was able to switch out some of the relevant files that were different (like pdbbind_datasets.py) between the source files and the 2.1 files.

**Comment by rbharath** [comment]
No unfortunately we don't have the conda build for 2.2 up yet. (@lilleswing is working on this now though). In the meanwhile, can you try installing from source? 2.2 simplifies the installation requirements so it should hopefully be easier

**Comment by fredrikszm** [comment]
@rbharath I was able to install from source this time, although there were some failed tests, I am able to run code so I think it is working. 
However, when I ran 
_PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="grid", reload=False)_
this time, it raised an exception and some of the pdb folders in v2015 are still empty.

here is the exception:

RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/fredrikszm/miniconda2/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/Users/fredrikszm/deepchem/deepchem/feat/base_classes.py", line 16, in _featurize_complex
    return featurizer._featurize_complex(mol_pdb_file, protein_pdb_file)
  File "/Users/fredrikszm/deepchem/deepchem/feat/rdkit_grid_featurizer.py", line 1243, in _featurize_complex
    protein_pdb_file, calc_charges=True, sanitize=self.sanitize)
  File "/Users/fredrikszm/deepchem/deepchem/utils/rdkit_util.py", line 128, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/Users/fredrikszm/deepchem/deepchem/utils/rdkit_util.py", line 52, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/Users/fredrikszm/miniconda2/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/Users/fredrikszm/miniconda2/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 901, in addHydrogens
    LocalEnergyMinimizer.minimize(context, 1.0, 50)
  File "/Users/fredrikszm/miniconda2/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/openmm.py", line 15160, in minimize
    return _openmm.LocalEnergyMinimizer_minimize(context, tolerance, maxIterations)
Exception: Particle coordinate is nan
"""

The above exception was the direct cause of the following exception:

Exception                                 Traceback (most recent call last)
<ipython-input-3-e15ab683a57f> in <module>()
----> 1 PDBBIND_tasks, (train_dataset, valid_dataset, test_dataset), transformers = dc.molnet.load_pdbbind(featurizer="grid", reload=False)

~/deepchem/deepchem/molnet/load_function/pdbbind_datasets.py in load_pdbbind(reload, data_dir, subset, load_binding_pocket, featurizer, split, split_seed, save_dir, save_timestamp)
    300   feat_t1 = time.time()
    301   features, failures = featurizer.featurize_complexes(ligand_files,
--> 302                                                       protein_files)
    303   feat_t2 = time.time()
    304   print("\nFeaturization finished, took %0.3f s." % (feat_t2 - feat_t1))

~/deepchem/deepchem/feat/base_classes.py in featurize_complexes(self, mol_files, protein_pdbs)
     51     failures = []
     52     for ind, result in enumerate(results):
---> 53       new_features = result.get()
     54       # Handle loading failures which return None
     55       if new_features is not None:

~/miniconda2/envs/deepchem/lib/python3.5/multiprocessing/pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

Exception: Particle coordinate is nan

**Comment by fredrikszm** [comment]
@rbharath would you also be able to give some additional info on how the load_pdbbind_grid dataset was featurized? The training dataset that results has 2052 features but when I use the rdkit grid featurizer on new data, I get 19968 features, so I am unable to make a prediction using the model trained on the pre-featurized dataset.
I was told to just use load_pdbbind for now, but since it is not working, perhaps you could shed some light on how to solve the original problem?

**Comment by rbharath** [comment]
So I think that the choice of arguments to `RdkitGridFeaturizer` controls how many features come out. Unfortunately, the grid featurizer classes have been refactored a couple times since that training dataset was originally computed, so it's not clear how the mismatch arose. I'm going to mark this one a bug since I think we should figure out how to set `RdkitGridFeaturizer` to produce the original fingerprints.

**Comment by fredrikszm** [comment]
@rbharath I believe these are the arguments that produce the original fingerprints:

grid_featurizer = dc.feat.RdkitGridFeaturizer(
    voxel_width=16.0, 
    feature_types=['ecfp', 'splif', 'hbond', 'salt_bridge'], 
    ecfp_power=9, 
    splif_power=9, 
    flatten=True)

This gives 2052 features which is the same as the number of features in the pre-featurized dataset. I found this when looking at the source code used to score in docking.
