### ISSUE TITLE
Installed Deepchem in CentOS machine, 

### ISSUE THREAD

**Issue by ZuoyiLi** [deepchem/deepchem#1580]
**Description:**

If you installed by source please give us the git hash as well
>> git log | head -n 1
--> commit 358a54eb53bbd625bc41bcd03d8ac928ecdb4415
- DeepChem Version:
- Platform: 
CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

I installed from source with only CPU support and I passed most of the nosetests. Traceback is at below. 

```
======================================================================
FAIL: Test training an OntologyModel for regression.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/home/zuoyi/deepchem/deepchem/models/tensorgraph/tests/test_ontology.py", line 41, in test_ontology_regressor
    assert np.all(pred_error < 0.01)
AssertionError

======================================================================
FAIL: Test A3C on an environment with a continous action space.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/home/zuoyi/deepchem/deepchem/rl/tests/test_a3c.py", line 297, in test_continuous
    assert distance < tolerance
AssertionError

======================================================================
FAIL: Test training a policy for the roulette environment.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/home/zuoyi/deepchem/deepchem/rl/tests/test_mcts.py", line 73, in test_roulette
    assert action_prob.argmax() == 37
AssertionError

----------------------------------------------------------------------
Ran 578 tests in 1311.696s

FAILED (SKIP=10, failures=3)

```
Then I ran a code using deepchem that was able to run on same environment on Ubuntu 18.04 machine. Then I received message as follows: 
```
Traceback (most recent call last):
  File "MP_FP_Param_Opt.py", line 8, in <module>
    import deepchem as dc
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/__init__.py", line 9, in <module>
    import deepchem.data
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/__init__.py", line 18, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 19, in <module>
    from deepchem.feat import UserDefinedFeaturizer
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/__init__.py", line 15, in <module>
    from deepchem.feat.graph_features import ConvMolFeaturizer
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/graph_features.py", line 5, in <module>
    from rdkit import Chem
  File "/srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/__init__.py", line 25, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: /lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /srv/home/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/../../../.././././libicuuc.so.58)
```
How should I fix the issue? Thanks!

**Comment by VIGS25** [comment]
The issue is not with DeepChem, but with `gcc` compilers and `rdkit`.
I couldn't find one for RDKit, but this is a more general issue, and some solutions are listed on https://github.com/Microsoft/CNTK/issues/2909
