### ISSUE TITLE
Store DiskDataset To Store Temporary Progress 

### ISSUE THREAD

**Issue by ZuoyiLi** [deepchem/deepchem#1581]
**Description:**

- Platform: Ubuntu 18.4

I was trying to run a time consuming program using deepchem package and the machine I use is owned by university and restarts everyday. I tried to store the process of my program by storing every list like objects in files using pickle module. However if the computer is turned off, there would be error message shown below:

```
2019-04-22 15:43:22.876958: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gradients_impl.py:112: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1376, in _enqueue_batch
    for feed_dict in generator:
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 742, in default_generator
    deterministic=deterministic)):
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 812, in iterate
    num_global_batches = math.ceil(dataset.get_shape()[0][0] / batch_size)
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 1321, in get_shape
    for shard_num, (X, y, w, ids) in enumerate(self.itershards()):
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 740, in iterate
    X = np.array(load_from_disk(os.path.join(dataset.data_dir, row['X'])))
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 223, in load_from_disk
    return joblib.load(filename)
  File "/u/z/u/zuoyi/anaconda3/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 570, in load
    with open(filename, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmppl14pwsa/shard-0-X.joblib'
```
My hypothesis is that the data sets are stored as DiskDataset objects and these disk files are cleaned when the machine restarts. So my question is how could I store the DiskDataset information in someway to use them later after a machine restart? Thanks!

**Comment by peastman** [comment]
According to the error message, you created your dataset inside `/tmp`.  That's a location for temporary files, so it's not surprising they're getting deleted.  How do you create the dataset?  You should generally put any non-temporary files inside your home directory.

**Comment by ZuoyiLi** [comment]
Hi, I generate the dataset from a loader, code is attached below:
```GC_featurizer = dc.feat.ConvMolFeaturizer()
    loader = dc.data.data_loader.CSVLoader( 
                                            tasks = [train_task], 
                                            smiles_field = smiles_field_name, 
                                            id_field = Id_name, 
                                            featurizer=GC_featurizer 
                                            )
    dataset = loader.featurize("/u/z/u/zuoyi/Desktop/GraphConvFolder/" + datafilename)
```
And here is how I attempted to store the dataset into files:
```
with open("test_set.txt", "wb") as fp0:
        pickle.dump(test_set, fp0)
        fp0.close()
```
I don't think I have ever used "tmp" folder explicitly. Does this mean I should not do work in folders under Desktop directory? Thank you!

**Comment by peastman** [comment]
In your call to `featurize()` you need to specify the `data_dir` argument to tell it where to store the dataset.  If you omit that, it creates a temporary directory.

Datasets aren't supposed to be pickled.  If you want to store one on disk, that's what DiskDataset is for.  You can then reinstantiate it by just writing

```python
dataset = DiskDataset(data_dir)
```

**Comment by ZuoyiLi** [comment]
Thank you so much! I think that is my issue. Really appreciate the help! I have one more question, for a dataset generated from "cv_data = splitter.k_fold_split(trainval_set, fold_k)", how should I store the new dataset, do I need to save it to some directory to maintain the split?

**Comment by peastman** [comment]
`k_fold_split()` has a `directories` argument.  It should be a list of length 2*k: `[train_dir1, cv_dir1, train_dir2, cv_dir2, ...]`.

**Comment by ZuoyiLi** [comment]
Thank! I think I will need to check the function descriptions first. I really appreciate the help.

**Comment by cjgalvin** [comment]
@peastman 
I am adding to this thread since my issue is related. I can start a new issue or feature request if more appropriate.
I have encountered a similar issue to the original poster, and I am curious why Deepchem is designed this way. 
I create a dataset using `dataset = CSVLoader.create_dataset('/path/to/dataset.csv')`. 
I save this dataset to disk using `dc.utils.save_to_disk(dataset, '/path/to/saved.joblib')`.

Importantly, I do not set a directory during the `create_dataset` call. As in the error above, after a computer restart, I cannot load using `dc.utils.load_from_disk('path/to/saved.joblib')`, and receive an error similar to the following:

> Exception has occurred: FileNotFoundError
> [Errno 2] No such file or directory: '/tmp/tmp3ko_huoy/shard-0-ids.npy'

I believe this is the same issue as the original poster.
Why doesn't the `save_to_disk` function also perform the same mechanics as setting a directory in the `create_dataset` function? It seems natural to expect `save_to_disk` to remove dependencies on tmp files. 

Or is that the expected behavior, and my error may be originating from a different issue?

Thank you,
Casey

**Comment by rbharath** [comment]
@cjgalvin This might be an issue with our docs not being clear unfortunately! `dc.utils.load_from_disk` is really an internal helper method that shouldn't be exposed in a public API. The way you'd want to save a loaded dataset is as follows

```
# Note that create_dataset is a method so we need to make the loader object to call it correctly
loader = dc.data.CSVLoader(...)
dataset = loader.create_dataset("/path/to/dataset.csv", data_dir="/path/to/save/featurized/dataset")
```
Now assume that you've restarted your computer. You can load the featurized dataset as follows
```
# Now to load dataset from disk
loaded_dataset = dc.data.DiskDataset("/path/to/save/featurized/dataset")
```

Basically neither `save_to_disk` nor `load_to_disk` should really be used by users. They're more utilities for developers developing new DeepChem internals. Hope that helps!

**Comment by rbharath** [comment]
Also, the example here https://deepchem.readthedocs.io/en/latest/api_reference/data.html#deepchem.data.CSVLoader might help provide some working code to look at
