### ISSUE TITLE
Error when loading DataSet: AttributeError: 'DataFrame' object has no attribute 'tolist'

### ISSUE THREAD

**Issue by sskaye** [deepchem/deepchem#1607]
Setup:
- MacOS 10.14.5
- Deepchem 2.1.0
- Installed in separate environment using conda

Problem Description:
When I try to load a csv file, following the instructions in the Dataset Creation tutorial (https://deepchem.io/docs/notebooks/dataset_preparation.html), I get the error: AttributeError: 'DataFrame' object has no attribute 'tolist' (Full error log below).

The input file is a basic csv file and I've confirmed I can load the file using deepchem.utils.save.load_from_disk and get the correct columns.

Any suggestions on what I'm doing wrong or how to fix it would be greatly appreciated.

Error log is below. Script and a truncated dataset (that gives the same error) are attached with txt extension added so they would upload.

(deepchem-env) stevens-imac:combinedMeltingPointData skaye$ python createDeepChemDataset.py 
/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d
- [2019-05-27 06:07] Confirm DeepChem can load the csv file
Columns of dataset: ['Melting Point (K)' 'SMILES' 'Name' 'Dataset']
Number of examples in dataset: 6
- [2019-05-27 06:07] Converting CSV to DeepChem dataset
Loading raw samples now.
shard_size: 8192
About to start loading CSV from ./testCSVMeltingPoint.csv
Loading shard 1 of size 8192.
Traceback (most recent call last):
  File "createDeepChemDataset.py", line 45, in <module>
    main()
  File "createDeepChemDataset.py", line 24, in main
    dataset = loader.featurize(inputFile)
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/deepchem/data/data_loader.py", line 234, in featurize
    shard_generator(), data_dir, self.tasks, verbose=self.verbose)
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/deepchem/data/datasets.py", line 557, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/deepchem/data/data_loader.py", line 213, in shard_generator
    X, valid_inds = self.featurize_shard(shard)
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/deepchem/data/data_loader.py", line 256, in featurize_shard
    return featurize_smiles_df(shard, self.featurizer, field=self.smiles_field)
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/deepchem/data/data_loader.py", line 63, in featurize_smiles_df
    sample_elems = df[field].tolist()
  File "/Users/skaye/miniconda3/envs/deepchem-env/lib/python2.7/site-packages/pandas/core/generic.py", line 3614, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tolist'

[createDeepChemDataset.py.txt](https://github.com/deepchem/deepchem/files/3223882/createDeepChemDataset.py.txt)
[testCSVMeltingPoint.csv.txt](https://github.com/deepchem/deepchem/files/3223883/testCSVMeltingPoint.csv.txt)

**Comment by sskaye** [comment]
Never mind. I specified the smiles_field as ['SMILES'] instead of 'SMILES' resulting in data_loader getting a DataFrame instead of a series. Once I fixed that, everything works fine.
