### ISSUE TITLE
Loading a trained model

### ISSUE THREAD

**Issue by jayliu99** [deepchem/deepchem#1617]
Hi,

I'm having trouble loading a trained model. It seems to be a problem with the version of sklearn.externals.joblib used for pickling not being the same version I call to unpickle?

- DeepChem Version:  2.2.1.dev74
- Platform:  Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-50-generic x86_64)

My code:
```
model_type = "KRR"
        sklearn_model = sklearn.kernel_ridge.KernelRidge(kernel=kernel)
        model_dir = os.path.join(current_dir, "pocket_%s_%s_%s_%s" % (split, subset, model_type, n_est))
        model = dc.models.SklearnModel(sklearn_model, model_dir=model_dir)
        model_trained = joblib.load(model_dir + "/model.joblib")
```

The error:
```
Traceback (most recent call last):
  File "pred.py", line 69, in <module>
    model_trained = joblib.load(model_dir + "/model.joblib")
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 578, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 508, in _unpickle
    obj = unpickler.load()
  File "/home/jliu99/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
KeyError: 1
```

**Comment by rbharath** [comment]
Closing this old issue as out of date. Please comment if this is still a bug you're seeing
