### ISSUE TITLE
TextCNNModel.predict_on_batch throws TypeError

### ISSUE THREAD

**Issue by RodrigoZepeda** [deepchem/deepchem#1619]
HI!
I am trying to use the `predict_on_batch` function inside the TextCNNModel to predict the solubility for new smiles; however, I get a `TypeError: object of type 'int' has no len()`. I have copied the code provided in [examples/delaney](https://github.com/deepchem/deepchem/blob/master/examples/delaney/delaney_textcnn.py) and the `predict_on_batch` example from [Deep Learning for the Life Sciences](https://books.google.com.mx/books?id=6OiRDwAAQBAJ&pg=PT71&lpg=PT71&dq=smiles+%3D+%5B%27COC(C)(C)CCCC(C)CC%3DCC(C)%3DCC(%3DO)OC(C)C%27,+%27CCOC(%3DO)CC%27,+%27CSc1nc(NC(C)C)nc(NC(C)C)n1%27,+%27CC(C%23C)N(C)C(%3DO)Nc1ccc(Cl)cc1%27,+%27Cc1cc2ccccc2cc1C%27%5D&source=bl&ots=SvNLWOy2mK&sig=ACfU3U0wMgyKc-J-kItzg-YMexOthstLQQ&hl=es-419&sa=X&ved=2ahUKEwiSmdrnrd_iAhUJna0KHRk0DCIQ6AEwAHoECAQQAQ#v=onepage&q=smiles%20%3D%20%5B'COC(C)(C)CCCC(C)CC%3DCC(C)%3DCC(%3DO)OC(C)C'%2C%20'CCOC(%3DO)CC'%2C%20'CSc1nc(NC(C)C)nc(NC(C)C)n1'%2C%20'CC(C%23C)N(C)C(%3DO)Nc1ccc(Cl)cc1'%2C%20'Cc1cc2ccccc2cc1C'%5D&f=false).

**How can I use the current model to predict solubility values for new smiles not in the original datasets?**

I am using:
- DeepChem Version: 2.1.0
- Platform: Ubuntu 18.04.2 LTS

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

#SECTION FROM 
#https://github.com/deepchem/deepchem/blob/master/examples/delaney/delaney_textcnn.py
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals

import numpy as np
np.random.seed(123)
import tensorflow as tf
tf.set_random_seed(123)
import deepchem as dc

# Load Delaney dataset
delaney_tasks, delaney_datasets, transformers = dc.molnet.load_delaney(
    featurizer='Raw', split='index')
train_dataset, valid_dataset, test_dataset = delaney_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.pearson_r2_score, np.mean)

char_dict, length = dc.models.TextCNNModel.build_char_dict(train_dataset)

# Batch size of models
batch_size = 64

model = dc.models.TextCNNModel(
    len(delaney_tasks),
    char_dict,
    seq_length=length,
    mode='regression',
    learning_rate=1e-3,
    batch_size=batch_size,
    use_queue=False)

# Fit trained model
model.fit(train_dataset, nb_epoch=10)

#Failed prediction as in book
from rdkit import Chem
smiles = ['COC(C)(C)CCCC(C)CC=CC(C)=CC(=O)OC(C)C',
          'CCOC(=O)CC',
          'CSc1nc(NC(C)C)nc(NC(C)C)n1',
          'CC(C#C)N(C)C(=O)Nc1ccc(Cl)cc1',
          'Cc1cc2ccccc2cc1C']
mols = [Chem.MolFromSmiles(s) for s in smiles]

featurizer = dc.feat.RawFeaturizer()   
x = featurizer.featurize(mols)

predicted_solubility = model.predict_on_batch(x)

```
The following error is thrown:

```
Traceback (most recent call last):

  File "<ipython-input-65-e33e2cfa9d4a>", line 1, in <module>
    predicted_solubility = model.predict_on_batch(x)

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 490, in predict_on_batch
    return self.predict_on_generator(generator, transformers, outputs)

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/text_cnn.py", line 275, in predict_on_generator
    generator, transformers=[], outputs=outputs)

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 472, in predict_on_generator
    return self._predict(generator, transformers, outputs, False)

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 420, in _predict
    for feed_dict in self._create_feed_dicts(generator, uncertainty):

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1071, in _create_feed_dicts
    for d in generator:

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/text_cnn.py", line 244, in default_generator
    smiles_seqs = [self.smiles_to_seq(smiles) for smiles in ids_b]

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/text_cnn.py", line 244, in <listcomp>
    smiles_seqs = [self.smiles_to_seq(smiles) for smiles in ids_b]

  File "/home/rod/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/text_cnn.py", line 251, in smiles_to_seq
    smiles_len = len(smiles)

TypeError: object of type 'int' has no len()
```

**Comment by rbharath** [comment]
Sorry for the lack of response here! This slipped through my inbox. I'll keep this issue open and take a look at it soon. I'm going to do a pass through the examples and book code soon to make sure everything runs correctly

**Comment by rbharath** [comment]
I'm running the `delaney_textcnn.py` example code on the latest DeepChem and it's running fine. I think this issue may have perhaps been fixed in the most recent versions of DeepChem. I'm going to go ahead and close this issue, but please feel free to re-open if you're still facing this issue.
