### ISSUE TITLE
ImportErrors in running any graph-base models

### ISSUE THREAD

**Issue by chf42** [deepchem/deepchem#1654]
Hi all,

I just installed the deepchem with conda environment, and tried to run some example codes. However, I came across the error "ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found"

<!-- To get the DeepChem version use the following commands:
>>> import deepchem
>>> deepchem.__version__
'2.1.1'

Detailed issues:
conda activate deepchem

Then, I went to tox21 folder 
(deepchem) $ **python tox21_graphcnn.py** 
Traceback (most recent call last):
  File "tox21_graphcnn.py", line 15, in <module>
    import deepchem as dc
  File "/home/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/__init__.py", line 9, in <module>
    import deepchem.data
  File "/home/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/data/__init__.py", line 18, in <module>
    from deepchem.data.data_loader import DataLoader
  File "/home/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 19, in <module>
    from deepchem.feat import UserDefinedFeaturizer
  File "/home/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/__init__.py", line 15, in <module>
    from deepchem.feat.graph_features import ConvMolFeaturizer
  File "/home/anaconda2/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/graph_features.py", line 5, in <module>
    from rdkit import Chem
  File "/home//anaconda2/envs/deepchem/lib/python3.5/site-packages/rdkit/__init__.py", line 2, in <module>
    from .rdBase import rdkitVersion as __version__
ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /home/anaconda2/envs/deepchem/lib/python3.5/site-packages/rdkit/rdBase.so)
```

Thanks,
Cheng

**Comment by peastman** [comment]
A search for that error message turns up a lot of reports in many places, all relating to conda in various ways.  Here are a few of the top ones:

https://github.com/ContinuumIO/anaconda-issues/issues/9090
https://github.com/BVLC/caffe/issues/4953
https://stackoverflow.com/questions/48453497/anaconda-libstdc-so-6-version-glibcxx-3-4-20-not-found

Some people seem to report it's caused by having `LD_LIBRARY_PATH` set incorrectly, and say you need to unset it.  Others report getting it to work by having conda install libgcc.  Others report success by *uninstalling* gcc.
