### ISSUE TITLE
AspuruGuzikAutoEncoder Error

### ISSUE THREAD

**Issue by hl2500** [deepchem/deepchem#1663]
Hello, I'm working with generative models in Chapter 9 of the book Deep Learning for Life Sciences. When I implemented this code block:

from deepchem.models.tensorgraph.optimizers import Adam, ExponentialDecay
from deepchem.models.tensorgraph.models.seqtoseq import AspuruGuzikAutoEncoder
model = AspuruGuzikAutoEncoder(tokens, max_length, model_dir='vae')
batches_per_epoch = len(train_smiles)/model.batch_size
learning_rate = ExponentialDecay(0.001, 0.95, batches_per_epoch)
model.set_optimizer(Adam(learning_rate=learning_rate))

There is an error AttributeError: 'AspuruGuzikAutoEncoder' object has no attribute 'set_optimizer'.

I'm not sure what happened...

**Comment by peastman** [comment]
Which version of DeepChem do you have installed?  The code in the book is written for 2.2.  If you're using the latest code from the repository, the signature has changed slightly.  You now pass the optimizer as an argument to the model's constructor:

```python
model = AspuruGuzikAutoEncoder(..., optimizer=Adam(learning_rate=learning_rate))
```

Or more simply, you can just pass the learning rate and it will use an Adam optimizer by default:

```python
model = AspuruGuzikAutoEncoder(..., learning_rate=learning_rate)
```

Once 2.3 is released (hopefully very soon), we'll update all the example code at https://github.com/deepchem/DeepLearningLifeSciences to work with it.

**Comment by hl2500** [comment]
Thank you for the reply! I think I'm using 2.1.1. Is there any way that I can update to a newer version?

**Comment by peastman** [comment]
Yes, you can upgrade by following the installation instructions at https://github.com/deepchem/deepchem.  Assuming you installed with conda, this will get you the right version:

```
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.2.0
```

**Comment by hl2500** [comment]
I used the conda environment, because this command didn't work. What should I do in this case? Thank you so much!

**Comment by peastman** [comment]
In what way does it not work?  What output do you get when you give that command?

**Comment by hl2500** [comment]
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
still not done yet

**Comment by hl2500** [comment]
Collecting package metadata (current_repodata.json): done
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: failed with current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed
Initial quick solve with frozen env failed.  Unfreezing env and trying again.
Solving environment: |

still not done yet..

**Comment by peastman** [comment]
I've occasionally seen messages like that.  I'm not sure exactly what they mean, but It seems to indicate conda is having to resolve all the dependencies by a very slow method rather than the normal faster method.  Just keep waiting.  It should eventually do something.

**Comment by hl2500** [comment]
It is finished, but there is an error.

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package libcxx conflicts for:
numpy-base -> blas==1.0=openblas -> openblas -> openblas-devel[version='0.3.3,0.3.6,>=0.2.20,<0.2.21.0a0',build=1] -> libopenblas[version='>=0.2.20,<0.2.21.0a0'] -> libgfortran[version='>=3.0.1,<4.0.0.a0'] -> libcxx[version='>=4.0.1']
testpath -> pathlib2 -> six -> python[version='2.7.*,3.4.*,3.5.*,3.6.*,>=2.7,<2.8.0a0,>=3.5,<3.6.0a0,>=3.6,<3.7.0a0'] -> sqlite[version='3.13.*,>=3.20.1,<4.0a0,>=3.24.0,<4.0a0,>=3.25.3,<4.0a0'] -> readline[version='6.2.*,7.0,>=7.0,<8.0a0'] -> ncurses[version='5.9.*,6.0.*,>=6.0,<7.0a0,>=6.1,<6.2.0a0'] -> libcxx[version='>=4.0.1']
numba -> numpy[version='1.15.*,>=1.12,<1.13.0a0,>=1.14.6,<2.0a0,>=1.15.4,<2.0a0,>=1.9.3,<2.0a0'] -> mkl_random -> numpy-base[version='>=1.0.2,<2.0a0'] -> blas==1.0=mkl -> openblas -> openblas-devel[version='0.3.3,0.3.6,>=0.2.20,<0.2.21.0a0',build=1] -> libopenblas==0.3.3=hdc02c5d_2 -> libgfortran[version='>=3.0.1,<4.0.0.a0,>=4.0.0,<5.0.0.a0'] -> llvm-openmp[version='>=8.0.0,>=8.0.1'] -> libcxx[version='>=4.0.1']

There are still much information like this following, I was not pasting them here...

**Comment by peastman** [comment]
Sometimes I think conda exists just to drive me crazy.  It does solve certain problems, but it also creates a lot of others in the process.  Let me see if I can figure out what's going on.

**Comment by hl2500** [comment]
Thank you! Is there any way that I can update the version I have in conda env? And how long does this training for generative model usually take? It has been running for 17 hrs, but still not done yet... It says:

WARNING:tensorflow:From /Users/haoxi/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
WARNING:tensorflow:From /Users/haoxi/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/checkpoint_management.py:624: remove_checkpoint (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to delete files with this prefix.

**Comment by peastman** [comment]
I think the problem is just that you're getting version conflicts with other libraries you have installed.  Create a clean environment and it should work:

```
conda create --name deepchem python=3.6
conda activate
conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=2.2.0
```

> And how long does this training for generative model usually take?

What hardware are you running on?  I don't recall how long that particular model took, but for large models it's critical to have a good GPU.  It often can be 10-50 times faster than training on your CPU.

**Comment by hl2500** [comment]
I'm running on Macbook Pro and using CPU version of deepchem.

**Comment by peastman** [comment]
Yeah, that's going to be very slow.  It's fine for simple exercises, but for doing real work you'll want something with a lot more computing power.

**Comment by hl2500** [comment]
Sorry, I tried the command above and install the deepchem in a conda env, but when I tried to import deepchem, it said:

ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'
ImportError: numpy.core.multiarray failed to import

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
SystemError: <class '_frozen_importlib._ModuleLockManager'> returned a result with an error set
ImportError: numpy.core._multiarray_umath failed to import
ImportError: numpy.core.umath failed to import
2019-08-23 17:27:07.624175: F tensorflow/python/lib/core/bfloat16.cc:675] Check failed: PyBfloat16_Type.tp_base != nullptr 
Abort trap: 6

**Comment by peastman** [comment]
Because, of course, Nothing Ever Works.  Sigh.

I just did a web search for "numpy core multiarray".  It turned up many pages of results, all about people encountering that error in many different programs.  Here's a huge thread of people getting it in TensorFlow: https://github.com/tensorflow/tensorflow/issues/559.

Nothing Ever Works.

Skimming through that thread, it looks like it's often caused by having one version of numpy installed with pip and another installed with conda.  `pip uninstall numpy` is suggested.  Possibly followed by `conda install numpy`.  Then there are people who say rebooting often fixes it.

Sigh.

**Comment by hl2500** [comment]
It seems that numpy cannot be recognized after I reinstalled. It says:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/haoxi/anaconda3/envs/deepchem2/lib/python3.6/site-packages/deepchem/__init__.py", line 9, in <module>
    import deepchem.data
  File "/Users/haoxi/anaconda3/envs/deepchem2/lib/python3.6/site-packages/deepchem/data/__init__.py", line 9, in <module>
    from deepchem.data.datasets import pad_features
  File "/Users/haoxi/anaconda3/envs/deepchem2/lib/python3.6/site-packages/deepchem/data/datasets.py", line 10, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by peastman** [comment]
Did you try `conda install numpy`?  If you type `conda list`, does it list numpy as being installed?

**Comment by hl2500** [comment]
Yes, and it's on the list.

numexpr                   2.7.0            py36h86efe34_0    conda-forge
numpy                     1.15.4           py36h6a91979_0  
olefile                   0.46                       py_0    conda-forge
openmm                    7.3.1           py36_cuda92_rc_2    omnia
openssl                   1.1.1c               h1de35cc_1

**Comment by peastman** [comment]
Alright, I'm very confused.  Maybe try deleting the environment and recreating it?  You could also look inside /Users/haoxi/anaconda3/envs/deepchem2/lib/python3.6/site-packages to see if numpy is really there or not.

**Comment by hl2500** [comment]
Thank you for the suggestion. I checked the path and did not find numpy... Then I deleted and recreated the env, but it still have the same problem. This time I tried conda uninstall numpy, followed by conda install numpy. Then I was able to import deepchem and I tried the first exercise:

>>> import deepchem as dc
>>> import numpy as np
>>> x = np.random.random((4,5))
>>> y = np.random.random((4,1))
>>> dataset = dc.data.NumpyDataset(x, y)

Then it says:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'deepchem' has no attribute 'data'

I also tried to load tox21 dataset, and it told me that deepchem has no attribute 'molnet'.
Do you have any idea about how these happened? Thank you!

**Comment by peastman** [comment]
Are you doing this from a directory that happens to contain a subdirectory called "deepchem"?  If so, Python will take it to mean that local directory instead of the installed module.

**Comment by hl2500** [comment]
I was doing it in the conda env which is created for deepchem 2.2. The directory is home directory and it contains the folder deepchem. It's weird that I cannot even import deepchem under any other directories... ModuleNotFoundError: No module named 'deepchem'. But I can do this with version 2.1 from any directories. I guess version 2.2 is not recognized by the system? Or the different versions of deepchem have conflicts?

**Comment by peastman** [comment]
Look in the `site-packages` folder for the environment.  If DeepChem is installed, there will be a directory there called `deepchem`.  If there isn't one, that means it isn't installed.
