### ISSUE TITLE
How to predict a dataset without the target?

### ISSUE THREAD

**Issue by kotori-y** [deepchem/deepchem#1695]
**How to predict a dataset without the target**

Dear All,

While we predict a dataset whose <code>y</code> is None, a unexpection happening
```
>>> model.predict(dataset)
Exception in thread Thread-1335:
Traceback (most recent call last):
  File "/public1/home/sc30142/.conda/envs/DeepChemProject/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/public1/home/sc30142/.conda/envs/DeepChemProject/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/public1/home/sc30142/.conda/envs/DeepChemProject/lib/python3.6/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 1382, in _enqueue_batch
    for feed_dict in generator:
  File "/public1/home/sc30142/.conda/envs/DeepChemProject/lib/python3.6/site-packages/deepchem/models/tensorgraph/models/graph_models.py", line 745, in default_generator
    d[self.labels[0]] = to_one_hot(y_b.flatten(), self.n_classes).reshape(
AttributeError: 'NoneType' object has no attribute 'flatten'
```

However, we could predict dataset with target:
```
>>> model.predict(test_set)
array([[[8.8882482e-01, 1.1117515e-01]],

       [[1.5574316e-03, 9.9844259e-01]],

       [[3.5134321e-01, 6.4865685e-01]],

       ...,

       [[7.4380159e-01, 2.5619838e-01]],

       [[3.6425345e-06, 9.9999630e-01]],

       [[1.9006871e-08, 1.0000000e+00]]], dtype=float32)
```

```
>>> dataset.X
array([<deepchem.feat.mol_graphs.ConvMol object at 0x2b98a2cd5898>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a2cd57f0>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a1ad2e80>,
       ...
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a2fdfc88>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a5566780>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a5567c18>],
      dtype=object)
>>> dataset.y
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/public1/home/sc30142/.conda/envs/DeepChemProject/lib/python3.6/site-packages/deepchem/data/datasets.py", line 1299, in y
    if len(y_b.shape) == 1:
AttributeError: 'NoneType' object has no attribute 'shape'
```

```
>>> test_set.X
array([<deepchem.feat.mol_graphs.ConvMol object at 0x2b98a20000b8>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a2000da0>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a40022e8>,
       ...
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a1b62048>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a1b629b0>,
       <deepchem.feat.mol_graphs.ConvMol object at 0x2b98a1b62da0]
>>> test_set.y
array([[1.],
       [0.],
       [0.],
       [1.],
       ...
       [0.],
       [1.],
       [0.]])
```
Thanks!

**Comment by peastman** [comment]
`y` should never be None.  Some of the constructors for creating datasets allow you to pass None, but then they automatically create an empty `y` array of the appropriate shape and set all the weights to 0: https://github.com/deepchem/deepchem/blob/master/deepchem/data/datasets.py#L318-L321.  Code that works with datasets expects there to always be a `y` array.

**Comment by kotori-y** [comment]
Thanks!
