### ISSUE TITLE
ValueError was found when running the tutorial GCN code

### ISSUE THREAD

**Issue by BonitoW** [deepchem/deepchem#1717]
**Description:**

Hi,
Now I am unable to run the example code inside the tutorial: Graph Convolutions For Tox21. The is the code:

```
#from __future__ import division
#from __future__ import print_function
#from __future__ import unicode_literals
import deepchem as dc
from deepchem.models.graph_models import GraphConvModel
#import tensorflow as tf
import numpy as np

tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21(featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = tox21_datasets

model = GraphConvModel(len(tox21_tasks), batch_size=50, mode='classification')
# Set nb_epoch=10 for better results.
model.fit(train_dataset, nb_epoch=1)
```
and it shows me this error
```
Traceback (most recent call last):
  File "/home/yilong/PycharmProjects/GCN1/gcn.py", line 12, in <module>
    model = GraphConvModel(len(tox21_tasks), batch_size=50, mode='classification')
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/graph_models.py", line 573, in __init__
    gc1 = layers.GraphConv(layer_size, activation_fn=tf.nn.relu)(gc1_in)
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 728, in __call__
    self.build(input_shapes)
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/layers.py", line 53, in build
    trainable=True) for k in range(num_deg)
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/layers.py", line 53, in <listcomp>
    trainable=True) for k in range(num_deg)
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/keras/engine/base_layer.py", line 565, in add_weight
    aggregation=aggregation)
  File "/home/yilong/anaconda3/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/training/checkpointable/base.py", line 509, in _add_variable_with_custom_getter
    "object.") % (name,))
ValueError: A variable named 'kernel' already exists in this Checkpointable, but Checkpointable._add_variable called to create another with that name. Variable names must be unique within a Checkpointable object.

```
If you know how o fix it, could you please help me?
DeepChem Version: 2.3.0

**Comment by peastman** [comment]
That code runs for me without any problems.  What version of TensorFlow are you using?  It should be 1.14.

**Comment by BonitoW** [comment]
> That code runs for me without any problems. What version of TensorFlow are you using? It should be 1.14.

You are right! It's the problem of different versions of packages.  I just reinstall these packages in the right version and then the code also runs for me. Thanks for your help!
