### ISSUE TITLE
runtime error with CSV input file of medium size

### ISSUE THREAD

**Issue by UnixJunkie** [deepchem/deepchem#1730]
**Description:**

- DeepChem Version: 2.1.1
- Platform: Darwin macpro 18.7.0 x86_64

While trying to load a training set with ~49000 molecules...

```
Loading raw samples now.
shard_size: 8192
About to start loading CSV from input_file.csv
Loading shard 1 of size 8192.
Traceback (most recent call last):
  File "/Users/john/bin/graph_conv_trvate.py", line 56, in <module>
    raw_train_set = loader.featurize(train_csv, shard_size=8192)
  File "/usr/local/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 239, in featurize
    shard_generator(), data_dir, self.tasks, verbose=self.verbose)
  File "/usr/local/lib/python3.7/site-packages/deepchem/data/datasets.py", line 557, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/usr/local/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 217, in shard_generator
    X, valid_inds = self.featurize_shard(shard)
  File "/usr/local/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 261, in featurize_shard
    return featurize_smiles_df(shard, self.featurizer, field=self.smiles_field)
  File "/usr/local/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 84, in featurize_smiles_df
    return np.squeeze(np.array(features), axis=1), valid_inds
  File "<__array_function__ internals>", line 6, in squeeze
  File "/usr/local/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 1438, in squeeze
    return squeeze(axis=axis)
numpy.AxisError: axis 1 is out of bounds for array of dimension 1
```

**Comment by rbharath** [comment]
@UnixJunkie Would it be possible to put together a simple failing script for me to look at? It looks like there's some type of shape mismatch but I'm not sure what this exact error is caused by

**Comment by UnixJunkie** [comment]
Don't bother, it was a stupid error on my side, sorry!
