### ISSUE TITLE
ModuleNotFoundError: No module named 'rdkit'

### ISSUE THREAD

**Issue by srinu844** [deepchem/deepchem#1819]
Hello

I installed deepchem using the below mentioned procedure.

```
git clone https://github.com/deepchem/deepchem.git # Clone deepchem source code from GitHub
cd deepchem
bash scripts/install_deepchem_conda.sh deepchem
source activate deepchem
yes | pip install tensorflow-gpu==1.6.0 # If you want GPU support
python setup.py install # Manual install
nosetests -a '!slow' -v deepchem --nologcapture # Run tests
```

This installed the packages required but not rdkit. so I installed rdkit using conda-forge. The following version was installed.

`rdkit 2020.03.1  py36h8e01224_1    conda-forge`

I also installed all the dependencies mentioned in requirements page.

After installing all the dependencies, I tried the example tox21 dataset. I activated the deepchem environment using conda activate deepchem. When I ran benchmark.py using the python 3.6, I am getting the following error:

```
(deepchem) DRSetty@SETE-CHEM-4 examples % python3 benchmark.py
Traceback (most recent call last):
File "benchmark.py", line 39, in 
import deepchem as dc
File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/init.py", line 6, in 
import deepchem.data
File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/data/init.py", line 14, in 
from deepchem.data.data_loader import DataLoader
File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/data/data_loader.py", line 17, in 
from deepchem.feat import UserDefinedFeaturizer
File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/feat/init.py", line 11, in 
from deepchem.feat.graph_features import ConvMolFeaturizer
File "/Users/DRSetty/miniconda3/lib/python3.7/site-packages/deepchem/feat/graph_features.py", line 2, in 
from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'
```

Can I get any help on this error.

**Comment by rbharath** [comment]
@srinu844 I responded in #1065 to your question there

**Comment by rbharath** [comment]
Closing this issue since according to  #1065 it looks to be resolved
