### ISSUE TITLE
Screening of new molecules causes error

### ISSUE THREAD

**Issue by DrrDom** [deepchem/deepchem#1868]
**Description:**

- DeepChem Version: 2.3.0
- Platform: Linux

This could be not a real issue but I could not figured out how to solve this.
According to sources `DataLoader` has a mandatory argument `tasks` which should be a list with names of activities. So, for test set prediction I have this column and I can specify it. But if I want to screen new compounds there is no activity columns in a file. I supposed that passing an empty list would work. But it does not.

So is it mandatory to pass some fake activity column to make prediction for new molecules or there is a more appropriate solution which I missed?

```
dataset_file = '1.smi'
featurizer_func = dc.feat.ConvMolFeaturizer()

# load test set - works
loader = dc.data.CSVLoader(tasks=['Activity'], smiles_field='smi', featurizer=featurizer_func)

# load set for screening - does not work
# loader = dc.data.CSVLoader(tasks=[], smiles_field='smi', featurizer=featurizer_func)

dataset = loader.featurize([dataset_file])
m_imb = dc.models.GraphConvModel(1, model_dir="modl")
m_imb.restore()
pred = m_imb.predict(dataset)
```
error message
```
Traceback (most recent call last):
  File "/home/pavel/python/deepchem-interp/pred.py", line 31, in <module>
    pred = m_imb.predict(dataset)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 711, in predict
    return self.predict_on_generator(generator, transformers, outputs)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 634, in predict_on_generator
    return self._predict(generator, transformers, outputs, False)
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/keras_model.py", line 544, in _predict
    for batch in generator:
  File "/home/pavel/anaconda3/envs/deepchem/lib/python3.6/site-packages/deepchem/models/graph_models.py", line 637, in default_generator
    y_b = to_one_hot(y_b.flatten(), self.n_classes).reshape(
AttributeError: 'NoneType' object has no attribute 'flatten'
```
I found that the `shard_generator` function from `data_loader` module assigns `None` value to `y` and `w` variables. `default_generator` from `GraphConvModel` class tries to make one-hot encoding of `y` which is actualy `None`.

**Comment by rbharath** [comment]
You're absolute right. This is an unfortunate edge that it's currently required to pass a fake activity field. I'm going to mark this as a fix for the next release and will fix this issue before we make the 2.4.0 cut in the next month or so.
