### ISSUE TITLE
WeaveFeaturizer's use_chirality option is broken

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1940]
Here's a simple failing test script:
```
import deepchem as dc
import numpy as np
from rdkit import Chem

smiles = ["C", "CC"]
featurizer = dc.feat.WeaveFeaturizer(use_chirality=True)
X = featurizer.featurize([Chem.MolFromSmiles(smile) for smile in smiles])
y = np.zeros(2)
dataset = dc.data.NumpyDataset(X, y)
model = dc.models.WeaveModel(
    1,
    batch_size=50,
    learning_rate=1e-3,
    mode='classification')
model.fit(dataset, nb_epoch=1)
```
The error given is
```
Traceback (most recent call last):
  File "chirality_test.py", line 15, in <module>
    model.fit(dataset, nb_epoch=1)
  File "/Users/bharath/Code/deepchem/deepchem/models/keras_model.py", line 276, in fit
    checkpoint_interval, restore, variables, loss, callbacks)
  File "/Users/bharath/Code/deepchem/deepchem/models/keras_model.py", line 344, in fit_generator
    for batch in generator:
  File "/Users/bharath/Code/deepchem/deepchem/models/graph_models.py", line 177, in default_generator
    (n_atoms * n_atoms, self.n_pair_feat)))
  File "<__array_function__ internals>", line 6, in reshape
  File "/Users/bharath/opt/anaconda3/envs/deepchem/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 301, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/Users/bharath/opt/anaconda3/envs/deepchem/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 61, in _wrapfunc
    return bound(*args, **kwds)
ValueError: cannot reshape array of size 18 into shape (1,14)
```
This same script works if we instead define
```
featurizer = dc.feat.WeaveFeaturizer()
```

**Comment by rbharath** [comment]
When fixing this, we should add some extra unit tests/docs to `WeaveFeaturizer` to avoid this error in the future.

**Comment by vsomnath** [comment]
Let me take a crack at this

**Comment by vsomnath** [comment]
The simple_fix is to just set `n_atom_feat=78` and `n_pair_feat=18`. But the `WeaveModel` should itself have a `use_chirality` option and change these sizes automatically.

**Comment by rbharath** [comment]
Good suggestion! I've been working with`WeaveModel` recently and found a few other issues. I'll put up an issue documenting all of them...
