### ISSUE TITLE
ImportError: cannot import name 'CloudPickler'

### ISSUE THREAD

**Issue by albertma-evotec** [deepchem/deepchem#1985]
**Description:**

I re-install deepchem by source last week and try to run membrane_permeability_graph_conv.py example in deepchem/examples/membrane_permeability
I got an ImportError: cannot import name 'CloudPickler'

Anyone came across this??

- DeepChem Version:  2.3.0
- Platform: ubuntu

```
(deepchem) [ama@uk-abi-smod61 membrane_permeability]$ python membrane_permeability_graph_conv.py
Traceback (most recent call last):
  File "membrane_permeability_graph_conv.py", line 12, in <module>
    import deepchem as dc
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/__init__.py", line 9, in <module>
    import deepchem.metalearning
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/metalearning/__init__.py", line 1, in <module>
    from deepchem.metalearning.maml import MAML, MetaLearner
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/metalearning/maml.py", line 3, in <module>
    from deepchem.models.optimizers import Adam, GradientDescent
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/models/__init__.py", line 11, in <module>
    from deepchem.models.fcnet import MultitaskRegressor
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/models/fcnet.py", line 13, in <module>
    from deepchem.models.layers import SwitchedDropout
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/deepchem-2.3.0-py3.6.egg/deepchem/models/layers.py", line 3, in <module>
    import tensorflow_probability as tfp
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/__init__.py", line 76, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/python/__init__.py", line 23, in <module>
    from tensorflow_probability.python import distributions
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/python/distributions/__init__.py", line 88, in <module>
    from tensorflow_probability.python.distributions.pixel_cnn import PixelCNN
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/python/distributions/pixel_cnn.py", line 37, in <module>
    from tensorflow_probability.python.layers import weight_norm
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/python/layers/__init__.py", line 31, in <module>
    from tensorflow_probability.python.layers.distribution_layer import CategoricalMixtureOfOneHotCategorical
  File "/home/UK/ama/.conda/envs/deepchem/lib/python3.6/site-packages/tensorflow_probability/python/layers/distribution_layer.py", line 28, in <module>
    from cloudpickle.cloudpickle import CloudPickler
ImportError: cannot import name 'CloudPickler'

```

**Comment by ncfrey** [comment]
Hi @albertma-evotec, this is an issue with a recent update to the `cloudpickle` library. I recommend either installing directly from DeepChem HEAD or the new nightly package, where this issue is fixed:
```
pip install tensorflow
pip install deepchem-nightly
```

**Comment by nd-02110114** [comment]
@albertma-evotec 

Maybe, I think the following command may work well. 
Currently, we don't recommend  the `deepchem-nightly` package

```
pip uninstall deepchem-nightly deepchem
pip install --pre deepchem
```

O, if you want to use tensorflow_probability, please reinstall `cloudpickle=1.4.1`
```
pip install cloudpickle==1.4.1
```
