### ISSUE TITLE
Error during model evaluation with dataset with empty list of task names

### ISSUE THREAD

**Issue by chstem** [deepchem/deepchem#2079]
During evaluation of a model with some metric and using a dataset with empty `dataset.task` the following error occurs:

```python
>>> metric = dc.metrics.Metric(dc.metrics.rms_score, np.mean)
>>> valid_score = model.evaluate(dataset, [metric])['mean-rms_score']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/deepchem/deepchem/models/models.py", line 248, in evaluate
    n_classes=n_classes)
  File "~/deepchem/deepchem/utils/evaluate.py", line 306, in compute_model_performance
    use_sample_weights=use_sample_weights)
  File "~/deepchem/deepchem/metrics/__init__.py", line 772, in compute_metric
    y_true, mode=self.mode, n_tasks=n_tasks, n_classes=n_classes)
  File "~/deepchem/deepchem/metrics/__init__.py", line 169, in normalize_labels_shape
    "Shape of input doesn't match expected n_tasks=%d" % n_tasks)
ValueError: Shape of input doesn't match expected n_tasks=0
```

A possible workaround is to assign `dataset.task` some list of appropriate length.  This also means the error can be reproduced from a standard molnet set by assigning `dataset.task` to an empty list:

```python
import deepchem as dc
import numpy as np
from deepchem.models.graph_models import GraphConvModel

qm9_tasks, qm9_datasets, transformers = dc.molnet.load_qm9(featurizer='GraphConv')
train_dataset, valid_dataset, test_dataset = qm9_datasets
n_tasks = len(qm9_tasks)

test_dataset.tasks = []

metric = dc.metrics.Metric(dc.metrics.rms_score, np.mean)
model = GraphConvModel(n_tasks, batch_size=100, mode='regression')
loss = model.fit(train_dataset, nb_epoch=1)
test_score = model.evaluate(test_dataset, [metric])['mean-rms_score']
```

This error occurs since b399a20d.

On a related note: The different dataset classes (`NumpyDataset`, `DiskDataset`) do not have a consistent interfaces to handle the task names. 
1. There is `dataset.get_task_names()` but no `dataset.set_task_names()`.
2. If a new dataset is created without explicity setting the task names, then `NumpyDataset.get_task_names()` automatically returns an array with indices of appropriate length. `DiskDataset.get_task_names()` on the other hand returns an empty list. (Which is how I found this issue.)

I suggest to add a method `dataset.set_task_names()` and some way to pass the task names during construction of a new dataset.

**Comment by peastman** [comment]
Datasets are generally immutable once created, so a `set_task_names()` method wouldn't be appropriate.  I agree we should make the different classes more consistent.  Currently:

- NumpyDataset and ImageDataset do not allow you to specify task names.  They hardcode that the task names are integers.
- DiskDataset allows you to specify task names.  If you don't, it returns an empty list.

How about if all of them let you specify a list of task names, and automatically use integers if you don't?

> This also means the error can be reproduced from a standard molnet set by assigning dataset.task to an empty list

Don't do that!  Like I said, Datasets are supposed to be immutable, so if you start modifying their internal fields Bad Things could happen.  We should probably discourage this by renaming the field to `_tasks` and making `tasks` into a property.

**Comment by chstem** [comment]
> DiskDataset allows you to specify task names. If you don't, it returns an empty list.

Ah, here is the problem: I missed that because NumpyDataset does not and I assumed all datasets work similar.

> We should probably discourage this by renaming the field to _tasks and making tasks into a property.

Yes, absolutely! Although just renaming it might be fine as well.

**Comment by peastman** [comment]
> Although just renaming it might be fine as well.

Agreed!  There's already `get_task_names()` after all.
