### ISSUE TITLE
FAQ needed

### ISSUE THREAD

**Issue by pnovick** [deepchem/deepchem#21]
A few common issues, which maybe be suitable for an FAQ.  Running on AWS Linux, moving data from Mac OSX 10.10.2

1. Need Python 2, not Python 3

2. remember to re- source .bashrc after install
```
[ec2-user@ip-172-31-31-11 ~]$ conda install -c omnia openbabel
-bash: conda: command not found
[ec2-user@ip-172-31-31-11 ~]$ source ~/.bashrc
[ec2-user@ip-172-31-31-11 ~]$ conda install -c omnia openbabel
```

3. When exporting as CSV from OSX Excel, need to use 'Windows Comma Separated', not 'Comma Separated Values.'  The former adds non-standard newlines (^M) rather than (^N).
```
[ec2-user@ip-172-31-31-11 stanfordCollab]$ python -m deep_chem.scripts.modeler featurize --input-file ../datasets/All_IDOTDO_dataset.csv --input-type csv --fields smiles id activity --field-types string string float --prediction-endpoint activity --smiles-endpoint smiles --id-endpoint smiles --name trainingWheels --out ./ 
Traceback (most recent call last):
  File "/home/ec2-user/anaconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/ec2-user/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ec2-user/deep-learning/deep_chem/scripts/modeler.py", line 278, in <module>
    main()
  File "/home/ec2-user/deep-learning/deep_chem/scripts/modeler.py", line 275, in main
    args.func(args)
  File "/home/ec2-user/deep-learning/deep_chem/scripts/modeler.py", line 187, in featurize_input
    args.threshold, args.delimiter)
  File "/home/ec2-user/deep-learning/deep_chem/utils/featurize.py", line 223, in extract_data
    for row_index, raw_row in enumerate(get_rows(input_file, input_type, delimiter)):
  File "/home/ec2-user/deep-learning/deep_chem/utils/featurize.py", line 104, in get_rows
    return [row for row in reader]
_csv.Error: new-line character seen in unquoted field - do you need to open the file in universal-newline mode?
```

**Comment by rbharath** [comment]
@pnovick Going to close this since the `deepchem` workflow has changed dramatically from this earlier version. Should still add an FAQ, but will need to wait to see what frequent questions arise in new API.
