### ISSUE TITLE
Tracking Errors in Examples

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#2168]
Let's use this thread to track known errors in our examples and coordinate fixes

**Comment by micimize** [comment]
Here are the results of example runs I tried earlier today (`adme`, `bace`, `toxcast`, `sider`, `clintox`):

<details>

<summary><code>conda run python examples/adme/run_benchmarks.py</code> 404s on the s3 csvs </summary>

```bash
--2020-09-14 14:28:30--  https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_logd.csv
Resolving s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)... 52.219.112.120
Connecting to s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)|52.219.112.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-14 14:28:31 ERROR 404: Not Found.

--2020-09-14 14:28:31--  https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_hppb.csv
Resolving s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)... 52.219.112.120
Connecting to s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)|52.219.112.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-14 14:28:31 ERROR 404: Not Found.

--2020-09-14 14:28:31--  https://s3-us-west-1.amazonaws.com/deep-crystal-california/az_clearance.csv
Resolving s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)... 52.219.112.120
Connecting to s3-us-west-1.amazonaws.com (s3-us-west-1.amazonaws.com)|52.219.112.120|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-09-14 14:28:31 ERROR 404: Not Found.
```

</details>

<details>

<summary><code>conda run python examples/bace/bace_rf.py</code> fails on classification with "Only one class present in y_true. ROC AUC score is not defined in that case." </summary>


This is after adding back a `SpecifiedSplitter`, and fixing hyperparam search with `rf_model_builder(model_dir, **model_params)` and `GridHyperparamOpt`

```python
ERROR conda.cli.main_run:execute(31): Subprocess for 'conda run ['python', 'examples/bace/bace_rf.py']' command failed.  (See above for error)
Classifier RF 20-80:
--------------------------------
Number of compounds in train set
204
Number of compounds in validation set
1273
Number of compounds in test set
45
Number of compounds in crystal set
25
RF Train set scores: {'accuracy_score': 0.9901960784313726, 'matthews_corrcoef': 0.9805806756909202, 'recall_score': 1.0, 'roc_auc_score': 0.9998077662437524}
RF Valid set scores: {'accuracy_score': 0.6842105263157895, 'matthews_corrcoef': 0.44740320920029036, 'recall_score': 0.9147005444646098, 'roc_auc_score': 0.7881772501269412}
RF Test set: {'accuracy_score': 0.4888888888888889, 'matthews_corrcoef': 0.14101901870444156, 'recall_score': 0.4772727272727273, 'roc_auc_score': 0.7045454545454546}

smiles_field is deprecated and will be removed in a future version of DeepChem.Use feature_field instead.
/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/data/data_loader.py:162: FutureWarning: featurize() is deprecated and has been renamed to create_dataset().featurize() will be removed in DeepChem 3.0
  "featurize() will be removed in DeepChem 3.0", FutureWarning)
/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/trans/transformers.py:538: RuntimeWarning: invalid value encountered in true_divide
  X = np.nan_to_num((X - self.X_means) / self.X_stds)
/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/trans/transformers.py:538: RuntimeWarning: divide by zero encountered in true_divide
  X = np.nan_to_num((X - self.X_means) / self.X_stds)
csv_out is deprecated as an argument and will be removed in a future version of DeepChem.Output is not written to CSV; manually write output instead.
stats_out is deprecated as an argument and will be removed in a future version of DeepChem.Stats output is not written; please manually write output instead
csv_out is deprecated as an argument and will be removed in a future version of DeepChem.Output is not written to CSV; manually write output instead.
stats_out is deprecated as an argument and will be removed in a future version of DeepChem.Stats output is not written; please manually write output instead
csv_out is deprecated as an argument and will be removed in a future version of DeepChem.Output is not written to CSV; manually write output instead.
stats_out is deprecated as an argument and will be removed in a future version of DeepChem.Stats output is not written; please manually write output instead
csv_out is deprecated as an argument and will be removed in a future version of DeepChem.Output is not written to CSV; manually write output instead.
stats_out is deprecated as an argument and will be removed in a future version of DeepChem.Stats output is not written; please manually write output instead
/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/metrics/_classification.py:846: RuntimeWarning: invalid value encountered in double_scalars
  mcc = cov_ytyp / np.sqrt(cov_ytyt * cov_ypyp)
Traceback (most recent call last):
  File "examples/bace/bace_rf.py", line 103, in <module>
    bace_rf_model(mode="classification", split="20-80")
  File "examples/bace/bace_rf.py", line 95, in bace_rf_model
    all_metrics, csv_out=csv_out, stats_out=stats_out
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/utils/evaluate.py", line 316, in compute_model_performance
    use_sample_weights=use_sample_weights)
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/metrics/metric.py", line 664, in compute_metric
    **kwargs)
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/metrics/metric.py", line 738, in compute_singletask_metric
    metric_value = self.metric(y_true, y_pred, **kwargs)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/utils/validation.py", line 72, in inner_f
    return f(**kwargs)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 398, in roc_auc_score
    sample_weight=sample_weight)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/metrics/_base.py", line 120, in _average_binary_score
    sample_weight=score_weight)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/metrics/_ranking.py", line 223, in _binary_roc_auc_score
    raise ValueError("Only one class present in y_true. ROC AUC score "
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.
```

</details>

<details>

<summary><code>conda run python examples/toxcast/toxcast_rf.py</code> fails with Unknown label type: 'unknown' </summary>

The first time I ran it it printed these `SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'`, now it just fails

```python
ERROR conda.cli.main_run:execute(31): Subprocess for 'conda run ['python', 'examples/toxcast/toxcast_rf.py']' command failed.  (See above for error)
smiles_field is deprecated and will be removed in a future version of DeepChem.Use feature_field instead.
[15:20:51] Explicit valence for atom # 0 F, 2, is greater than permitted
/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/data/data_loader.py:162: FutureWarning: featurize() is deprecated and has been renamed to create_dataset().featurize() will be removed in DeepChem 3.0
  "featurize() will be removed in DeepChem 3.0", FutureWarning)
Failed to featurize datapoint %d. Appending empty array
[15:20:51] Explicit valence for atom # 2 Cl, 2, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[15:20:51] Explicit valence for atom # 0 Cl, 2, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[15:20:52] WARNING: not removing hydrogen atom without neighbors
[15:20:52] Explicit valence for atom # 3 Si, 8, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[15:20:52] Explicit valence for atom # 3 Si, 8, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[15:20:52] Explicit valence for atom # 7 Mg, 4, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[15:20:54] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:54] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:55] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:55] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:55] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:55] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:56] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:56] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:56] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:56] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:57] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:57] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:58] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:58] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:58] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:58] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:58] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:58] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
[15:20:58] SMILES Parse Error: syntax error while parsing: FAIL
[15:20:58] SMILES Parse Error: Failed parsing SMILES 'FAIL' for input: 'FAIL'
Failed to featurize datapoint %d. Appending empty array
/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/numpy/core/_asarray.py:83: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  return array(a, dtype, copy=False, order=order)
Traceback (most recent call last):
  File "examples/toxcast/toxcast_rf.py", line 28, in <module>
    model.fit(train_dataset)
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/models/multitask.py", line 108, in fit
    task_model.fit(task_datasets[ind], **kwargs)
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/models/sklearn_models/sklearn_model.py", line 85, in fit
    self.model_instance.fit(X, y, w)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 330, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/ensemble/_forest.py", line 558, in _validate_y_class_weight
    check_classification_targets(y)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/sklearn/utils/multiclass.py", line 172, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'unknown'
```

</details>


<details>

<summary><code>conda run python examples/sider/sider_rf.py</code> runs properly after fixing <code>dc.utils.save.load_from_disk</code> </summary>

```diff
- dataset = dc.utils.save.load_from_disk(dataset_file)
+ dataset = dc.utils.load_from_disk(dataset_file)
```
with 
```python
Train scores
{'mean-roc_auc_score': 0.9999828325995789}
Validation scores
{'mean-roc_auc_score': 0.6678139839206264}
```
</details>


<details>
<summary>
And then both clintox scripts appear to run fine
</summary>

There were a few warnings and failures in the logs but I'm guessing that's normal:
```
conda run python examples/clintox/clintox_graph_conv.py
Evaluating model
Train scores
{'mean-roc_auc_score': 0.9678033621683504}
Validation scores
{'mean-roc_auc_score': 0.8812402252111355}
...
[19:25:01] Explicit valence for atom # 10 N, 4, is greater than permitted
Failed to featurize datapoint %d. Appending empty array
[19:25:02] Can't kekulize mol.  Unkekulized atoms: 4
```

</details>

**Comment by micimize** [comment]
<details>
<summary><code>conda run python examples/hiv/hiv_irv.py</code> fails in the <code>IRVTransformer</code> seemingly due to passing <code>tf.nn.top_k</code> a similarity of type <code>np.ndarray</code> instead of an <code>EagerTensor</code>. This would mean there might be an actual bug in the transformer

</summary>

```python
transformer = dc.trans.IRVTransformer(10, len(hiv_tasks), train_dataset)
train_dataset = transformer.transform(train_dataset)
```

```
2020-09-19 08:59:55.846525: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-09-19 08:59:55.868532: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc0fe11df40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-09-19 08:59:55.868544: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 11305, in top_kv2
    tld.op_callbacks, input, k, "sorted", sorted)
tensorflow.python.eager.core._FallbackException: This function does not handle the case of the path where all inputs are not already EagerTensors.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "examples/hiv/hiv_irv.py", line 23, in <module>
    train_dataset = transformer.transform(train_dataset)
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/trans/transformers.py", line 1585, in transform
    dataset.X[count * 5000:min((count + 1) * 5000, X_length), :]))
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/trans/transformers.py", line 1525, in X_transform
    X_target2.append(self.realize(similarity, self.y[:, i], self.w[:, i]))
  File "/Users/mjr/Documents/code/libraries/ml/deepchem/deepchem/trans/transformers.py", line 1476, in realize
    value, indice = tf.nn.top_k(similarity, k=self.K + 1, sorted=True)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py", line 4494, in top_k
    return gen_nn_ops.top_kv2(input, k=k, sorted=sorted, name=name)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 11311, in top_kv2
    input, k, sorted=sorted, name=name, ctx=_ctx)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 11339, in top_kv2_eager_fallback
    _attr_T, (input,) = _execute.args_to_matching_eager([input], ctx)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 263, in args_to_matching_eager
    t, dtype, preferred_dtype=default_dtype, ctx=ctx))
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/framework/ops.py", line 1341, in convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/framework/tensor_conversion_registry.py", line 52, in _default_conversion_function
    return constant_op.constant(value, dtype, name=name)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 262, in constant
    allow_broadcast=True)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 270, in _constant_impl
    t = convert_to_eager_tensor(value, ctx, dtype)
  File "/usr/local/anaconda3/envs/deepchem/lib/python3.7/site-packages/tensorflow/python/framework/constant_op.py", line 96, in convert_to_eager_tensor
    return ops.EagerTensor(value, ctx.device_name, dtype)
ValueError: Failed to convert a NumPy array to a Tensor (Unsupported object type float).
```

</details>

**Comment by rbharath** [comment]
@micimize Awesome, thanks for getting these failures documented here! I wouldn't be surprised with a bug in `IRVTransformer`. We need to add more stringent tests for `IRVTransformer`

**Comment by rbharath** [comment]
The examples are mostly outdated and not maintained (the doctests/tutorials have taken over this role). Closing this old issue
