### ISSUE TITLE
Omnia Keras is Outdated

### ISSUE THREAD

**Issue by altaetran** [deepchem/deepchem#224]
Hi, 

I just wanted to point out that the omnia keras version is outdated, as such, it does not contain the Input layer from Keras.layers, which means the Keras must be a much older version that what is currently in use. Is there any way to use a more recent keras? Thanks!

**Comment by rbharath** [comment]
@altaetran I'd recommend just going ahead and using the newest Keras. This is an open issue #169 long due for debugging. Could you raise issues for any bugs you find?

**Comment by altaetran** [comment]
I obtain the following errors in the nosetests

> ======================================================================
ERROR: Test that keras models can overfit simple classification datasets.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_overfit.py", line 292, in test_keras_classification_overfit
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'mul_2:0' shape=() dtype=float32> of <tf.Tensor 'mul_2:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("mul_2:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test keras multitask overfits tiny data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_overfit.py", line 617, in test_keras_multitask_classification_overfit
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'add_27:0' shape=() dtype=float32> of <tf.Tensor 'add_27:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("add_27:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test keras multitask overfits tiny data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_overfit.py", line 763, in test_keras_multitask_regression_overfit
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'add_70:0' shape=() dtype=float32> of <tf.Tensor 'add_70:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("add_70:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test that keras models can overfit simple regression datasets.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_overfit.py", line 192, in test_keras_regression_overfit
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'mul_146:0' shape=() dtype=float32> of <tf.Tensor 'mul_146:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("mul_146:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test keras models can overfit 0/1 datasets with few actives.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_overfit.py", line 342, in test_keras_skewed_classification_overfit
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'mul_158:0' shape=() dtype=float32> of <tf.Tensor 'mul_158:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("mul_158:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test that trained keras models can be reloaded correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/tests/test_reload.py", line 109, in test_keras_reload
    model.fit(dataset)
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch))
  File "/home/stanford/pande/users/hraut/src/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/stanford/pande/users/hraut/programs/anaconda2/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 975, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 584, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/global/software/extras/tensorflow/0.9/tensorflow/python/client/session.py", line 543, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'mul_170:0' shape=() dtype=float32> of <tf.Tensor 'mul_170:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("mul_170:0", shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
compute_feature_statistics
True
Starting epoch 1

--------------------- >> end captured stdout << ----------------------

----------------------------------------------------------------------
Ran 134 tests in 744.851s

FAILED (errors=8)

> 

Is there any concern for this?

**Comment by rbharath** [comment]
@altaetran This is a concern, so I'll make this a debugging priority. I'll try to hit this today or tomorrow if possible.

In the meanwhile, I'd recommend continuing ahead with Keras head on your use-case. If more issues come up, please report them on this thread.

**Comment by altaetran** [comment]
Ok thanks!

**Comment by rbharath** [comment]
@altaetran Could you give me more details about your enviornment setup? I'm having trouble duplicating these precise errors on my development setup. Travis CI does see these same errors though #227.

**Comment by altaetran** [comment]
I just installed omnia keras as in the instructions. Then, I tried to use keras, but realized I couldn't import Input. I made a new environment for the installation process.

**Comment by rbharath** [comment]
@altaetran Did you do `pip install keras` after realizing `Input` wasn't present?

**Comment by rbharath** [comment]
(For reference, this discussion was also continued in #227)

@altaetran I think I've hunted down the source of the bugs. When I run

```nosetests -v deepchem --nologcapture```

I get the same output you report. For example, here's the failing output from one of the keras tests:
```
======================================================================
ERROR: Test that trained keras models can be reloaded correctly.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/scratch/users/rbharath/deepchem/deepchem/models/tests/test_reload.py", line 116, in test_keras_reload
    model.fit(dataset)
  File "/scratch/users/rbharath/deepchem/deepchem/models/__init__.py", line 130, in fit
    losses.append(self.fit_on_batch(X_batch, y_batch, w_batch)) 
  File "/scratch/users/rbharath/deepchem/deepchem/models/keras_models/fcnet.py", line 111, in fit_on_batch
    loss = self.raw_model.train_on_batch(data, sample_weight=sample_weight)
  File "/home/rbharath/anaconda/envs/deepchem/lib/python2.7/site-packages/keras/legacy/models.py", line 505, in train_on_batch
    class_weight=class_weight)
  File "/home/rbharath/anaconda/envs/deepchem/lib/python2.7/site-packages/keras/engine/training.py", line 1219, in train_on_batch
    outputs = self.train_function(ins)
  File "/home/rbharath/anaconda/envs/deepchem/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 971, in __call__
    updated = session.run(self.outputs + [self.updates_op], feed_dict=feed_dict)
  File "/share/sw/free/tensorflow/0.8.0/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/share/sw/free/tensorflow/0.8.0/tensorflow/python/client/session.py", line 523, in _run
    processed_fetches = self._process_fetches(fetches)
  File "/share/sw/free/tensorflow/0.8.0/tensorflow/python/client/session.py", line 496, in _process_fetches
    'Tensor. (%s)' % (subfetch, fetch, str(e)))
ValueError: Fetch argument <tf.Tensor 'mul_170:0' shape=() dtype=float32> of <tf.Tensor 'mul_170:0' shape=() dtype=float32> cannot be interpreted as a Tensor. (Tensor Tensor("mul_170:0",
 shape=(), dtype=float32) is not an element of this graph.)
-------------------- >> begin captured stdout << ---------------------
```
But, when I run this same test manually with the command
```
nosetests -v deepchem.models.tests.test_reload:TestReloadAPI.test_keras_reload --nologcapture
```
The test passes!
```
Using TensorFlow backend.
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so.4 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so.7.5 locally
Test that trained keras models can be reloaded correctly. ... I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:
name: Tesla K20Xm
major: 3 minor: 5 memoryClockRate (GHz) 0.784
pciBusID 0000:08:00.0
Total memory: 6.00GiB
Free memory: 5.92GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K20Xm, pci bus id: 0000:08:00.0)
ok

----------------------------------------------------------------------
Ran 1 test in 2.469s

OK
```
I think the issue has to do with `tensorflow` cleanup. Somehow, running multiple `keras` models in the same process (where `tensorflow` is used as the backend) seems to pollute the global `tensorflow` graph. I'm going to do a little more debugging, but I think these errors are essentially harmless and can be ignored.

**Comment by rbharath** [comment]
@altaetran #227 should have resolved this issue. Going to go ahead and close. Please re-open if you find future issues.
