### ISSUE TITLE
Errors about test_weave_fit_simple_infinity_distance 

### ISSUE THREAD

**Issue by nd-02110114** [deepchem/deepchem#2266]
Travis log: https://travis-ci.org/github/deepchem/deepchem/jobs/740320951
`test_weave_fit_simple_infinity_distance` is always failed in only Linux. We should fix this issue.

```
___________________ test_weave_fit_simple_infinity_distance ____________________
    def test_weave_fit_simple_infinity_distance():
      featurizer = dc.feat.WeaveFeaturizer(max_pair_distance=None)
      X = featurizer(["C", "CCC"])
      y = np.array([0, 1.])
      dataset = dc.data.NumpyDataset(X, y)
    
      batch_size = 20
      model = WeaveModel(
          1,
          batch_size=batch_size,
          mode='classification',
          fully_connected_layer_sizes=[2000, 1000],
          batch_normalize=True,
          batch_normalize_kwargs={
              "fused": False,
              "trainable": True,
              "renorm": True
          },
          learning_rage=0.0005)
      model.fit(dataset, nb_epoch=200)
      transformers = []
      metric = dc.metrics.Metric(
          dc.metrics.roc_auc_score, np.mean, mode="classification")
>     scores = model.evaluate(dataset, [metric], transformers)
deepchem/models/tests/test_weave_models.py:186: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
deepchem/models/models.py:219: in evaluate
    n_classes=n_classes)
deepchem/utils/evaluate.py:316: in compute_model_performance
    use_sample_weights=use_sample_weights)
deepchem/metrics/metric.py:664: in compute_metric
    **kwargs)
deepchem/metrics/metric.py:738: in compute_singletask_metric
    metric_value = self.metric(y_true, y_pred, **kwargs)
../../../miniconda/envs/deepchem/lib/python3.7/site-packages/sklearn/utils/validation.py:72: in inner_f
    return f(**kwargs)
../../../miniconda/envs/deepchem/lib/python3.7/site-packages/sklearn/metrics/_ranking.py:372: in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
../../../miniconda/envs/deepchem/lib/python3.7/site-packages/sklearn/utils/validation.py:72: in inner_f
    return f(**kwargs)
../../../miniconda/envs/deepchem/lib/python3.7/site-packages/sklearn/utils/validation.py:645: in check_array
    allow_nan=force_all_finite == 'allow-nan')
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
X = array([[nan, nan],
       [nan, nan]], dtype=float32), allow_nan = False
msg_dtype = None
    def _assert_all_finite(X, allow_nan=False, msg_dtype=None):
        """Like assert_all_finite, but only for ndarray."""
        # validation is also imported in extmath
        from .extmath import _safe_accumulator_op
    
        if _get_config()['assume_finite']:
            return
        X = np.asanyarray(X)
        # First try an O(n) time, O(1) space solution for the common case that
        # everything is finite; fall back to O(n) space np.isfinite to prevent
        # false positives from overflow in sum method. The sum is also calculated
        # safely to reduce dtype induced overflows.
        is_float = X.dtype.kind in 'fc'
        if is_float and (np.isfinite(_safe_accumulator_op(np.sum, X))):
            pass
        elif is_float:
            msg_err = "Input contains {} or a value too large for {!r}."
            if (allow_nan and np.isinf(X).any() or
                    not allow_nan and not np.isfinite(X).all()):
                type_err = 'infinity' if allow_nan else 'NaN, infinity'
                raise ValueError(
                        msg_err.format
                        (type_err,
>                        msg_dtype if msg_dtype is not None else X.dtype)
                )
E               ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```

**Comment by rbharath** [comment]
I just tried running this on my local development machine (Mac), and I'm getting a clean pass. Could someone with a linux development machine try giving it a run?

CC @peastman @ncfrey @nd-02110114 @seyonechithrananda in case any of you develop with a linux machine

**Comment by peastman** [comment]
That test is passing for me on Linux.  On the other hand, `test_weave_model()` consistently fails.

**Comment by cjgalvin** [comment]
I believe I am getting the same error and will add a datapoint here for your reference.
Let me know if I can add any additional info to what I've included below.

Ubuntu 20.04
Deepchem Nightly Build (Dec. 20, 2020)

Training Weave model for regression task. GraphConvModel worked as expected.
If I train the Weave model for 10 epochs, evaluate works correctly and prints my score metric (tested with `mae_score` and `r2_score`)
If I train the Weave model for 100 epochs, I get the error traceback pasted below. I believe this is identical to the original post error.

```
Traceback (most recent call last):
  File "/.../main.py", line 22, in <module>
    print(model.evaluate(dataset, build_metrics(config)))
  File "/.../lib/python3.7/site-packages/deepchem/models/models.py", line 219, in evaluate
    n_classes=n_classes)
  File "/.../lib/python3.7/site-packages/deepchem/utils/evaluate.py", line 316, in compute_model_performance
    use_sample_weights=use_sample_weights)
  File "/.../lib/python3.7/site-packages/deepchem/metrics/metric.py", line 656, in compute_metric
    **kwargs)
  File "/.../lib/python3.7/site-packages/deepchem/metrics/metric.py", line 730, in compute_singletask_metric
    metric_value = self.metric(y_true, y_pred, **kwargs)
  File "/.../lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/.../lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 677, in r2_score
    y_true, y_pred, multioutput)
  File "/.../lib/python3.7/site-packages/sklearn/metrics/_regression.py", line 90, in _check_reg_targets
    y_pred = check_array(y_pred, ensure_2d=False, dtype=dtype)
  File "/.../lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/.../lib/python3.7/site-packages/sklearn/utils/validation.py", line 663, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/.../lib/python3.7/site-packages/sklearn/utils/validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
```

**Comment by rbharath** [comment]
Hmm, so the warnings I think are relatively harmless. I've seen them on Weave for a long time with models that have trained well. It would be nice for us to figure out what's causing them and get rid of them though.

Your broader failure is a numerical instability issue. I've seen this occasionally on some models but I don't know if there's an obvious fix. Some settings of hyperparameters seem to be numerically unstable and it seems to depend on platform (as the error at the top shows, tests fail on some systems and run on others). Honestly, I'm a little stymied here. Let's keep brainstorming to see if we can come up with some possible causes

**Comment by cjgalvin** [comment]
I understand, thanks for taking a look at my comment. If I happen to come across a solution (or other error that helps shape the contours of this issue) I will post it here.

As always, thanks for the effort that goes into Deepchem. It is very appreciated.
