### ISSUE TITLE
KeyError: 'atomic'

### ISSUE THREAD

**Issue by dkurt** [deepchem/deepchem#2362]
## 🐛 Bug

```
Traceback (most recent call last):
  File "pdbbind_atomic_conv.py", line 22, in <module>
    featurizer="atomic", split="random", subset="core")
  File "/home/dkurt/deepchem/deepchem/molnet/load_function/pdbbind_datasets.py", line 166, in load_pdbbind
    **kwargs)
  File "/home/dkurt/deepchem/deepchem/molnet/load_function/pdbbind_datasets.py", line 20, in __init__
    super(_PDBBindLoader, self).__init__(*args, **kwargs)
  File "/home/dkurt/deepchem/deepchem/molnet/load_function/molnet_loader.py", line 119, in __init__
    featurizer = featurizers[featurizer.lower()]
KeyError: 'atomic'
```

## To Reproduce

1. `cd deepchem/examples/pdbbind`
2. `python3 pdbbind_atomic_conv.py`

**Comment by rbharath** [comment]
Thanks for reporting this! The Atomic convs are currently one of the buggy parts of DeepChem that still need to be overhauled. I'll keep this issue open for us to track the fix :)
