### ISSUE TITLE
AtomicConvModel does not fit data

### ISSUE THREAD

**Issue by Mirrty** [deepchem/deepchem#2369]
## 🐛 Bug

I attempted to use AtomicConvModel with pdbbind dataset loaded with _load_pdbbind(),_ but got the following error:
```

train_dataset.get_shape()
((8, 3, 4), (8, 1), (8, 1), (8,)) # a subset of 8 molecules
model = dc.models.AtomicConvModel()
model.fit(train_dataset, nb_epoch=1)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/keras_model.py", line 307, in fit
    checkpoint_interval, restore, variables, loss, callbacks)
  File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/keras_model.py", line 360, in fit_generator
    for batch in generator:
  File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/atomic_conv.py", line 273, in default_generator
    num_features = F_b[0][0].shape[1]
IndexError: tuple index out of range
```
``

## Environment

* OS: Linux Centos 8
* Python version: 3.7
* DeepChem version: 2.3.0
* RDKit version (optional): '2020.09.1'
* TensorFlow version (optional): 1.14
* PyTorch version (optional):
* Any other relevant information:

**Comment by rbharath** [comment]
I've marked this as a bug. I'll try to take a closer look later this week!

**Comment by arunppsg** [comment]
I tried the following code from this [tutorial](https://github.com/deepchem/deepchem/blob/master/examples/tutorials/Modeling_Protein_Ligand_Interactions_With_Atomic_Convolutions.ipynb) and it seems to work:
```
from deepchem.feat import AtomicConvFeaturizer

f1_num_atoms = 100  # maximum number of atoms to consider in the ligand
f2_num_atoms = 1000  # maximum number of atoms to consider in the protein
max_num_neighbors = 12  # maximum number of spatial neighbors for an atom

acf = AtomicConvFeaturizer(frag1_num_atoms=f1_num_atoms,
                      frag2_num_atoms=f2_num_atoms,
                      complex_num_atoms=f1_num_atoms+f2_num_atoms,
                      max_num_neighbors=max_num_neighbors,
                      neighbor_cutoff=4)

tasks, datasets, transformers = dc.molnet.load_pdbbind(featurizer=acf,
                                             pocket=True,
                                             reload=False,
                                             set_name='core')


from deepchem.models import AtomicConvModel
acm = AtomicConvModel(n_tasks=1,
                      frag1_num_atoms=f1_num_atoms,
                      frag2_num_atoms=f2_num_atoms,
                      complex_num_atoms=f1_num_atoms+f2_num_atoms,
                      max_num_neighbors=max_num_neighbors,
                      batch_size=12,
                      layer_sizes=[32, 32, 16],
                      learning_rate=0.003,
                      )

acm.fit(train, nb_epoch=1)
```

A couple of points which may provide fix are:
- Try changing input parameters to the `AtomicConvModel`
- `AtomicConvFeaturizer` used during loading `pdbbind` dataset requires `pdbfixer` to be installed. Make sure that the dependencies are present in the environment.

**Comment by rbharath** [comment]
Going to go ahead and close. Feel free to re-open if there are any further issues!
