### ISSUE TITLE
Saving model

### ISSUE THREAD

**Issue by Mirrty** [deepchem/deepchem#2373]
I would like to save a built "_AtomicConvModel_" on disk, but there is the following problem:

```
model.save()
File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 924, in save
    pickle.dump(self, fout)
TypeError: can't pickle _thread.RLock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 926, in save
    logger.info(self.get_pickling_errors(self))
  File "/home/anaconda3/envs/acnn/lib/python3.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 886, in get_pickling_errors
    pickle.dumps(state[i], protocol=2)
TypeError: can't pickle _thread.RLock objects
``` 
## Environment
OS: Linux Centos 8
Python version: 3.7
DeepChem version: 2.3.0
RDKit version (optional): '2020.09.1'
TensorFlow version (optional): 1.14

**P.S** I managed to built _AtomicConvModel_ with the code written here: https://github.com/hnlab/can-ai-do/blob/master/tutorial/ACNN_PDBbind/acnn/atomic_conv.py.

**Comment by rbharath** [comment]
Ah unfortunately `AtomicConvModel` can't be saved right now. I'm working on trying to bootstrap this model over the next week or two. Will take a look!

**Comment by arunppsg** [comment]
Here is a simple step to reproduce the error:

```
inputs = tf.keras.Input(shape=(3,))
x = tf.keras.layers.Dense(4, activation=tf.nn.relu)(inputs)
outputs = tf.keras.layers.Dense(5, activation=tf.nn.softmax)(x)
model = tf.keras.Model(inputs=inputs, outputs=outputs)

joblib.dump(model, 'model.joblib')
```

From my understanding, the problem lies within tensorflow's way of saving models. As a quick fix, this works:
```
acm = atomic_conv.AtomicConvModel(n_tasks=1)
acm.model.save_weights('model.weights')
```

To fix this, we can modify `save` method to save the model weights. A related issue is that for a few other models, like `dc.models.CNN`, the `save` method is not defined.

**Comment by arunppsg** [comment]
DeepChem saves model automatically during training. To retrieve the saved model, we can use `model.restore()`.

Example:
```
acm = AtomicConvModel(n_tasks=1, batch_size=batch_size,
      layer_sizes=[1,], frag1_num_atoms=5, frag2_num_atoms=5, complex_num_atoms=10,
      model_dir=os.getcwd())
acm.fit(dataset, nb_epoch=10)
reloaded_model = AtomicConvModel(n_tasks=1, batch_size=batch_size,
      layer_sizes=[1,], frag1_num_atoms=5, frag2_num_atoms=5, complex_num_atoms=10,
      model_dir=os.getcwd())
reloaded_model.restore()
```

Probably, we can remove `save` and `reload` method as they are ambiguous @rbharath .

https://github.com/deepchem/deepchem/blob/master/deepchem/models/atomic_conv.py#L303-L309

**Comment by rbharath** [comment]
@arunppsg We should deprecate `save()` and `reload()` and modify `SklearnModel` and `XGBoostModel` to follow the same `fit()`/`restore()` flow as the deep models
