### ISSUE TITLE
ValueError when running “run_benchmark“

### ISSUE THREAD

**Issue by chen709847237** [deepchem/deepchem#2500]
## ❓ Questions & Help

Basically, I'm trying to get the benchmark test score of Weave model on tox21 dataset with the scaffold split method. 
By using:
```python
run_benchmark(datasets=['tox21'], model='weave',split='scaffold', out_path='./test_result/',  test=True)
```
BUT, an error occurred during the program running
```
2021-04-26 16:48:31.177188: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2021-04-26 16:48:31.177420: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
'split' is deprecated.  Use 'splitter' instead.
-------------------------------------
Benchmark on dataset: tox21
-------------------------------------
Splitting function: scaffold
2021-04-26 16:48:32.739343: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-04-26 16:48:32.740448: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2021-04-26 16:48:32.740659: W tensorflow/stream_executor/cuda/cuda_driver.cc:326] failed call to cuInit: UNKNOWN ERROR (303)
2021-04-26 16:48:32.743195: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: DESKTOP-F6Q8T0M
2021-04-26 16:48:32.743426: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: DESKTOP-F6Q8T0M
2021-04-26 16:48:32.743717: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-04-26 16:48:32.744409: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
WARNING:tensorflow:AutoGraph could not transform <bound method WeaveLayer.call of <deepchem.models.layers.WeaveLayer object at 0x000001709C6BB748>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <bound method WeaveGather.call of <deepchem.models.layers.WeaveGather object at 0x000001709C89B308>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:AutoGraph could not transform <function KerasModel._create_gradient_fn.<locals>.apply_gradient_for_batch at 0x000001709E40B288> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Index'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING:tensorflow:Gradients do not exist for variables ['weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/batch_normalization_3/gamma:0', 'weave_layer_1/batch_normalization_3/beta:0', 'weave_layer_1/batch_normalization_4/gamma:0', 'weave_layer_1/batch_normalization_4/beta:0', 'weave_layer_1/batch_normalization_5/gamma:0', 'weave_layer_1/batch_normalization_5/beta:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/batch_normalization_3/gamma:0', 'weave_layer_1/batch_normalization_3/beta:0', 'weave_layer_1/batch_normalization_4/gamma:0', 'weave_layer_1/batch_normalization_4/beta:0', 'weave_layer_1/batch_normalization_5/gamma:0', 'weave_layer_1/batch_normalization_5/beta:0'] when minimizing the loss.
2021-04-26 16:48:36.460711: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
WARNING:tensorflow:Gradients do not exist for variables ['weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/batch_normalization_3/gamma:0', 'weave_layer_1/batch_normalization_3/beta:0', 'weave_layer_1/batch_normalization_4/gamma:0', 'weave_layer_1/batch_normalization_4/beta:0', 'weave_layer_1/batch_normalization_5/gamma:0', 'weave_layer_1/batch_normalization_5/beta:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/kernel:0', 'weave_layer_1/Variable:0', 'weave_layer_1/batch_normalization_3/gamma:0', 'weave_layer_1/batch_normalization_3/beta:0', 'weave_layer_1/batch_normalization_4/gamma:0', 'weave_layer_1/batch_normalization_4/beta:0', 'weave_layer_1/batch_normalization_5/gamma:0', 'weave_layer_1/batch_normalization_5/beta:0'] when minimizing the loss.
Traceback (most recent call last):
  File "D:/mol_net_2021/other_compare/test.py", line 27, in <module>
    run_benchmark.run_benchmark(datasets=['tox21'], model='weave',split='scaffold', out_path='D:\mol_net_2021\other_compare\\',  test=True, hyper_parameters=para_data)
  File "D:\mol_net_2021\other_compare\deepchem\molnet\run_benchmark.py", line 192, in run_benchmark
    seed=seed)
  File "D:\mol_net_2021\other_compare\deepchem\molnet\run_benchmark_models.py", line 375, in benchmark_classification
    train_scores[model_name] = model.evaluate(train_dataset, metric, transformers)
  File "D:\mol_net_2021\other_compare\deepchem\models\models.py", line 220, in evaluate
    n_classes=n_classes)
  File "D:\mol_net_2021\other_compare\deepchem\utils\evaluate.py", line 316, in compute_model_performance
    use_sample_weights=use_sample_weights)
  File "D:\mol_net_2021\other_compare\deepchem\metrics\metric.py", line 640, in compute_metric
    **kwargs)
  File "D:\mol_net_2021\other_compare\deepchem\metrics\metric.py", line 704, in compute_singletask_metric
    metric_value = self.metric(y_true, y_pred, **kwargs)
  File "C:\Users\mb85409\Anaconda3\envs\deepchem\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\mb85409\Anaconda3\envs\deepchem\lib\site-packages\sklearn\metrics\_ranking.py", line 524, in roc_auc_score
    y_score = check_array(y_score, ensure_2d=False)
  File "C:\Users\mb85409\Anaconda3\envs\deepchem\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "C:\Users\mb85409\Anaconda3\envs\deepchem\lib\site-packages\sklearn\utils\validation.py", line 664, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "C:\Users\mb85409\Anaconda3\envs\deepchem\lib\site-packages\sklearn\utils\validation.py", line 106, in _assert_all_finite
    msg_dtype if msg_dtype is not None else X.dtype)
ValueError: Input contains NaN, infinity or a value too large for dtype('float32').
```
After checking the detail of error information. We believe this error is caused by the training score calculation
```python
train_scores[model_name] = model.evaluate(train_dataset, metric, transformers)
```
The model predicts ```NaN``` for all input data. But all hyperparameters were set as default value
So, the question is How to solve this problem and getting the test score of Weave model on Tox21 dataset. 
My local environment is Windows10 (I also tried the script on Linux but the error is the same) with Anaconda 4.10.1 and the following libraries:
```
python                    3.7.10
tensorflow                2.4.1
deepchem                  2.5.0
```

Thank you very much for your help!

**Comment by rbharath** [comment]
Sometimes the weave models can exhibit numerical instabilities for some values of hyperparameters. I'd recommend trying a few different variants of the hyperparameters to find a range that is stable. I hope that helps!

**Comment by AYUSH676-JARVIS** [comment]
I was able to reproduce the issue by running run_benchmark. py.

The error occurs during [mention step from traceback].

I am investigating the root cause and will propose a fix.
