### ISSUE TITLE
 FeaturizationTransformer error---required positional argument: 'datapoints'

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2686]
## ❓ Questions & Help
Hi, everybody !
      when transforming dataset by FeaturizationTransformer, error occurred. can someone help me?
the .csv data source are renal clearance indicates with X=smiles, y=clearance value(cl_renal), codes as follows:

```
import deepchem as dc

featurizer = dc.feat.MolGraphConvFeaturizer(1024)
loader = dc.data.CSVLoader(tasks=['cl_renal'], feature_field="smiles", featurizer=featurizer)
dataset = loader.create_dataset("./data/CL_renal_kg.csv")
transformer = dc.trans.FeaturizationTransformer(dataset, dc.feat.MolGraphConvFeaturizer)
dataset = transformer.transform(dataset)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/python/anaconda3/lib/python3.7/site-packages/deepchem/trans/transformers.py", line 201, in transform
    return dataset.transform(self, out_dir=out_dir, parallel=parallel)
  File "/home/python/anaconda3/lib/python3.7/site-packages/deepchem/data/datasets.py", line 1777, in transform
    generator(), data_dir=out_dir, tasks=tasks)
  File "/home/python/anaconda3/lib/python3.7/site-packages/deepchem/data/datasets.py", line 1204, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "/home/python/anaconda3/lib/python3.7/site-packages/deepchem/data/datasets.py", line 1773, in generator
    newx, newy, neww, newids = transformer.transform_array(X, y, w, ids)
  File "/home/python/anaconda3/lib/python3.7/site-packages/deepchem/trans/transformers.py", line 2241, in transform_array
    X = self.featurizer.featurize(X)
TypeError: featurize() missing 1 required positional argument: 'datapoints'
```

so where and how to set the positional argument: 'datapoints'  ? many thanks for any help!

**Comment by biotech7** [comment]
issued solved, some codes ommited.
