### ISSUE TITLE
why "No molecule provided" when running  ScaffoldSplitter() ?

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2692]
## ❓ Questions & Help
when running ScaffoldSplitter() it raised "No molecule provided" error. cannot figure out what's wrong?
the datasource has included SMILES.
deepchem version: 2.6.0 dev( pytorch backend) 
OS: win10

```
import deepchem as dc

featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)
loader = dc.data.CSVLoader(tasks=['target'], feature_field="smile", id_field="id", featurizer=featurizer)
dataset = loader.create_dataset(['./data/clearance.csv'])

transformer = dc.trans.NormalizationTransformer(transform_y=True, dataset=dataset)
dataset = transformer.transform(dataset)

splitter = dc.splits.ScaffoldSplitter()
train_dataset, valid_dataset, test_dataset = splitter.train_valid_test_split(dataset=dataset)

Traceback (most recent call last):
  File "D:\ProgramData\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-8ce2b4937028>", line 2, in <module>
    dataset=dataset)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\splits\splitters.py", line 165, in train_valid_test_split
    log_every_n=log_every_n)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\splits\splitters.py", line 1358, in split
    scaffold_sets = self.generate_scaffolds(dataset)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\splits\splitters.py", line 1401, in generate_scaffolds
    scaffold = _generate_scaffold(smiles)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\splits\splitters.py", line 1175, in _generate_scaffold
    scaffold = MurckoScaffoldSmiles(mol=mol, includeChirality=include_chirality)
  File "D:\ProgramData\anaconda\lib\site-packages\rdkit\Chem\Scaffolds\MurckoScaffold.py", line 108, in MurckoScaffoldSmiles
    raise ValueError('No molecule provided')
ValueError: No molecule provided
```

**Comment by rbharath** [comment]
I think for some reason your dataset isn't featurizing properly. Trying printing out the `dataset` object in IPython and check that `dataset.X` doesn't contain Nones

**Comment by biotech7** [comment]
after many trials, it's comfirmed parameter `id_field="id"`  in CSVLoader() caused this error. if excluding this para, it works well.
cheers!
