### ISSUE TITLE
can AttentiveFPModel implement of features of chirality and partial_charge?

### ISSUE THREAD

**Issue by biotech7** [deepchem/deepchem#2699]
## ❓ Questions & Help
Hi,
i want to train a model by setting "use_chirality=True, use_partial_charge=True" in 
`featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True, use_chirality=True, use_partial_charge=True)`
in terms of `dc.models.torch_models.AttentiveFPModel()`
but it resulted in errors when starting training model.  
Is it compatible implementation of chirality and partial_charge with AttentiveFPModel?
if not, which graph models are compatible with the paras mentioned above?

**Comment by biotech7** [comment]
**### codes to reproduce:** 

```
import deepchem as dc
from deepchem.models import AttentiveFPModel
smiles = ["C1CCC1", "C1=CC=CN=C1"]
labels = [0., 1.]
featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True, use_chirality=True, use_partial_charge=True)
X = featurizer.featurize(smiles)
dataset = dc.data.NumpyDataset(X=X, y=labels)
model = AttentiveFPModel(mode='classification', n_tasks=1,
   batch_size=16, learning_rate=0.001)
loss = model.fit(dataset, nb_epoch=5)

Traceback (most recent call last):
  File "D:\ProgramData\anaconda\lib\site-packages\IPython\core\interactiveshell.py", line 3441, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-247c50c10fba>", line 1, in <module>
    loss = model.fit(dataset, nb_epoch=5)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\torch_model.py", line 338, in fit
    checkpoint_interval, restore, variables, loss, callbacks, all_losses)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\torch_model.py", line 424, in fit_generator
    outputs = self.model(inputs)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\deepchem\models\torch_models\attentivefp.py", line 163, in forward
    out = self.model(g, node_feats, edge_feats)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\dgllife\model\model_zoo\attentivefp_predictor.py", line 87, in forward
    node_feats = self.gnn(g, node_feats, edge_feats)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\dgllife\model\gnn\attentivefp.py", line 357, in forward
    node_feats = self.init_context(g, node_feats, edge_feats)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\dgllife\model\gnn\attentivefp.py", line 223, in forward
    g.ndata['hv_new'] = self.project_node(node_feats)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\modules\linear.py", line 91, in forward
    return F.linear(input, self.weight, self.bias)
  File "D:\ProgramData\anaconda\lib\site-packages\torch\nn\functional.py", line 1674, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: size mismatch, m1: [80 x 33], m2: [30 x 200] at ..\aten\src\TH/generic/THTensorMath.cpp:41

```

**Comment by rbharath** [comment]
@mufeili Would you happen to know the answer? I think AttentiveFPModel is a dgl-lifesci model and I'm not as familiar with the implementation

**Comment by mufeili** [comment]
@biotech7 @rbharath Do you know if setting `use_chirality=True, use_partial_charge=True` gives you additional numerical values for the input node features? If so, I guess you just need to adjust the input node feature size.

**Comment by biotech7** [comment]
@mufeili @rbharath  i'll get a try. hope to solve this issue. 
Regards!
