### ISSUE TITLE
Tensorflow 0.12 breaks Python 3.5

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#301]
```

======================================================================
ERROR: Failure: NotFoundError (/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/anaconda/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/travis/anaconda/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/travis/anaconda/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/travis/anaconda/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/travis/anaconda/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/travis/anaconda/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/travis/build/deepchem/deepchem/deepchem/__init__.py", line 12, in <module>
    import deepchem.models
  File "/home/travis/build/deepchem/deepchem/deepchem/models/__init__.py", line 10, in <module>
    from deepchem.models.tf_keras_models.multitask_classifier import MultitaskGraphClassifier
  File "/home/travis/build/deepchem/deepchem/deepchem/models/tf_keras_models/multitask_classifier.py", line 14, in <module>
    from deepchem.models.tensorflow_models import model_ops
  File "/home/travis/build/deepchem/deepchem/deepchem/models/tensorflow_models/__init__.py", line 22, in <module>
    from tensorflow.contrib.layers.python.layers import batch_norm
  File "/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/__init__.py", line 25, in <module>
    from tensorflow.contrib import cudnn_rnn
  File "/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 21, in <module>
    from tensorflow.contrib.cudnn_rnn.python.ops.cudnn_rnn_ops import CudnnGRU
  File "/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 28, in <module>
    resource_loader.get_path_to_datafile("_cudnn_rnn_ops.so"))
  File "/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/util/loader.py", line 42, in load_op_library
    ret = load_library.load_op_library(path)
  File "/home/travis/anaconda/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/travis/anaconda/lib/python3.5/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so: cannot open shared object file: No such file or directory
```

For now, seeing if setting test version to 0.10 handles this issue. Will need to figure out a proper fix.

**Comment by rbharath** [comment]
This might be caused by fact that that we're not using the recommended conda installation for tensorflow. First debugging step is to probably swap over to that version and see if we still have problems.

**Comment by gufodotto** [comment]
Hi guys,

just installed your framework over the weekend to try it out, excellent work. 
I initially ran into the issue above, and found that updating the tensorflow from within conda indeed seems to fix it.

**Comment by rbharath** [comment]
@gufodotto Thanks for the pointer! Will make a fix to the install/test scripts.

**Comment by rbharath** [comment]
Just realized that #275 was already open...

**Comment by rbharath** [comment]
Going to close. Not seeing this issue with new `pip` install command for Tensorflow.
