### ISSUE TITLE
dgl dependency causes model training to fail 

### ISSUE THREAD

**Issue by simonaxelrod** [deepchem/deepchem#3149]
Thanks for the great open-source software and documentation, DeepChem team! I really love the project.

I'm running into an issue training an attentive FP model related to dgl. Here are the details:

## 🐛 Bug

Training an attentive FP model fails because the GPU version of dgl is required. Installing the GPU version then causes it to fail for a different dgl-related issue.

## To Reproduce

1. Create deepchem environment: `conda create --name deepchem python=3.7`
2. Activate environment: `conda activate deepchem`
3. Install torch: `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu116`
4. Install deepchem: `pip install deepchem[torch]`
5. Try to train attentive FP model:
```python
import deepchem as dc
from deepchem.models import AttentiveFPModel
# preparing dataset
smiles = ["C1CCC1", "C1=CC=CN=C1"]
labels = [0., 1.]
featurizer = dc.feat.MolGraphConvFeaturizer(use_edges=True)
X = featurizer.featurize(smiles)
dataset = dc.data.NumpyDataset(X=X, y=labels)
# training model
model = AttentiveFPModel(mode='regression', n_tasks=1,
   batch_size=16, learning_rate=0.001)
loss = model.fit(dataset, nb_epoch=5) # fails here
```

The code fails on the last line when trying to train the model. Here is the stack trace:

```python
>>> loss = model.fit(dataset, nb_epoch=5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/torch_model.py", line 335, in fit
    callbacks, all_losses)
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/torch_model.py", line 413, in fit_generator
    inputs, labels, weights = self._prepare_batch(batch)
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/attentivefp.py", line 307, in _prepare_batch
    inputs = dgl.batch(dgl_graphs).to(self.device)
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/heterograph.py", line 5448, in to
    ret._graph = self._graph.copy_to(utils.to_dgl_context(device))
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/heterograph_index.py", line 237, in copy_to
    return _CAPI_DGLHeteroCopyTo(self, ctx.device_type, ctx.device_id)
  File "dgl/_ffi/_cython/./function.pxi", line 293, in dgl._ffi._cy3.core.FunctionBase.__call__
  File "dgl/_ffi/_cython/./function.pxi", line 225, in dgl._ffi._cy3.core.FuncCall
  File "dgl/_ffi/_cython/./function.pxi", line 215, in dgl._ffi._cy3.core.FuncCall3
dgl._ffi.base.DGLError: [14:58:44] /opt/dgl/src/runtime/c_runtime_api.cc:88: Check failed: allow_missing: Device API gpu is not enabled. Please install the cuda version of dgl.
Stack trace:
  [bt] (0) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x4f) [0x7f1adb0fe6ef]
  [bt] (1) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPIManager::GetAPI(std::string, bool)+0x37c) [0x7f1adb3cc7dc]
  [bt] (2) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::DeviceAPI::Get(DLContext, bool)+0x1f4) [0x7f1adb3c6b44]
  [bt] (3) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::Empty(std::vector<long, std::allocator<long> >, DLDataType, DLContext)+0x15b) [0x7f1adb3e824b]
  [bt] (4) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::runtime::NDArray::CopyTo(DLContext const&) const+0xc0) [0x7f1adb425000]
  [bt] (5) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::aten::COOMatrix::CopyTo(DLContext const&) const+0x7d) [0x7f1adb54709d]
  [bt] (6) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::UnitGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DLContext const&)+0x2aa) [0x7f1adb53665a]
  [bt] (7) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(dgl::HeteroGraph::CopyTo(std::shared_ptr<dgl::BaseHeteroGraph>, DLContext const&)+0xf5) [0x7f1adb436d65]
  [bt] (8) /home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/libdgl.so(+0x4e748b) [0x7f1adb44448b]
```

I tried fixing this issue by installing the GPU version of dgl: `pip install dgl-cu101`. Now things fail with a different dgl-related error, but it happens when creating the model, before even trying to train:

```python
>>> model = AttentiveFPModel(mode='regression', n_tasks=1,
   batch_size=16, learning_rate=0.001)
Traceback (most recent call last):
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/attentivefp.py", line 102, in __init__
    import dgl
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/backend/__init__.py", line 95, in <module>
    load_backend(get_preferred_backend())
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/backend/__init__.py", line 41, in load_backend
    from .._ffi.base import load_tensor_adapter # imports DGL C library
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/_ffi/base.py", line 44, in <module>
    _LIB, _LIB_NAME, _DIR_NAME = _load_lib()
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/dgl/_ffi/base.py", line 34, in _load_lib
    lib = ctypes.CDLL(lib_path[0])
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.1: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/attentivefp.py", line 269, in __init__
    n_classes=n_classes)
  File "/home/saxelrod/miniconda3/envs/deepchem/lib/python3.7/site-packages/deepchem/models/torch_models/attentivefp.py", line 104, in __init__
    raise ImportError('This class requires dgl.')
ImportError: This class requires dgl.
```

Thanks in advance for all your help!

**Comment by gusty1g** [comment]
Do you have cuda toolkit installed? I think running `nvidia-smi` will show cuda toolkit version. Also, could you try running in a cpu only environment, I think it's an environment issue.

**Comment by simonaxelrod** [comment]
Good call, thanks! I ran it in a cpu only environment and it worked great. But still no dice on the GPU version. I ran `nvidia-smi`, and the cuda version is 11.4. I tried making the environment again and installing torch for cuda 11.3 instead of 11.6 (`pip install torch==1.12.1+cu113 torchvision==0.13.1+cu113 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu113
`), but got the same initial issue. I then installed dgl with cuda 11.3 (`pip install dgl-cu113 dglgo -f https://data.dgl.ai/wheels/repo.html`), but it still didn't work.

**Comment by kevingreenman** [comment]
I was able to reproduce this issue with the following:
```
conda create --name deepchem python=3.7
conda activate deepchem
pip install torch torchvision torchaudio
pip install deepchem[torch]
```
The torch installation command above was given by https://pytorch.org/ for PyTorch Build Stable (2.0.0), Linux, Pip, Python, Cuda 11.7.

But then I was able to get the example script working by running:
```
pip uninstall dgl
pip install  dgl -f https://data.dgl.ai/wheels/cu117/repo.html
pip install  dglgo -f https://data.dgl.ai/wheels-test/repo.html
```
The dgl CUDA installation instructions were given by https://www.dgl.ai/pages/start.html for CUDA 11.7, Pip(Stable), Linux.
