### ISSUE TITLE
k_fold_split does not work on RandomGroupSplitter

### ISSUE THREAD

**Issue by hochej** [deepchem/deepchem#3253]
## 🐛 Bug

Using the k_fold_split method seems to cause problems with the RandomGroupSplitter because the length of the group sequence does not match the dataset (`rem_dataset`) 

## To Reproduce

```python
import deepchem as dc
import numpy as np

groups = [0, 0, 0, 1, 1, 1, 2, 2, 2, 3, 3, 3]
splitter = dc.splits.RandomGroupSplitter(groups=groups)
dataset = dc.data.NumpyDataset(X=np.arange(12))   # 12 elements
folds = splitter.k_fold_split(dataset, 3)

for (train, test) in folds:
    print (train.ids)  
```
Executing this code leads to the following error:

```
Traceback (most recent call last):
  File "xxxx/test_dc.py", line 9, in <module>
    folds = splitter.k_fold_split(dataset, 3)
  File "xxxx/python3.10/site-packages/deepchem/splits/splitters.py", line 86, in k_fold_split
    fold_inds, rem_inds, _ = self.split(rem_dataset,
  File "xxxx/python3.10/site-packages/deepchem/splits/splitters.py", line 465, in split
    assert len(self.groups) == dataset.X.shape[0]
AssertionError
```

## Expected behavior

I would expect either that the RandomGroupSplitter does not support and does not implement the k_fold_split method, or that k splits are generated where the indexes are properly grouped. 

## Environment

* OS: SUSE Linux Enterprise HPC 15 SP3
* Python version: 3.10.6
* DeepChem version: 2.7.2.dev
* RDKit version: 2022.09.4
* TensorFlow version: 2.11.0
* PyTorch version: 1.13.1

## Additional context
I think the problem is with the k_fold_split method, because here the dataset (`rem_dataset`) used in each iteration (over k) is shrunk and thus no longer has the same length as the groups (see L94 in splitters.py).
https://github.com/deepchem/deepchem/blob/a7341360cb997c5c6c4d87c8f890621347f7bf10/deepchem/splits/splitters.py#L94

Since the split is then performed on this data set and the groups are passed here, the assertion check then fails.  
https://github.com/deepchem/deepchem/blob/a7341360cb997c5c6c4d87c8f890621347f7bf10/deepchem/splits/splitters.py#L86

**Comment by rbharath** [comment]
Thank you for the report! I've marked this as a bug. It may require some thought to fix this interaction since I'm not sure how to make k_fold_split work properly in this case

**Comment by Nozziel** [comment]
yeah the current issue is that k_fold_split will repeatedly call `split` to split of the number of requested folds thus the second and later calls will be done on a smaller (remaining) dataset, and thus crashes.
 
Without going in to very fancy solutions, I could implement a `RandomGroupSplitter.k_fold_split` that splits the groups in folds.
We would assume that each group is on average similar in size (for which we could log a warning).

Is that a way forward? Alternatively I can enable a `NotImplemented` exception with some info as why this is not working for `RandomGroupSplitter`.
