### ISSUE TITLE
Issues with Generating Molecules with MolGAN

### ISSUE THREAD

**Issue by xavierchee** [deepchem/deepchem#3290]
**Good morning, i've been following the codes in the tutorial and noticed this issue when running the codes at** 

In[14]:  gan.fit_gan(iterbatches(25), generator_steps=0.2, checkpoint_interval=5000)
            generated_data = gan.predict_gan_generator(1000)

**The error message was:** 
KeyError                                  Traceback (most recent call last)
[<ipython-input-35-aa2c2447b447>](https://localhost:8080/#) in <module>
----> 1 gan.fit_gan(iterbatches(25), generator_steps=0.2, checkpoint_interval=5000)
      2 generated_data = gan.predict_gan_generator(1000)

14 frames
[/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py](https://localhost:8080/#) in _update_step(self, gradient, variable)
    214             return
    215         if self._var_key(variable) not in self._index_dict:
--> 216             raise KeyError(
    217                 f"The optimizer cannot recognize variable {variable.name}. "
    218                 "This usually means you are trying to call the optimizer to "

KeyError: in user code:
    File "/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 208, in _update_step_xla  *
        return self._update_step(gradient, variable)
    File "/usr/local/lib/python3.9/dist-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 216, in _update_step  **
        raise KeyError(
    KeyError: 'The optimizer cannot recognize variable SimpleMolGANGenerator/dense_40/kernel:0. This usually means you are trying to call the optimizer to update different parts of the model separately. Please call `optimizer.build(variables)` with the full list of trainable variables before the training loop or use legacy optimizer `tf.keras.optimizers.legacy.{self.__class__.__name__}.'

May i know how should i resolve this? The codes were run on Google Colab on Python 3.9.16.
Thanks!

**Comment by rbharath** [comment]
Thanks for the report! This looks like a potential bug. Which tutorial did you encounter this error in?

**Comment by xavierchee** [comment]
No problem. The tutorial name is: Generating_molecules_with_MolGAN. Thanks Rbharath!

**Comment by mmontazeri2001** [comment]
Same issue for me

**Comment by moben1** [comment]
I am encountering the same error, did you find any solution?

**Comment by xavierchee** [comment]
Nope, not yet

**Comment by rbharath** [comment]
@shreyasvinaya Could you please take a look since you are working on MolGANs?

**Comment by shreyasvinaya** [comment]
@xavierchee @moben1 The error seems to be fixed on colab and the model is generating valid molecules
