### ISSUE TITLE
hyperparameter optimization

### ISSUE THREAD

**Issue by SoodabehGhaffari** [deepchem/deepchem#3356]
Hello,
I am running hyper-parameter optimization with the command below:
bench.optimize_hyperparams(df_train=df_train, epochs=50, max_evals=30, splitter='maxmin',
                            best_model_dir='best_model_smiles_1task_maxmin',
                            trials_save_file='hyperopt_1task_maxmin')

It is running smoothly until step 29 (note that max_eval is 30) and then it gives me the error below (see the tail of the error). Any suggestions are greatly appreciated.

^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss: -0.014113463905251191]^M                                                                                           ^MSplitting done...
^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss: -0.014113463905251191]^M                                                                                           ^MTraining model...
^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss: -0.014113463905251191]Step 3800 validation: mean_squared_error=110.455
Step 7600 validation: mean_squared_error=134.62
Step 11400 validation: mean_squared_error=119.962
Step 15200 validation: mean_squared_error=160.632
Step 19000 validation: mean_squared_error=112.992
Step 22800 validation: mean_squared_error=125.723
Step 26600 validation: mean_squared_error=107.48
Step 30400 validation: mean_squared_error=126.179
^M                                                                                           ^M--All metrics:-----
^M 93%|█████████▎| 28/30 [26:10:02<1:11:41, 2150.60s/trial, best loss: -0.014113463905251191]^M                                                                                           ^MPearson correlation training: 0.09196818234168698, validation: 0.015237410336668858, all: 0.0704538023080769.
^M 93%|█████████▎| 28/30 [26:11:28<1:11:41, 2150.60s/trial, best loss: -0.014113463905251191]^M 97%|█████████▋| 29/30 [26:11:28<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]^M                                                                                           ^MMaxMinSplitter
^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]^M                                                                                           ^MSplitting done...
^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]^M                                                                                           ^MTraining model...
^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]Step 3800 validation: mean_squared_error=113.592
Step 7600 validation: mean_squared_error=159.396
Step 11400 validation: mean_squared_error=136.259
Step 15200 validation: mean_squared_error=156.028
Step 19000 validation: mean_squared_error=124.103
Step 22800 validation: mean_squared_error=116.274
Step 26600 validation: mean_squared_error=142.842
Step 30400 validation: mean_squared_error=142.032
^M                                                                                           ^M--All metrics:-----
^M 97%|█████████▋| 29/30 [28:34:27<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]^M                                                                                           ^MPearson correlation training: 0.02356629150571425, validation: 0.004057812100650602, all: 0.018072315509814224.
^M 97%|█████████▋| 29/30 [28:35:52<1:08:17, 4097.32s/trial, best loss: -0.015237410336668858]^M100%|██████████| 30/30 [28:35:52<00:00, 5467.29s/trial, best loss: -0.015237410336668858]  ^M100%|██████████| 30/30 [28:35:52<00:00, 3431.75s/trial, best loss: -0.015237410336668858]
Best parameters found: {'atom_features': 78, 'batch_size': 100, 'dense_layers': 32, 'dropout': 0.05398003300872365, 'graph_conv_layers': (1000, 1000), 'learning_rate': 0.0007921334854473414}
Traceback (most recent call last):
  File "/scratch/gpfs/sg6615/PA/examples/PA.py", line 19, in <module>
    bench.optimize_hyperparams(df_train=df_train, epochs=50, max_evals=30, splitter='maxmin',
  File "/scratch/gpfs/sg6615/PA/models/graphcnn.py", line 228, in optimize_hyperparams
    self.train_model(
  File "/scratch/gpfs/sg6615/PA/models/graphcnn.py", line 101, in train_model
    train_dataset, valid_dataset = splitter.train_test_split(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'train_test_split'

**Comment by SoodabehGhaffari** [comment]
Thanks for the response! I think I need to clarify my question:
I specified the type of splitting in my training function and I then call
training function in the hyper-parameter optimization. It runs smoothly for
28 steps of evaluation (max_evaluation=30). However, when it reaches step
29th of the evaluation, it gives me an error about splitting. It is weird
to me because if the splitting is not defined properly, it should give me
an error in the first step. Please see the log file below:

Any suggestions are greatly appreciated.

Best Regards
Soodabeh

*^M 90%|█████████ | 27/30 [23:25:52<1:51:37, 2232.66s/trial, best loss:
-0.014113463905251191]Step 3800 validation: mean_squared_error=145.481*

*Step 7600 validation: mean_squared_error=118.176*

*Step 11400 validation: mean_squared_error=126.549*

*Step 15200 validation: mean_squared_error=163.341*

*Step 19000 validation: mean_squared_error=132.775*

*Step 22800 validation: mean_squared_error=158.334*

*^M
                  ^M--All metrics:-----*

*^M 90%|█████████ | 27/30 [23:47:09<1:51:37, 2232.66s/trial, best loss:
-0.014113463905251191]^M
                                        ^MPearson correlation training:
0.040205183536306484, validation: 0.0051111268953438855, all:
0.030421096869775583.*

*^M 90%|█████████ | 27/30 [23:47:29<1:51:37, 2232.66s/trial, best loss:
-0.014113463905251191]^M 93%|█████████▎| 28/30 [23:47:29<1:11:41,
2150.60s/trial, best loss: -0.014113463905251191]^M

^MMaxMinSplitter*

*^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss:
-0.014113463905251191]^M
                                        ^MSplitting done...*

*^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss:
-0.014113463905251191]^M
                                        ^MTraining model...*

*^M 93%|█████████▎| 28/30 [23:58:28<1:11:41, 2150.60s/trial, best loss:
-0.014113463905251191]Step 3800 validation: mean_squared_error=110.455*

*Step 7600 validation: mean_squared_error=134.62*

*Step 11400 validation: mean_squared_error=119.962*

*Step 15200 validation: mean_squared_error=160.632*

*Step 19000 validation: mean_squared_error=112.992*

*Step 22800 validation: mean_squared_error=125.723*

*Step 26600 validation: mean_squared_error=107.48*

*Step 30400 validation: mean_squared_error=126.179*

*^M
                  ^M--All metrics:-----*

*^M 93%|█████████▎| 28/30 [26:10:02<1:11:41, 2150.60s/trial, best loss:
-0.014113463905251191]^M
                                        ^MPearson correlation training:
0.09196818234168698, validation: 0.015237410336668858, all:
0.0704538023080769.*

*^M 93%|█████████▎| 28/30 [26:11:28<1:11:41, 2150.60s/trial, best loss:
-0.014113463905251191]^M 97%|█████████▋| 29/30 [26:11:28<1:08:17,
4097.32s/trial, best loss: -0.015237410336668858]^M

^MMaxMinSplitter*

*^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss:
-0.015237410336668858]^M
                                        ^MSplitting done...*

*^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss:
-0.015237410336668858]^M
                                        ^MTraining model...*

*^M 97%|█████████▋| 29/30 [26:22:27<1:08:17, 4097.32s/trial, best loss:
-0.015237410336668858]Step 3800 validation: mean_squared_error=113.592*

*Step 7600 validation: mean_squared_error=159.396*

*Step 11400 validation: mean_squared_error=136.259*

*Step 15200 validation: mean_squared_error=156.028*

*Step 19000 validation: mean_squared_error=124.103*

*Step 22800 validation: mean_squared_error=116.274*

*Step 26600 validation: mean_squared_error=142.842*

*Step 30400 validation: mean_squared_error=142.032*

*^M
                  ^M--All metrics:-----*

*^M 97%|█████████▋| 29/30 [28:34:27<1:08:17, 4097.32s/trial, best loss:
-0.015237410336668858]^M
                                        ^MPearson correlation training:
0.02356629150571425, validation: 0.004057812100650602, all:
0.018072315509814224.*

*^M 97%|█████████▋| 29/30 [28:35:52<1:08:17, 4097.32s/trial, best loss:
-0.015237410336668858]^M100%|██████████| 30/30 [28:35:52<00:00,
5467.29s/trial, best loss: -0.015237410336668858]  ^M100%|██████████| 30/30
[28:35:52<00:00, 3431.75s/trial, best loss: -0.015237410336668858]*

*Best parameters found: {'atom_features': 78, 'batch_size': 100,
'dense_layers': 32, 'dropout': 0.05398003300872365, 'graph_conv_layers':
(1000, 1000), 'learning_rate': 0.0007921334854473414}*

*Traceback (most recent call last):*

*  File "/scratch/gpfs/sg6615/PA/examples/PA.py", line 19, in <module>*

*    bench.optimize_hyperparams(df_train=df_train, epochs=50, max_evals=30,
splitter='maxmin',*

*  File "/scratch/gpfs/sg6615/PA/models/graphcnn.py", line 228, in
optimize_hyperparams*

*    self.train_model(*

*  File "/scratch/gpfs/sg6615/PA/models/graphcnn.py", line 101, in
train_model*

*    train_dataset, valid_dataset = splitter.train_test_split(*

*                                   ^^^^^^^^^^^^^^^^^^^^^^^^^*

*AttributeError: 'str' object has no attribute 'train_test_split'*
