### ISSUE TITLE
model.fit return nan

### ISSUE THREAD

**Issue by rybakov-ks** [deepchem/deepchem#3469]
## ❓ Questions & Help

I want to run the standard example on the bandgap dataset. I am running the following code:
```python
import deepchem as dc
import os

os.environ['DEEPCHEM_DATA_DIR'] = os.getcwd()

tasks, datasets, transformers = dc.molnet.load_bandgap()
train_dataset, val_dataset, test_dataset = datasets
n_tasks = len(tasks)
n_features = train_dataset.get_data_shape()[0]
model = dc.models.MultitaskRegressor(n_tasks, n_features)
result = model.fit(train_dataset, nb_epoch=100)
print(result)
```
This code returns:
```python
nan
```
## Expected behavior
The average loss over the most recent checkpoint interval. For example:
```python
model.fit(train_dataset, nb_epoch=100) # => 0.11707531929016113
```

If I run the following code:
```python
band_energy = model.predict_on_batch(test_dataset.X[0])
print(band_energy)
```
Returns:
```python
[[[nan]]]
```
If I use the Delaney (ESOL) data set, then everything works fine.

## Environment
OS: Windows 11
Python version: Python  3.11.4
DeepChem version: 2.6.0.dev
RDKit version: 2023.3.2
TensorFlow version: 2.12.0
PyTorch version: 2.0.1+cu117
Pymatgen version: 2023.6.28

**Comment by quincylin1** [comment]
Hi @rybakov-ks, I couldn't reproduce your error and got the following output when running your code:

```python
Failed to featurize datapoint 4589. Appending empty array
Failed to featurize datapoint 4590. Appending empty array
Failed to featurize datapoint 4591. Appending empty array
Failed to featurize datapoint 4592. Appending empty array
Failed to featurize datapoint 4593. Appending empty array
Failed to featurize datapoint 4594. Appending empty array
Failed to featurize datapoint 4595. Appending empty array
Failed to featurize datapoint 4596. Appending empty array
Failed to featurize datapoint 4597. Appending empty array
Failed to featurize datapoint 4598. Appending empty array
Failed to featurize datapoint 4599. Appending empty array
Failed to featurize datapoint 4600. Appending empty array
Failed to featurize datapoint 4601. Appending empty array
Failed to featurize datapoint 4602. Appending empty array
Failed to featurize datapoint 4603. Appending empty array
Traceback (most recent call last):
  File "pre_train_error.py", line 6, in <module>
    tasks, datasets, transformers = dc.molnet.load_bandgap()
  File "/Users/linquincy/Downloads/deepchem/deepchem/molnet/load_function/material_datasets/load_bandgap.py", line 105, in load_bandgap
    return loader.load_dataset('bandgap', reload)
  File "/Users/linquincy/Downloads/deepchem/deepchem/molnet/load_function/molnet_loader.py", line 190, in load_dataset
    transformers = [
  File "/Users/linquincy/Downloads/deepchem/deepchem/molnet/load_function/molnet_loader.py", line 191, in <listcomp>
    t.create_transformer(transformer_dataset) for t in self.transformers
  File "/Users/linquincy/Downloads/deepchem/deepchem/molnet/load_function/molnet_loader.py", line 37, in create_transformer
    return self.transformer_class(dataset=dataset, **self.kwargs)
  File "/Users/linquincy/Downloads/deepchem/deepchem/trans/transformers.py", line 488, in __init__
    y_means, y_stds = dataset.get_statistics(X_stats=False,
  File "/Users/linquincy/Downloads/deepchem/deepchem/data/datasets.py", line 463, in get_statistics
    x_shape, y_shape, w_shape, ids_shape = self.get_shape()
  File "/Users/linquincy/Downloads/deepchem/deepchem/data/datasets.py", line 2690, in get_shape
    return tuple(X_shape), tuple(y_shape), tuple(w_shape), tuple(
UnboundLocalError: local variable 'X_shape' referenced before assignment
```

**Comment by rbharath** [comment]
If this is still an issue, I'd recommend checking out the learning rate or verifying the numerical libraries are installed correctly
