### ISSUE TITLE
Pre-training GNNModular model for node representation learning with low batch size

### ISSUE THREAD

**Issue by arunppsg** [deepchem/deepchem#3650]
On pre-training GNNModular model for node representation learning with low batch size, throws ValueError. Steps to reproduce:

```py
import deepchem as dc
from deepchem.models.torch_models import GNNModular
import torch

featurizer = dc.feat.SNAPFeaturizer()
tasks, datasets, transformers = dc.molnet.load_delaney(featurizer=featurizer, data_dir='datadir')
train, test, valid = datasets


model = dc.models.GNNModular(context_mode = 'cbow', emb_dim=300,
                             task='context_pred', neg_samples=1,
                             jump_knowledge='last', neighborhood_size=2,
                             num_layer=5,
                            model_dir='snap-node-level',
                            batch_size=16,
                            device=torch.device('cpu'))

model.fit(train)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
  File "/opt/conda/lib/python3.9/site-packages/ray/tune/trainable/trainable.py", line 384, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 336, in entrypoint
    return self._trainable_func(
  File "/opt/conda/lib/python3.9/site-packages/ray/tune/trainable/function_trainable.py", line 653, in _trainable_func
    output = fn()
  File "/home/arun/ch/chemberta3/benchmarking/pretraining/pretrain_snap_node_level.py", line 43, in _train_snap
    train_loss = model.fit(train_ds, nb_epoch=config['num_epochs'])
  File "/home/arun/deepchem/deepchem/models/torch_models/torch_model.py", line 338, in fit
    return self.fit_generator(
  File "/home/arun/deepchem/deepchem/models/torch_models/modular.py", line 220, in fit_generator
    inputs, labels, weights = self._prepare_batch(batch)
  File "/home/arun/deepchem/deepchem/models/torch_models/gnn.py", line 770, in _prepare_batch
    sampled_g = [
  File "/home/arun/deepchem/deepchem/models/torch_models/gnn.py", line 771, in <listcomp>
    context_pred_sampler(graph, self.context_size,
  File "/home/arun/deepchem/deepchem/models/torch_models/gnn.py", line 1163, in context_pred_sampler
    context_G, context_node_map = data.subgraph(context_node_idxes)
  File "/home/arun/deepchem/deepchem/feat/graph_data.py", line 310, in subgraph
    subgraph_data = GraphData(node_features=subgraph_node_features,
  File "/home/arun/deepchem/deepchem/feat/graph_data.py", line 72, in __init__
    raise ValueError('The shape of edge_index is [2, num_edges].')
ValueError: The shape of edge_index is [2, num_edges].
```

Expected result: successful training of the model.

**Comment by quincylin1** [comment]
Hi @arunppsg thank you for spotting this. I took a look and I think the main issue is that we didn't cover the case where the `context_node_idxes` of the context graph is non-empty, but there's no edge between the context nodes in the input subgraph

**Comment by quincylin1** [comment]
If you look at  [`context_pred_sampler`](https://github.com/deepchem/deepchem/blob/master/deepchem/models/torch_models/gnn.py) in class `GNNModular`, you will see that `data.subgraph()` accepts a `context_node_idxes`, which is a set of context nodes lying between distance l1 and l2. What `subgraph()` does is that it tries to create a subgraph consisting of these context nodes by sampling nodes in the input graph (which is the entire graph (molecule)), see [here](https://github.com/deepchem/deepchem/blob/c2a368ee2423fb9c052c1e58f9aeef1db7f6aa2d/deepchem/feat/graph_data.py#L296).

The problem is that there are no edges between the context nodes, so it never passes the if statement in L302, and the `subgraph_edge_indices` and `subgraph_edge_features` remain an empty list. 

When you pass empty lists to L310, it raises the `ValueError` for the shape of the `edge_index`.

**Comment by quincylin1** [comment]
I printed out some of the intermediate results when reproducing the error. `src` and `dest` are the nodes for which an edge exist in the input graph, and nodes correspond to the context nodes in `context_node_idxes`. You can see that **both** the src and dest need to be in `nodes` in order for the subgraph to be created (which makes sense, since you can't create a subgraph from nodes which are not connected)

```
src: 16, dest: 0, nodes: {8, 2}
src: 0, dest: 16, nodes: {8, 2}
src: 0, dest: 12, nodes: {8, 2}
src: 12, dest: 0, nodes: {8, 2}
src: 12, dest: 22, nodes: {8, 2}
src: 22, dest: 12, nodes: {8, 2}
src: 22, dest: 24, nodes: {8, 2}
src: 24, dest: 22, nodes: {8, 2}
src: 22, dest: 4, nodes: {8, 2}
src: 4, dest: 22, nodes: {8, 2}
src: 4, dest: 10, nodes: {8, 2}
src: 10, dest: 4, nodes: {8, 2}
src: 10, dest: 13, nodes: {8, 2}
src: 13, dest: 10, nodes: {8, 2}
src: 13, dest: 23, nodes: {8, 2}
src: 23, dest: 13, nodes: {8, 2}
src: 23, dest: 8, nodes: {8, 2}
src: 8, dest: 23, nodes: {8, 2}
src: 8, dest: 7, nodes: {8, 2}
src: 7, dest: 8, nodes: {8, 2}
src: 7, dest: 19, nodes: {8, 2}
src: 19, dest: 7, nodes: {8, 2}
src: 19, dest: 18, nodes: {8, 2}
src: 18, dest: 19, nodes: {8, 2}
src: 19, dest: 14, nodes: {8, 2}
src: 14, dest: 19, nodes: {8, 2}
src: 14, dest: 2, nodes: {8, 2}
src: 2, dest: 14, nodes: {8, 2}
src: 2, dest: 11, nodes: {8, 2}
src: 11, dest: 2, nodes: {8, 2}
src: 11, dest: 21, nodes: {8, 2}
src: 21, dest: 11, nodes: {8, 2}
src: 10, dest: 9, nodes: {8, 2}
src: 9, dest: 10, nodes: {8, 2}
src: 9, dest: 3, nodes: {8, 2}
src: 3, dest: 9, nodes: {8, 2}
src: 3, dest: 6, nodes: {8, 2}
src: 6, dest: 3, nodes: {8, 2}
src: 6, dest: 5, nodes: {8, 2}
src: 5, dest: 6, nodes: {8, 2}
src: 5, dest: 20, nodes: {8, 2}
src: 20, dest: 5, nodes: {8, 2}
src: 20, dest: 17, nodes: {8, 2}
src: 17, dest: 20, nodes: {8, 2}
src: 20, dest: 15, nodes: {8, 2}
src: 15, dest: 20, nodes: {8, 2}
src: 15, dest: 1, nodes: {8, 2}
src: 1, dest: 15, nodes: {8, 2}
src: 5, dest: 0, nodes: {8, 2}
src: 0, dest: 5, nodes: {8, 2}
src: 9, dest: 0, nodes: {8, 2}
src: 0, dest: 9, nodes: {8, 2}
src: 11, dest: 4, nodes: {8, 2}
src: 4, dest: 11, nodes: {8, 2}
src: 11, dest: 8, nodes: {8, 2}
src: 8, dest: 11, nodes: {8, 2}
subgraph_edge_index: [], subgraph_edge_features: []
```

The error message reads:
```python
  File "/Users/linquincy/Downloads/deepchem/deepchem/feat/graph_data.py", line 72, in __init__
    raise ValueError(f'The shape of edge_index must be (2, num_edges), but got {edge_index.shape}')
ValueError: The shape of edge_index must be (2, num_edges), but got (0,)
```

The shape of the edge_index is `(0,)` due to the empty list issue mentioned above.
