### ISSUE TITLE
AttributeError: module 'scipy.stats' has no attribute 'gilbrat'

### ISSUE THREAD

**Issue by wasifferoze** [deepchem/deepchem#3808]
## To Reproduce

1. after installing through conda
2. import deepchem as dc
3. it will produce this error

> >>> import deepchem as dc
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\__init__.py", line 8, in <module>
>     import deepchem.data
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\data\__init__.py", line 16, in <module>
>     from deepchem.data.data_loader import DataLoader
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\data\data_loader.py", line 17, in <module>
>     from deepchem.feat import UserDefinedFeaturizer, Featurizer
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\__init__.py", line 21, in <module>
>     from deepchem.feat.molecule_featurizers import AtomicCoordinates
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\molecule_featurizers\__init__.py", line 22, in <module>
>     from deepchem.feat.molecule_featurizers.dmpnn_featurizer import DMPNNFeaturizer
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\molecule_featurizers\dmpnn_featurizer.py", line 24, in <module>
>     class GraphConvConstants(object):
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\molecule_featurizers\dmpnn_featurizer.py", line 57, in GraphConvConstants
>     RDKitDescriptors(use_bcut2d=False, is_normalized=True)
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\molecule_featurizers\rdkit_descriptors.py", line 113, in __init__
>     self._make_normalised_func_dict()
>   File "C:\Users\anaconda3\envs\deepchem\lib\site-packages\deepchem\feat\molecule_featurizers\rdkit_descriptors.py", line 216, in _make_normalised_func_dict
>     cont_distribution: rv_continuous = getattr(st, distribution_name)
> AttributeError: module 'scipy.stats' has no attribute 'gilbrat'

## Expected behavior
It should import the library

## Environment

* OS: Windows
* Python version: 3.9.18
* DeepChem version: 2.7.1
* RDKit version (optional):  2022.03.5
* TensorFlow version (optional):
* PyTorch version (optional):
* Any other relevant information:

**Comment by wasifferoze** [comment]
install from source using this command
```shell
pip install git+https://github.com/deepchem/deepchem.git
```

**Comment by wasifferoze** [comment]
I may close this, if there is no better solution.
