### ISSUE TITLE
Installation process from Contribution guide

### ISSUE THREAD

**Issue by AlessioBray** [deepchem/deepchem#3864]
## 📚 Installation

Following the tutorial to start contributing I obtain the following error (additionally to a deprecation warning for easy_install). I am suggesting to update the Contribution guide with the nightly build installation `pip install --pre deepchem` command as in the README.

```
Searching for scipy>=1.10.1
Reading https://pypi.org/simple/scipy/
Downloading https://files.pythonhosted.org/packages/30/85/cdbf2c3c460fe5aae812917866392068a88d02f07de0fe31ce738734c477/scipy-1.12.0.tar.gz#sha256=4bf5abab8a36d20193c698b0f1fc282c1d083c94723902c447e5d2f1780936a3
Best match: scipy 1.12.0
Processing scipy-1.12.0.tar.gz
error: Couldn't find a setup script in /tmp/easy_install-x_acmnt7/scipy-1.12.0.tar.gz 
```

## Environment

* OS: Ubuntu 22.04.3 LTS
* Package manager (PyPI or Conda): Conda 23.7.4
* Python version: 3.8
* DeepChem version: 2.7.2.dev
* TensorFlow version: 2.13.1
* PyTorch version (optional):
* CUDA/cuDNN version (optional):
* Any other relevant information:

## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [ ] I used Google Colab.
- [ ] I do have multiple CUDA versions on my machine.

##Additional context

Everything works fine with Python 3.10.13

**Comment by archit-spec** [comment]
i have the same problem

**Comment by archit-spec** [comment]
There  [#2631](https://github.com/deepchem/deepchem/issues/2631) is a solution here that worked for me but then 
i got this 
```
Downloading https://files.pythonhosted.org/packages/da/b4/5d7b9f64d2c3795ac37da3d8bc303be7950e575ec21ac7d0eb9de34fe0d5/scikit-learn-1.4.1.post1.tar.gz#sha256=93d3d496ff1965470f9977d05e5ec3376fb1e63b10e4fda5e39d23c2d8969a30
Best match: scikit-learn 1.4.1.post1
Processing scikit-learn-1.4.1.post1.tar.gz
Writing /tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/setup.cfg
Running scikit-learn-1.4.1.post1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/egg-dist-tmp-270wvnk1
Partial import of sklearn during the build process.
Traceback (most recent call last):
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/setup.py", line 645, in <module>
  File "/tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/setup.py", line 629, in setup_package
RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/dumball/anaconda3/envs/deepchem/bin/python.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 41, in <module>
    setup(name='deepchem',
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
    return distutils.core.setup(**attrs)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/dist.py", line 989, in run_command
    super().run_command(command)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/develop.py", line 124, in install_for_development
    self.process_distribution(None, self.dist, not self.no_deps)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 788, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1147, in obtain
    return installer(requirement)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 713, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 932, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1206, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1192, in run_setup
    run_setup(setup_script, args)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dumball/anaconda3/envs/deepchem/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/setup.py", line 645, in <module>
  File "/tmp/easy_install-cm4n829_/scikit-learn-1.4.1.post1/setup.py", line 629, in setup_package
RuntimeError: Scikit-learn requires Python 3.9 or later. The current Python version is 3.8.18 installed in /home/dumball/anaconda3/envs/deepchem/bin/python.
```

the python 3.8 version is not compatible with the scikit-learn package

**Comment by AlessioBray** [comment]
Sure, @GreatRSingh I think the [contribution guide](https://github.com/deepchem/deepchem/blob/master/CONTRIBUTING.md) should be updated since in the steps it is suggesting to create a conda environment with python 3.8
