### ISSUE TITLE
Unrecognized keyword arguments passed to BatchNormalization

### ISSUE THREAD

**Issue by osangma** [deepchem/deepchem#4034]
## Environment

* OS: MacOS 
* Python version: 3.11
* DeepChem version: 2.8.0
* RDKit version (optional): 2024.3.1
* TensorFlow version (optional): 2.16.2
* PyTorch version (optional):

## Additional context

>>> tasks, datasets, transformers = dc.molnet.load_tox21(featurizer='GraphConv')
>>> train_dataset, valid_dataset, test_dataset = datasets
>>> n_tasks = len(tasks)
>>> model = dc.models.GraphConvModel(n_tasks, mode='classification')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Volumes/sandisk/anaconda3/envs/deepchem/lib/python3.11/site-packages/deepchem/models/graph_models.py", line 973, in __init__
    model = _GraphConvKerasModel(n_tasks,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/sandisk/anaconda3/envs/deepchem/lib/python3.11/site-packages/deepchem/models/graph_models.py", line 839, in __init__
    self.batch_norms = [
                       ^
  File "/Volumes/sandisk/anaconda3/envs/deepchem/lib/python3.11/site-packages/deepchem/models/graph_models.py", line 840, in <listcomp>
    BatchNormalization(fused=False) if batch_normalize else None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/sandisk/anaconda3/envs/deepchem/lib/python3.11/site-packages/keras/src/layers/normalization/batch_normalization.py", line 143, in __init__
    super().__init__(**kwargs)
  File "/Volumes/sandisk/anaconda3/envs/deepchem/lib/python3.11/site-packages/keras/src/layers/layer.py", line 266, in __init__
    raise ValueError(
ValueError: Unrecognized keyword arguments passed to BatchNormalization: {'fused': False}

**Comment by 1355wss** [comment]
You can add a parameter named batch_normalize = False to GraphConvModel()
`model = dc.models.GraphConvModel(1, mode='regression',dropout=0.5,batch_normalize=False)`
