### ISSUE TITLE
unrecognized keyword arguments passed to BatchNormalization

### ISSUE THREAD

**Issue by bhuvanmdev** [deepchem/deepchem#4196]
## To Reproduce

1. git clone deepchem
2. pip install .[tensorflow]
3.
 ```python
from deepchem.models import WeaveModel
model = WeaveModel(mode='classification', n_tasks=1, batch_size=32, learning_rate=1e-1, dropout=0.05)
```

Error Message:
```python
Traceback (most recent call last):
  File "E:\deepchem\temp.py", line 2, in <module>
    model = WeaveModel(mode='classification', n_tasks=1, batch_size=32, learning_rate=1e-1, dropout=0.05)
  File "E:\deepchem\deepchem\models\graph_models.py", line 229, in __init__
    weave_layer_ind_A, weave_layer_ind_P = layers.WeaveLayer(
  File "E:\deepchem\.venv\lib\site-packages\keras\src\utils\traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "E:\deepchem\deepchem\models\layers.py", line 2841, in build
    self.AA_bn = BatchNormalization(**self.batch_normalize_kwargs)
ValueError: Unrecognized keyword arguments passed to BatchNormalization: {'renorm': True}
```

Note:- We get this error irrespective of the value of batch_normalize(True/False)

## Expected behavior

For the model to get initialized without any issue.

## Environment

* OS: Windows 11
* Python version: python 3.10.11
* Keras: 3.7.0
* DeepChem version: 2.8.1.dev
* TensorFlow version : 2.18.0

**Comment by Freshcoder-04** [comment]
Hi @bhuvanmdev , I would like to work on this issue.  Can you assign this to me please?

**Comment by Freshcoder-04** [comment]
> Hi @bhuvanmdev , I would like to work on this issue. Can you assign this to me please?

Hi, after reviewing the issue, I've learnt that in keras 3.0, keyword renorm has been removed from BatchNormalization. So we can either avoid renorm altogether or we can implement a custom renormalisation.

Let me know what to implement.

**Comment by krtimisra67** [comment]
Option 1: Use an Older Version of TensorFlow & Keras

Since DeepChem 2.7.2 is quite old, it might not be compatible with the latest TensorFlow/Keras versions. Try installing TensorFlow 2.4 and Keras 2.4:

pip install tensorflow==2.4 keras==2.4

Then, retry running your script.
Option 2: Manually Edit DeepChem's Source Code

If downgrading is not an option, you can manually edit the DeepChem code to remove the renorm=True argument:

    Open deepchem/models/layers.py.
    Find the WeaveLayer class and locate this line:

self.AA_bn = BatchNormalization(**self.batch_normalize_kwargs)

If batch_normalize_kwargs contains renorm=True, remove it:

    self.AA_bn = BatchNormalization()

    Save and retry.

Option 3: Upgrade DeepChem

If possible, upgrade DeepChem to the latest version that supports TensorFlow 2.10+:

pip install --upgrade deepchem
