### ISSUE TITLE
PDBBind Dataset Load Error

### ISSUE THREAD

**Issue by thomasklau** [deepchem/deepchem#562]
Hi,

I'm importing the script from examples/pdbbind/pdbbind_datasets.py and when I run:

dataset, tasks = pdbbind_datasets.featurize_pdbbind(feat="grid", subset="full")

I am getting the following error, multiple times (all on HIS residues). Is there a change I can make such that I don't keep getting this error?

--- Logging error ---
Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 54, in add_hydrogens_to_mol
    fixer.addMissingHydrogens(7.4)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
    modeller.addHydrogens(pH=pH)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 735, in addHydrogens
    raise ValueError('HIS residue (%d) has the wrong set of atoms' % residue.index)
ValueError: HIS residue (0) has the wrong set of atoms

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2683, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2787, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2847, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6d9aa26a6893>", line 1, in <module>
    dataset, tasks = pdbbind_datasets.featurize_pdbbind(feat="grid", subset="full16")
  File "/home/thomas/deepchem/examples/pdbbind/pdbbind_datasets.py", line 106, in featurize_pdbbind
    p = Pool(multiprocessing.cpu_count())
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 168, in __init__
    self._repopulate_pool()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 233, in _repopulate_pool
    w.start()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/context.py", line 267, in _Popen
    return Popen(process_obj)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/thomas/deepchem/examples/pdbbind/pdbbind_datasets.py", line 184, in compute_single_pdbbind_feature
    pdb_code)
  File "/home/thomas/deepchem/examples/pdbbind/pdbbind_datasets.py", line 199, in compute_pdbbind_features
    features = grid_featurizer.featurize_complexes([ligand_file], [protein_file])
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 747, in featurize_complexes
    protein_pdb_lines)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 722, in _featurize_complex
    features_dict = self._transform(protein_pdb_file, ligand_file)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 772, in _transform
    protein_pdb, calc_charges=True)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 117, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 62, in add_hydrogens_to_mol
    logging.warning("Unable to add hydrogens", e)
Message: 'Unable to add hydrogens'
Arguments: (ValueError('HIS residue (0) has the wrong set of atoms',),)
WARNING:root:Unable to compute features for (929, '4kw6', '/home/thomas/deepchem/examples/pdbbind/v2016', <deepchem.feat.rdkit_grid_featurizer.RdkitGridFeaturizer object at 0x7f2b261b1fd0>)

**Comment by thomasklau** [comment]
I tried to change to code to use rdkit's addHs, but to no success:
http://www.rdkit.org/docs/GettingStartedInPython.html

****
Pre-condition Violation
getNumImplicitHs() called without preceding call to calcImplicitValence()
Violation occurred on line 176 in file /scratch/RDKit_git/Code/GraphMol/Atom.cpp
Failed Expression: d_implicitValence>-1
****

**Comment by peastman** [comment]
This probably means the input file has nonstandard atom names.  It expects a HIS residue to have atoms named ND1 and NE2.  If it doesn't find those, it throws an exception.

**Comment by thomasklau** [comment]
Thanks! Would it be egregious to do:

nd1 = [atom for atom in residue.atoms() if atom.name == 'ND1']
ne2 = [atom for atom in residue.atoms() if atom.name == 'NE2']
if len(nd1) != 1 or len(ne2) != 1:
  continue #<-Added this
  raise ValueError('HIS residue (%d) has the wrong set of atoms' % residue.index)

so that I get more training data? PDBBind is curated, so I'm assuming that the PDB structures in there are correct.

**Comment by peastman** [comment]
That wouldn't work.  It's not looking up those atoms to be arbitrary.  It needs to know which atoms the hydrogens should be added to.  It identifies them by name.  If there are no atoms with those names, it has no idea which are the correct atoms.

**Comment by levipierce** [comment]
Running prepwizard on the structures that are missing side chain atoms before processing using the option -fillsidechains resolves the issue.  Maybe there is some code in openmm that will do this as well...

$SCHRODINGER/utilities/prepwizard -fillsidechains 2aac_protein.pdb 2aac_protein_prep.pdb

**Comment by cxhernandez** [comment]
>Maybe there is some code in openmm that will do this as well...

[PDBFixer](https://github.com/pandegroup/pdbfixer) might be of interest

**Comment by thomasklau** [comment]
I believe that it is PDBFixer is already being called - correct me if I'm wrong though.

**Comment by cxhernandez** [comment]
True, the first part of that traceback seems to be an error with PDBFixer:

```
File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 54, in add_hydrogens_to_mol
fixer.addMissingHydrogens(7.4)
File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/pdbfixer/pdbfixer.py", line 1019, in addMissingHydrogens
modeller.addHydrogens(pH=pH)
File "/home/thomas/miniconda3/envs/deepchem/lib/python3.5/site-packages/simtk/openmm/app/modeller.py", line 735, in addHydrogens
raise ValueError('HIS residue (%d) has the wrong set of atoms' % residue.index)
ValueError: HIS residue (0) has the wrong set of atoms
```

Are you sure that the HIS residue is complete (as @levipierce hinted)? Could you try using [`fixer.findMissingAtoms` and  `fixer.addMissingAtoms`](https://github.com/pandegroup/pdbfixer/blob/ea4bb1c86c054c18ad2e4b41f3d5384c1c5ff535/pdbfixer/pdbfixer.py#L796-L960)?

**Comment by levipierce** [comment]
Yeah I will give it a shot, this is the problematic residue...
ATOM   1553  N   HIS A 105      17.121  24.927  51.965  1.00 11.68           N  
ATOM   1554  H   HIS A 105      16.611  24.022  52.011  1.00  0.00           H  
ATOM   1555  CA  HIS A 105      16.810  25.966  52.962  1.00 14.71           C  
ATOM   1556  HA  HIS A 105      16.278  26.722  52.384  1.00  0.00           H  
ATOM   1557  C   HIS A 105      17.993  26.712  53.559  1.00 11.38           C  
ATOM   1558  O   HIS A 105      17.990  27.948  53.603  1.00 13.03           O  
ATOM   1559  CB  HIS A 105      15.914  25.405  54.082  1.00 15.98           C  
ATOM   1560  HB1 HIS A 105      14.981  25.042  53.651  1.00  0.00           H  
ATOM   1561  HB2 HIS A 105      16.429  24.584  54.581  1.00  0.00           H

**Comment by thomasklau** [comment]
I just ended up running prepwizard on all of the structures in PDBBind first before running the script.

**Comment by thomasklau** [comment]
The issue with PSBFixer was affecting about 1000 structures in the dataset for me. I'm running it on the newer 2016 full version.

**Comment by levipierce** [comment]
Had to add three lines to rdkit_util.py

    fixer.findMissingResidues()                                                 
    fixer.findMissingAtoms()                                                    
    fixer.addMissingAtoms()  

problem solved...all with open source code...beautiful.

**Comment by cxhernandez** [comment]
Great to hear!

**Comment by rbharath** [comment]
@levipierce The fix sounds like it would be a great PR :-)

**Comment by thomasklau** [comment]
Since you're running the PDB grid featurizer code, I think it would be helpful to say that I found a bug that occurs when hashing ECFP pairs. The string needed to be converted to unicode first. I fixed it to be:

def hash_ecfp_pair(ecfp_pair, power):
  """
  Returns an int of size 2^power representing that
  ECFP pair. Input must be a tuple of strings.
  """
  ecfp = "%s,%s" % (ecfp_pair[0], ecfp_pair[1])
  ecfp = ecfp.encode('utf-8')
  md5 = hashlib.md5()
  md5.update(ecfp)
  digest = md5.hexdigest()
  ecfp_hash = int(digest, 16) % (2**power)
  return (ecfp_hash)

I believe that this makes the code simply not add the ECFP features to the grid.

**Comment by mwojcikowski** [comment]
Wouldn't it be better if we use much simpler hashing function, which should also be ~1-2 orders of magnitude faster:
```
def hash32(value):
    """Platform independend 32bit hashing method"""
    return hash(value) & 0xffffffff
```
I successfully use thish hashing in the ECFP implementation in [ODDT](https://github.com/oddt/oddt/blob/master/oddt/fingerprints.py#L202)

**Comment by rbharath** [comment]
@thomasklau Good find! Would you mind putting together a PR with the fix?

@mwojcikowski Is the hashing the rate limiting step in the grid featurization? If so, a simpler hash would be a good improvement.

**Comment by levipierce** [comment]
I am going to file a separate bug about the hashing and a PR for it as well...

https://github.com/deepchem/deepchem/issues/593

**Comment by rbharath** [comment]
I believe the issues raised her are fixed so going to close this old issue.
