### ISSUE TITLE
Install Fails on Ubuntu 16.04 Server due to libxrender missing

### ISSUE THREAD

**Issue by LRParser** [deepchem/deepchem#613]
The installation of deepchem fails with the following error on Ubuntu 16.04 server with Anaconda 3.6 installed:

```
running install_egg_info
Copying deepchem.egg-info to /home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem-1.1.1.dev155-py3.5.egg-info
running install_scripts
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/multiprocessing/util.py", line 254, in _run_finalizers
    finalizer()
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/shutil.py", line 471, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/shutil.py", line 469, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/easy_install-lxo1dgyd/pbr-3.1.1/temp/pymp-fnhs7bda'
Failure: ImportError (libXrender.so.1: cannot open shared object file: No such file or directory) ... ERROR

======================================================================
ERROR: Failure: ImportError (libXrender.so.1: cannot open shared object file: No such file or directory)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/ubuntu/deepchem/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/home/ubuntu/deepchem/deepchem/data/__init__.py", line 9, in <module>
    from deepchem.data.datasets import pad_features
  File "/home/ubuntu/deepchem/deepchem/data/datasets.py", line 11, in <module>
    from deepchem.utils.save import save_to_disk
  File "/home/ubuntu/deepchem/deepchem/utils/__init__.py", line 14, in <module>
    from rdkit import Chem
  File "/home/ubuntu/anaconda3/envs/deepchem/lib/python3.5/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: libXrender.so.1: cannot open shared object file: No such file or directory
```

This appears to be fixed via running:

```
sudo apt-get install -y libxrender-dev
```

**Comment by rbharath** [comment]
I believe this was fixed by @LRParser's recent PR

**Comment by xingyafeng** [comment]
sudo apt-get install libxrender1:i386
sudo apt-get install libxrender1
