### ISSUE TITLE
Multi-Task Regression [Tensorgraph]

### ISSUE THREAD

**Issue by patrickhop** [deepchem/deepchem#625]
Tensorgraph multi-task regression does not seem to work for the regression case:

```
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals

import numpy as np
np.random.seed(123)
import tensorflow as tf
tf.set_random_seed(123)
import deepchem as dc

# Load tox21 dataset
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_hopv(
    featurizer='Weave', split='index')
train_dataset, valid_dataset, test_dataset = tox21_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

n_atom_feat = 75
n_pair_feat = 14
# Batch size of models
batch_size = 64
n_feat = 128

model = dc.models.WeaveTensorGraph(
    len(tox21_tasks),
    batch_size=batch_size,
    learning_rate=1e-3,
    use_queue=False,
    mode='regression')

# Fit trained model
model.fit(train_dataset, nb_epoch=50)
print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)
```

```
  DeprecationWarning)
About to featurize HOPV dataset.
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
Traceback (most recent call last):
  File "tox21_tensorgraph_weave.py", line 36, in <module>
    model.fit(train_dataset, nb_epoch=50)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 121, in fit
    max_checkpoints_to_keep, checkpoint_interval)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 138, in fit_generator
    self.build()
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/models/tensorgraph/tensor_graph.py", line 330, in build
    node_layer.create_tensor(training=self._training_placeholder)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/models/tensorgraph/layers.py", line 520, in create_tensor
    out_tensor = tf.concat(inputs, axis=self.axis)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1034, in concat
    name=name)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 519, in _concat_v2
    name=name)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2329, in create_op
    set_shapes_for_outputs(ret)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1717, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1667, in call_with_requiring
    return call_cpp_shape_fn(op, require_shape_fn=True)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 610, in call_cpp_shape_fn
    debug_python_shape_fn, require_shape_fn)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 676, in _call_cpp_shape_fn_impl
    raise ValueError(err.message)
ValueError: Shape must be at least rank 2 but is rank 1 for 'Concat_22/concat' (op: 'ConcatV2') with input shapes: [?], [?], [?], [?], [?], [?], [?], [?], [].
```

**Comment by lilleswing** [comment]
Weave was concatonating on axis=1 over [[?], [?],[?]] -- fixed in 
https://github.com/deepchem/deepchem/pull/636

**Comment by rbharath** [comment]
@patrickhop Can you check out HEAD and see if bug is fixed?

**Comment by patrickhop** [comment]
@rbharath Rerun results:
```
"""
Script that trains weave models on tox21 dataset.
"""
from __future__ import print_function
from __future__ import division
from __future__ import unicode_literals

import numpy as np
np.random.seed(123)
import tensorflow as tf
tf.set_random_seed(123)
import deepchem as dc

# Load tox21 dataset
hopv_tasks, hopv_datasets, transformers = dc.molnet.load_hopv(
    featurizer='Weave', split='index')
train_dataset, valid_dataset, test_dataset = hopv_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, task_averager=np.mean)

n_atom_feat = 75
n_pair_feat = 14
# Batch size of models
batch_size = 64
n_feat = 128

model = dc.models.WeaveTensorGraph(
    len(hopv_tasks),
    batch_size=batch_size,
    learning_rate=1e-3,
    use_queue=False,
    mode='regression')

# Fit trained model
model.fit(train_dataset, nb_epoch=2)
print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

print("Train scores")
print(train_scores)

print("Validation scores")
print(valid_scores)
```

```
Warning: No xgboost installed on your system
Attempting to run %s will throw runtime errors
Warning: No pdbfixer installed on your system
Attempting to run %s will throw runtime errors
Warning: No simtk installed on your system
Attempting to run %s will throw runtime errors
About to featurize HOPV dataset.
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE3 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
Ending global_step 10: Average loss 4.81837e+06
TIMING: model fitting took 6.780 s
Evaluating model
Traceback (most recent call last):
  File "tox21_tensorgraph_weave.py", line 38, in <module>
    train_scores = model.evaluate(train_dataset, [metric], transformers)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/models/models.py", line 192, in evaluate
    scores = evaluator.compute_model_performance(metrics)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/utils/evaluate.py", line 122, in compute_model_performance
    y, y_pred, w, per_task_metrics=False)
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/deepchem/metrics/__init__.py", line 212, in compute_metric
    y_pred = np.reshape(y_pred, (n_samples, n_tasks, n_classes))
  File "/home/ubuntu/miniconda2/lib/python2.7/site-packages/numpy/core/fromnumeric.py", line 224, in reshape
    return reshape(newshape, order=order)
ValueError: total size of new array must be unchanged
```

**Comment by lilleswing** [comment]
The other half of the fixes are in here -- we needed to get more explicit about what shapes we need out of the labels in predictor_generator.
https://github.com/deepchem/deepchem/pull/642

**Comment by rbharath** [comment]
@patrickhop Give it one more try now #642 is merged in? :-)

**Comment by patrickhop** [comment]
This is resolved now in a new PR. Closing.
