### ISSUE TITLE
error running pdbbind_rf.py

### ISSUE THREAD

**Issue by pincher-chen** [deepchem/deepchem#660]
I get pdbbind_v2015.tar.gz by get_pdbbind.sh, when i run pdbbind_rf.py error occured:

```
$ python pdbbind_rf.py 
~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /usr/local/cuda/lib64:~/sf_install/mongo-c-driver/lib:~/sf_install/mayachemtools/lib::/lib64:/lib:/usr/lib:/usr/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
About to load contents.
Processing 3zzf
Processing 3gww
Processing 1w8l
Processing 3fqa
Processing 1zsb
Processing 4obv
Processing 1wkm
Processing 3k41
Processing 4eu3
Processing 2w97
Processing 1p0y
Processing 2b1r
Processing 2d2v
Processing 2a31
Processing 1aw1
Processing 1maw
Processing 3fl9
Processing 4lh2
Processing 4to8
Processing 4fci
Processing 4fck
Processing 4clp
Processing 1f9g
Processing 1a0t
Processing 1b74
Processing 2fah
Processing 2igw
Processing 2vl1
Processing 3nm6
Processing 1qpb
Processing 1hty
Processing 1o4l
Processing 1o4m
Processing 1o4n
Processing 2hdq
Processing 3eor
Processing 3e81
Processing 1ozv
Processing 1utp
Processing 1tnk
Processing 4bh4
Processing 4lh3
Processing 3mwe
Processing 4amw
Processing 1iig
Processing 3rup
Processing 2b1q
Processing 1w8m
Processing 3itc
Processing 2it4
Processing 1a7t
Processing 1hgj
Processing 1rdj
Processing 2o9r
Processing 4qsw
Processing 1d2v
Traceback (most recent call last):
  File "pdbbind_rf.py", line 24, in <module>
    split=split, subset=subset)
  File "~/deepchem/examples/pdbbind/pdbbind_datasets.py", line 191, in load_pdbbind_grid
    dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
  File "~/deepchem/examples/pdbbind/pdbbind_datasets.py", line 90, in featurize_pdbbind
    dataset = compute_atomic_conv_features(tasks, data_dir, pdbbind_dir, y, ids)
  File "~/deepchem/examples/pdbbind/pdbbind_datasets.py", line 158, in compute_atomic_conv_features
    shard_generator(), data_dir=data_dir, tasks=tasks)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 440, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "~/deepchem/examples/pdbbind/pdbbind_datasets.py", line 145, in shard_generator
    str(ligand_file), str(protein_file))
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 209, in _featurize_complex
    frag1_coords, frag1_mol = rdkit_util.load_molecule(mol_pdb_file)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 105, in load_molecule
    suppl = Chem.SDMolSupplier(str(molecule_file), sanitize=False)
OSError: File error: Bad input file ~/deepchem/examples/pdbbind/v2015/1d2v/1d2v_ligand.sdf
```
I found no 1d2v in v2015  folder. I tried to delete 1d2v in  v2015/INDEX_general_PL_data.2015, the computing can continue, but another error occured:
```
Processing 1p17
Processing 2a3a
Processing 2rib
Processing 2w6z
[18:03:58] Can't kekulize mol.  Unkekulized atoms: 5 6 8 13 14

--- Logging error ---
Traceback (most recent call last):
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 49, in add_hydrogens_to_mol
    pdbblock = Chem.MolToPDBBlock(mol)
ValueError: Sanitization error: Can't kekulize mol.  Unkekulized atoms: 5 6 8 13 14


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 981, in emit
    msg = self.format(record)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 831, in format
    return fmt.format(record)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 568, in format
    record.message = record.getMessage()
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/logging/__init__.py", line 331, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "pdbbind_rf.py", line 24, in <module>
    split=split, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 191, in load_pdbbind_grid
    dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 90, in featurize_pdbbind
    dataset = compute_atomic_conv_features(tasks, data_dir, pdbbind_dir, y, ids)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 158, in compute_atomic_conv_features
    shard_generator(), data_dir=data_dir, tasks=tasks)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 440, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 145, in shard_generator
    str(ligand_file), str(protein_file))
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 209, in _featurize_complex
    frag1_coords, frag1_mol = rdkit_util.load_molecule(mol_pdb_file)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 121, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 66, in add_hydrogens_to_mol
    logging.warning("Unable to add hydrogens", e)
Message: 'Unable to add hydrogens'
Arguments: (ValueError("Sanitization error: Can't kekulize mol.  Unkekulized atoms: 5 6 8 13 14\n",),)
Traceback (most recent call last):
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 49, in add_hydrogens_to_mol
    pdbblock = Chem.MolToPDBBlock(mol)
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pdbbind_rf.py", line 24, in <module>
    split=split, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 191, in load_pdbbind_grid
    dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 90, in featurize_pdbbind
    dataset = compute_atomic_conv_features(tasks, data_dir, pdbbind_dir, y, ids)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 158, in compute_atomic_conv_features
    shard_generator(), data_dir=data_dir, tasks=tasks)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 440, in create_dataset
    for shard_num, (X, y, w, ids) in enumerate(shard_generator):
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 145, in shard_generator
    str(ligand_file), str(protein_file))
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/atomic_coordinates.py", line 209, in _featurize_complex
    frag1_coords, frag1_mol = rdkit_util.load_molecule(mol_pdb_file)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 121, in load_molecule
    my_mol = add_hydrogens_to_mol(my_mol)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/rdkit_util.py", line 67, in add_hydrogens_to_mol
    raise MoleculeLoadException(e)
deepchem.utils.rdkit_util.MoleculeLoadException
```
How can run this examples successfully?

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/661

**Comment by pincher-chen** [comment]
I have found pdbbind_datasets.py file that has been modified. I test but error still happened.
```
$ python pdbbind_rf.py 
~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcublas.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:126] Couldn't open CUDA library libcudnn.so.5. LD_LIBRARY_PATH: /usr/local/cuda/lib64:/usr/local/cuda/lib:/WORK/app/boost/1_41_0/lib:/WORK/app/CUDA/8.0/libnvvp:/WORK/app/CUDA/8.0/libnsight:/WORK/app/CUDA/8.0/lib64:/WORK/app/CUDA/8.0/lib:/WORK/app/Python/2.7.9-fPIC/lib:/WORK/app/Openbabel/2.3.2-python/lib::/lib64:/lib:/usr/lib:/usr/lib64
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3517] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcufft.so.8.0 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
About to load contents.
Processing complex 0, 3zzf
Processing complex 150, 2igv
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 300, 4b3d
Processing complex 450, 3ckb
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 600, 3ad8
Featurizing 0 / 1
Processing complex 750, 4gwk
Processing complex 900, 3tf7
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 1050, 4ibd
Featurizing 0 / 1
Processing complex 1350, 3c39
Processing complex 1200, 4q9s
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 1500, 2vtd
Processing complex 1650, 3avl
Processing complex 1800, 4cqf
Featurizing 0 / 1
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 1950, 3uxd
Processing complex 2100, 3aas
Processing complex 2250, 3msk
Featurizing 0 / 1
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 2400, 2uy4
Processing complex 2550, 3atl
Processing complex 2700, 4uof
Featurizing 0 / 1
Featurizing 0 / 1
Featurizing 0 / 1
Processing complex 2850, 2gss
Featurizing 0 / 1
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.001 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.002 s
TIMING: Writing protein took 0.003 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.002 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.003 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.002 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.006 s
TIMING: Writing protein took 0.004 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.003 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.002 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.004 s
TIMING: Writing protein took 0.003 s
TIMING: Writing protein took 0.004 s
TIMING: Writing protein took 0.003 s
TIMING: Writing protein took 0.003 s
TIMING: Writing protein took 0.004 s
TIMING: Writing protein took 0.005 s
TIMING: Writing protein took 0.003 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.011 s
TIMING: Writing protein took 0.018 s
TIMING: Loading protein coordinates took 2.977 s
TIMING: Loading ligand coordinates took 0.069 s
TIMING: Centroid processing took 0.001 s
TIMING: ecfp voxel computataion took 0.125 s
TIMING: splif voxel computataion took 0.164 s
TIMING: hbond voxel computataion took 0.140 s
TIMING: salt_bridge voxel computataion took 0.034 s
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/HOME/nscc-gz_pinchen/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 169, in compute_single_pdbbind_feature
    pdb_code)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 183, in compute_pdbbind_features
    features = grid_featurizer.featurize_complexes([ligand_file], [protein_file])
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 747, in featurize_complexes
    protein_pdb_lines)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 722, in _featurize_complex
    features_dict = self._transform(protein_pdb_file, ligand_file)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 948, in _transform
    channel_power=self.ecfp_power)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/feat/rdkit_grid_featurizer.py", line 1103, in _voxelize
    dtype=np.int8)
TypeError: 'float' object cannot be interpreted as an integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 174, in compute_single_pdbbind_feature
    logging.warning("Unable to compute features for %s" % x)
TypeError: not all arguments converted during string formatting
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pdbbind_rf.py", line 24, in <module>
Processing complex 3000, 4mw7
Featurizing 0 / 1
    split=split, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 190, in load_pdbbind_grid
    dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
  File "~/code/deepchem/examples/pdbbind/pdbbind_datasets.py", line 103, in featurize_pdbbind
    results = p.map(compute_single_pdbbind_feature, args)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
TypeError: not all arguments converted during string formatting
TIMING: Writing ligand took 0.000 s
TIMING: Writing protein took 0.006 s
```

**Comment by pincher-chen** [comment]
I try to change "subset = "core"" in pdbbind_rf.py,  and  data processing can be done successfully, but error happened:
```
$ python pdbbind_rf.py
....
I tensorflow/stream_executor/dso_loader.cc:135] successfully opened CUDA library libcurand.so.8.0 locally
About to load contents.
Processing 3ao4
Processing 3i3b
Processing 1uto
Processing 1ps3
Processing 1qi0
Processing 3g2z
Processing 3dxg
...
Processing 4djr
TIMING: dataset construction took 215.254 s
Loading dataset from disk.
TIMING: dataset construction took 8.144 s
Loading dataset from disk.
TIMING: dataset construction took 3.531 s
Loading dataset from disk.
TIMING: dataset construction took 3.574 s
Loading dataset from disk.
Fitting model on train dataset
Traceback (most recent call last):
  File "pdbbind_rf.py", line 38, in <module>
    model.fit(train_dataset)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/models/sklearn_models/__init__.py", line 31, in fit
    self.model_instance.fit(X, y, w)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/ensemble/forest.py", line 247, in fit
    X = check_array(X, accept_sparse="csc", dtype=DTYPE)
  File "~/sf_install/miniconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/utils/validation.py", line 382, in check_array
    array = np.array(array, dtype=dtype, order=order, copy=copy)
ValueError: setting an array element with a sequence.
```

**Comment by lilleswing** [comment]
@pincher-chen repull from master -- the featurizer for rf_pdbbind is "grid".  

You can get the pre-featurized cocrystalized complexes for python 2.7 via
``` bash
cd examples/pdbbind
bash get_featurized_pdbbind.sh
```
If you want to featurize it yourself (be carefull it takes ~ 15 seconds per complex per cpu core) you will need this PR which updates the error handling
https://github.com/deepchem/deepchem/pull/665

**Comment by rbharath** [comment]
Going to close since I think this is now fixed.
