### ISSUE TITLE
TicTacToe Index Error

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#734]
On the TicTacToe example, I sporadically see the following `IndexError` from some of the workers. It appears harmless (training continues), but might be nice to fix if we can:

```
Traceback (most recent call last):
  File "/home/rbharath/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/rbharath/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/rbharath/dlwithtf/ch8/a3c.py", line 184, in <lambda>
    target=lambda: worker.run(step_count, total_steps))
  File "/home/rbharath/dlwithtf/ch8/a3c.py", line 341, in run
    states, actions, rewards, values = self.create_rollout()
  File "/home/rbharath/dlwithtf/ch8/a3c.py", line 372, in create_rollout
    rewards.append(self.env.step(action))
  File "/home/rbharath/dlwithtf/ch8/environment.py", line 57, in step
    move = self.get_O_move()
  File "/home/rbharath/dlwithtf/ch8/environment.py", line 76, in get_O_move
    return random.choice(empty_squares)
  File "/home/rbharath/anaconda2/lib/python2.7/random.py", line 275, in choice
    return seq[int(self.random() * len(seq))]  # raises IndexError if seq is empty
IndexError: list index out of range
```

**Comment by lilleswing** [comment]
What code are you using to get this?  Is it my tictactoe.py in contrib/rl?

What frequency are you hitting this?  I can't seem to get it.

**Comment by rbharath** [comment]
This is `contrib/rl/tictactoe.py`. I don't see it that often, once every few runs (perhaps once every few million steps). Appears to be hit if there are no empty squares?

**Comment by rbharath** [comment]
I'm going to close this old issue since we don't use tic-tac-toe as an example for anything.
