### ISSUE TITLE
TensorGraphMultiTaskClassifier Issue

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#756]
I'm looking into converting examples that use `TensorflowMultiTaskClassClassifier` to use `TensorGraphMultiTaskClassifier`. I'm getting some strange errors though. Here is a Tox21 example I've converted to use `TensorGraphMultiTaskClassifier`:

```
# Load Tox21 dataset
n_features = 1024
tox21_tasks, tox21_datasets, transformers = dc.molnet.load_tox21()
train_dataset, valid_dataset, test_dataset = tox21_datasets

# Fit models
metric = dc.metrics.Metric(dc.metrics.roc_auc_score, np.mean)

model = dc.models.TensorGraphMultiTaskClassifier(
    len(tox21_tasks), n_features, layer_sizes=[1000], dropouts=[.25],
    learning_rate=0.001, batch_size=50)

# Fit trained model
model.fit(train_dataset, nb_epoch=1)
model.save()

print("Evaluating model")
train_scores = model.evaluate(train_dataset, [metric], transformers)
valid_scores = model.evaluate(valid_dataset, [metric], transformers)

print("Train scores")
print(train_scores)

print("Validation scores")
print(valid_scores)
```
Running this code results in the following error from `predict_proba`:
```
Traceback (most recent call last):
  File "tox21_tf_models.py", line 32, in <module>
    train_scores = model.evaluate(train_dataset, [metric], transformers)
  File "/home/rbharath/deepchem/deepchem/models/models.py", line 192, in evaluate
    scores = evaluator.compute_model_performance(metrics)
  File "/home/rbharath/deepchem/deepchem/utils/evaluate.py", line 101, in compute_model_performance
    y_pred = self.model.predict_proba(self.dataset, self.output_transformers)
  File "/home/rbharath/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 357, in predict_proba
    return self.predict_proba_on_generator(generator, transformers)
  File "/home/rbharath/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 282, in predict_proba_on_generator
    return np.concatenate(results, axis=0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly
```
Is there an API mismatch here causing issues?

CC @peastman

**Comment by peastman** [comment]
Looks like a question for @lilleswing.  It's calling `TensorGraph.predict_proba()` which is implemented as follows:

```Python
    generator = self.default_generator(dataset, predict=True, pad_batches=False)
    return self.predict_proba_on_generator(generator, transformers)
```

Notice that it specifies `pad_batches=False`.  I don't know why.  It then calls `predict_proba_on_generator()`, which loops over the batches and tries to concatenate the results together.  But because the batches are different size, the results are too and it throws that exception.

**Comment by lilleswing** [comment]
@peastman if we don't pad_batches then we have to truncate the results to remove the padded amount.  I can see this failing because of queues as well.

**Comment by peastman** [comment]
So why is it specifying `pad_batches=False`?  That's your code.

**Comment by rbharath** [comment]
Going to close this issue since we've completed this transition.
