### ISSUE TITLE
How to get featurized pdbbind datasets with ECFP (and GraphConv)? 

### ISSUE THREAD

**Issue by hfxfroi** [deepchem/deepchem#762]

**Comment by rbharath** [comment]
Try `dc.molnet.load_pdbbind_grid(featurizer="ECFP")` or `dc.molnet.load_pdbbind_grid(featurizer="GraphConv")`.

We should rename `load_pdbbind_grid` to `load_pdbbind` though.

**Comment by hfxfroi** [comment]
@rbharath  Thank you, I will try.
and when I run pdbbind_datasets.py error occured：
There are three proteins that can not be grid featured. For example, the core datasets set has 195, but I only get 192.

> /home/hfx/anaconda2/lib/python2.7/site-packages/deepchem/feat/rdkit_grid_featurizer.py:1103: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  dtype=np.int8)

WARNING:root:Unable to add hydrogens math domain error
WARNING:root:Unable to compute features for (1, '3i3b', u'/home/hfx/my_work/v2015', <deepchem.feat.rdkit_grid_featurizer.RdkitGridFeaturizer object at 0x7fd50f26f110>)


WARNING:root:Unable to compute features for (55, '3vd4', u'/home/hfx/my_work/v2015', <deepchem.feat.rdkit_grid_featurizer.RdkitGridFeaturizer object at 0x7fd4c7132650>)


WARNING:root:Unable to compute features for (23, '3muz', u'/home/hfx/my_work/v2015', <deepchem.feat.rdkit_grid_featurizer.RdkitGridFeaturizer object at 0x7fd50f26f110>)

**Comment by lilleswing** [comment]
Yeah rdkit + pdbfixer were unable to load and featurize those proteins.  
PRs welcome for the fix!

**Comment by hfxfroi** [comment]
When I updated  Deepchem to 1.2.1, error occured：

> >>> import deepchem
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hfx/anaconda2/lib/python2.7/site-packages/deepchem/__init__.py", line 12, in <module>
    import deepchem.models
  File "/home/hfx/anaconda2/lib/python2.7/site-packages/deepchem/models/__init__.py", line 10, in <module>
    from deepchem.models.xgboost_models import XGBoostModel
  File "/home/hfx/anaconda2/lib/python2.7/site-packages/deepchem/models/xgboost_models/__init__.py", line 12, in <module>
    from sklearn.model_selection import train_test_split, GridSearchCV
ImportError: No module named model_selection
>>>

**Comment by rbharath** [comment]
What's your sklearn version? It's possible you need to upgrade scikit-learn to have the example run.

**Comment by hfxfroi** [comment]
@rbharath Oh, I used scikit-learn 0.17.1.  I will try upgrade  sklearn version

**Comment by rbharath** [comment]
Great. If that fixes the issue, please let us know and we'll update the minimal required sklearn version.

**Comment by hfxfroi** [comment]
@rbharath I updated deepchem 1.1.1 to 1.2.1, and I upgraded sklearn version to 0.19.0,
import deepchem, it fixes the issue, but some warnings occured:

> /home/hfx/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

Warning: No pyGPGO.covfunc installed on your system
Attempting to run pyGPGO.covfunc will throw runtime errors
Warning: No pyGPGO.acquisition installed on your system
Attempting to run pyGPGO.acquisition will throw runtime errors
Warning: No pyGPGO.surrogates.GaussianProcess installed on your system
Attempting to run pyGPGO.surrogates.GaussianProcess will throw runtime errors
Warning: No pyGPGO.GPGO installed on your system
Attempting to run pyGPGO.GPGO will throw runtime errors

**Comment by rbharath** [comment]
These warnings are expected. You're good!

**Comment by hfxfroi** [comment]
@rbharath Thank you!  And there are some other problems.
I run featurizer="ECFP" or featurizer="GraphConv", some warnings occured:

> hfx@hfx-ubuntu:~/my_work/Results$ python ECFP.py
Loading raw samples now.
shard_size: 8192
About to start loading CSV from /tmp/refined_smiles_labels.csv
Loading shard 1 of size 8192.
Featurizing sample 0
Featurizing sample 1000
Featurizing sample 2000
Featurizing sample 3000
/home/hfx/anaconda2/lib/python2.7/site-packages/deepchem/data/data_loader.py:42: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if y[ind, task] == "":
TIMING: featurizing shard 0 took 20.229 s
TIMING: dataset construction took 20.531 s
Loading dataset from disk.
...
...
...
And the following warning occured when only running featurizer="GraphConv":

> /home/hfx/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "

Will these warnings affect my results?

**Comment by rbharath** [comment]
These warnings are expected as well.

We may want to clean up our warnings in general...

**Comment by hfxfroi** [comment]
@rbharath Thank you for your patience. Thank you very much.
