### ISSUE TITLE
Tensoboard induced bug

### ISSUE THREAD

**Issue by sharma409** [deepchem/deepchem#795]
The following code works with tensorboard=False, but errors out when tensorboard=True

> from __future__ import division
> import numpy as np
> import matplotlib.pyplot as plt
> import tensorflow as tf
> import deepchem as dc
> from deepchem.data import NumpyDataset
> 
> from deepchem.models.tensorgraph.layers import Dense, SoftMaxCrossEntropy, ReduceMean, SoftMax, ReduceSquareDifference
> from deepchem.models.tensorgraph.layers import Reshape, Flatten, Feature, Conv2D, MaxPool, Label, BatchNorm, Dropout
> 
> from tensorflow.examples.tutorials.mnist import input_data
> mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)
> train = NumpyDataset(mnist.train.images, mnist.train.labels)
> valid = NumpyDataset(mnist.validation.images,
>                              mnist.validation.labels)
> layer = Feature(shape=(None, 784))
> 
> layer = Dense(out_channels=2048, activation_fn=tf.nn.relu, in_layers=[layer])
> layer = Dropout(dropout_prob=0.4,in_layers=[layer])
> layer = BatchNorm(in_layers=[layer])
> 
> layer = Dense(out_channels=512, activation_fn=tf.nn.tanh, in_layers=[layer])
> layer = Dropout(dropout_prob=0.5,in_layers=[layer])
> 
> 
> out_layer = Dense(out_channels=10, in_layers=[layer])
> 
> label = Label(shape=(None, 10))
> smce = SoftMaxCrossEntropy(in_layers=[label, out_layer])
> loss = ReduceMean(in_layers=[smce])
> output = SoftMax(in_layers=[out_layer])
> tg = dc.models.TensorGraph(model_dir='/tmp/mnist', batch_size=1000, use_queue=True, learning_rate=0.001, tensorboard=True)
> tg.add_output(output)
> tg.set_loss(loss)
> tg.fit(train, nb_epoch=10)
> 

the error it gives is

> InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
> 	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
> 

Any idea as to why this is the case?

**Comment by sharma409** [comment]
This is the full traceback:

Exception in thread Thread-5:
Traceback (most recent call last):
  File "/miniconda/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/miniconda/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 598, in _enqueue_batch
    summary = sess.run(tg._get_tf("summary_op"), feed_dict=enq)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
    run_metadata_ptr)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
    feed_dict_string, options, run_metadata)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
    target_list, options, run_metadata)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
    raise type(e)(node_def, op, message)
InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'Placeholder', defined at:
  File "/miniconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/miniconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/miniconda/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/miniconda/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/miniconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/miniconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/miniconda/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/miniconda/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/miniconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/miniconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/miniconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/miniconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/miniconda/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/miniconda/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/miniconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/miniconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/miniconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-4-596dcf62d212>", line 20, in <module>
    tg.fit(train, nb_epoch=10)
  File "/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 126, in fit
    max_checkpoints_to_keep, checkpoint_interval)
  File "/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 143, in fit_generator
    self.build()
  File "/deepchem/deepchem/models/tensorgraph/tensor_graph.py", line 331, in build
    self._training_placeholder = tf.placeholder(dtype=tf.float32, shape=())
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1502, in placeholder
    name=name)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2149, in _placeholder
    name=name)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 763, in apply_op
    op_def=op_def)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2327, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/miniconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1226, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): You must feed a value for placeholder tensor 'Placeholder' with dtype float
	 [[Node: Placeholder = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by lilleswing** [comment]
https://github.com/deepchem/deepchem/pull/797

**Comment by rbharath** [comment]
@sharma409 Going to go ahead and close since #797 fixes. Feel free to re-open if there are further issues.
