### ISSUE TITLE
Docs Building on Travis is Failing

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#810]
Travis is failing to build docs and is failing with a strange import error:

```
Traceback (most recent call last):
  File "/home/travis/anaconda/envs/deepchem/bin/sphinx-apidoc", line 7, in <module>
    from sphinx.apidoc import main
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/apidoc.py", line 25, in <module>
    from sphinx.util.osutil import walk
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/util/__init__.py", line 27, in <module>
    import docutils
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/util/docutils.py", line 25, in <module>
    from sphinx.locale import __
ImportError: cannot import name __
Traceback (most recent call last):
  File "/home/travis/anaconda/envs/deepchem/bin/sphinx-build", line 11, in <module>
    sys.exit(main())
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/__init__.py", line 51, in main
    sys.exit(build_main(argv))
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/__init__.py", line 61, in build_main
    from sphinx import cmdline
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/cmdline.py", line 23, in <module>
    from sphinx.application import Sphinx
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/application.py", line 31, in <module>
    from sphinx.roles import XRefRole
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/roles.py", line 21, in <module>
    from sphinx.util import ws_re
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/util/__init__.py", line 27, in <module>
    import docutils
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/sphinx/util/docutils.py", line 25, in <module>
    from sphinx.locale import __
ImportError: cannot import name __
About to push docs to s3
ERROR: Parameter problem: Invalid character(s) in header name ''content-type'': "''"
ERROR: Parameter problem: Invalid character(s) in header name ''content-type'': "''"
```

Does anyone have any ideas on what's going on here?

**Comment by rbharath** [comment]
#814 fixes this error! Unfortunately, we still have a couple more bugs left:

```
/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/nbconvert/filters/strings.py:204: UserWarning: IPython is needed to transform IPython syntax to pure Python. Install ipython if you need this functionality.
  "IPython is needed to transform IPython syntax to pure Python."

Exception occurred:
  File "/home/travis/anaconda/envs/deepchem/lib/python2.7/site-packages/nbconvert/preprocessors/execute.py", line 191, in _km_default
    raise ImportError("`nbconvert --execute` requires the jupyter_client package: `pip install jupyter_client`")
ImportError: `nbconvert --execute` requires the jupyter_client package: `pip install jupyter_client`
The full traceback has been saved in /tmp/sphinx-err-0yVG_j.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

The content warning issues still shows up as well:

```
ERROR: Parameter problem: Invalid character(s) in header name ''content-type'': "''"
ERROR: Parameter problem: Invalid character(s) in header name ''content-type'': "''"
```

**Comment by mpharrigan** [comment]
make sure you're installing jupyter before trying to run the jupyter notebooks

**Comment by lilleswing** [comment]
Because we are running all the notebooks we have to install all the deps for all the notebooks.
It adds 10 minutes to the build to both install the deps and run the notebooks.

![selection_097](https://user-images.githubusercontent.com/1225605/29972800-62f43fe6-8efb-11e7-8c8b-ea21699ff62f.png)

``` bash
conda install -y jupyter
conda install -y nbconvert
conda install -y jupyter_client
conda install -y ipykernel
conda install -y matplotlib
yes | pip install nglview
conda install -y ipywidgets
conda install -y cmake
yes | pip install gym[atari]
```
Are the additional deps we need to install.
Also I don't see any logic in the after_success script to run only with python 2.7 and not 3.5 (the notebooks rely on 2.7 pickles).  We should restrict the upload of the docs to only go when $TRAVIS_PYTHON_VERSION=2.7

**Comment by rbharath** [comment]
Good suggestions! We should put these changes in. 

We may want to consider moving the docs build over to Jenkins though, especially as we add more tutorials.

**Comment by rbharath** [comment]
I believe this issue has been resolved. Closing for now.
