### ISSUE TITLE
Delaney Bayesian_predict example causes numpy AttributeError

### ISSUE THREAD

**Issue by IamDavyG** [deepchem/deepchem#838]
Hey everyone, I'm getting numpy AttributeErrors from bayesian_predict after model fitting. I will try and see if this is replicated in a conda environment,

Here is what I'm seeing from the console:

```
TIMING: model fitting took 24.431 s
computed_metrics: [0.41083452912900115]
INFO:tensorflow:Restoring parameters from model_saves/model-120
Traceback (most recent call last):

  File "<ipython-input-1-95e970213fd1>", line 1, in <module>
    runfile('/home/davy/deepchem/examples/delaney/delaney_graphconv_error_bars.py', wdir='/home/davy/deepchem/examples/delaney')

  File "/home/davy/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 710, in runfile
    execfile(filename, namespace)

  File "/home/davy/anaconda2/lib/python2.7/site-packages/spyder/utils/site/sitecustomize.py", line 93, in execfile
    builtins.execfile(filename, *where)

  File "/home/davy/deepchem/examples/delaney/delaney_graphconv_error_bars.py", line 46, in <module>
    valid_dataset.X, transformers, untransform=True, n_passes=24)

  File "/home/davy/deepchem/deepchem/models/tensorgraph/models/graph_models.py", line 648, in bayesian_predict
    X = dataset.X

AttributeError: 'numpy.ndarray' object has no attribute 'X'
```

**Comment by rutayanp** [comment]
@rbharath Do you think a newbie like me can take this up? :)
I am new to contributing to open sources but would like to start from somewhere.

**Comment by rbharath** [comment]
@rutayanp Thanks for the offer! This one might be a little tricky since I think we need to put together a more general API for Bayesian prediction. I'd recommend starting easier, perhaps by adding on a new DeepChem tutorial or example to get your feet wet :)

**Comment by rutayanp** [comment]
sure :)
