### ISSUE TITLE
Problem loading Atomic conv (ACNN) datasets

### ISSUE THREAD

**Issue by nhstanley** [deepchem/deepchem#856]
I've been trying to run the ACNN examples but I've been hitting this error:

```
$ python opt_random.py 
Loading dataset from disk.
Loading dataset from disk.
Traceback (most recent call last):
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle_compat.py", line 226, in load_compatibility
    obj = unpickler.load()
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1185, in load_binstring
    self.append(self._decode_string(data))
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1167, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 0: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 115, in load_from_disk
    return joblib.load(filename)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 576, in load
    return load_compatibility(fobj)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle_compat.py", line 235, in load_compatibility
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 226, in load_compatibility
    obj = unpickler.load()
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1185, in load_binstring
    self.append(self._decode_string(data))
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/pickle.py", line 1167, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xdd in position 0: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "opt_random.py", line 44, in <module>
    y_train = train_dataset.y
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 1004, in y
    for (_, y_b, _, _) in self.itershards():
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 609, in iterate
    X = np.array(load_from_disk(os.path.join(dataset.data_dir, row['X'])))
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 120, in load_from_disk
    return old_joblib.load(filename)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 573, in load
    return load_compatibility(fobj)
  File "/Users/stanlen1/anaconda/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 235, in load_compatibility
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.
```

I've run into this error on linux and mac os, despite the fact that I have no problem spinning up a ipython terminal and reading the files manually. What's going on? Is it trying to load it using the wrong loader, or is using the wrong decoding? 

cc: @joegomes

**Comment by rbharath** [comment]
@dr-nate Is this code in `contrib/` or in `examples/`? 

From first look, I think you're running into the fact that the featurized data we've been storing on AWS is in Py2 pickle format and I think you're running Py3. We should fix this one :)

**Comment by dr-nate** [comment]
Yup, it's in `contrib/`.  Here specifcially: `https://github.com/deepchem/deepchem/tree/master/contrib/atomicconv/acnn/core`

**Comment by rbharath** [comment]
I think the `contrib/` code for ACNN is currently not maintained. Is the ACNN code in `examples` broken as well? If so we should definitely fix that.

**Comment by dr-nate** [comment]
Hmm. Where is the ACNN stuff in `examples/`. If I do a `grep -iR 'atomicnet' ` on the repo the only place I see stuff is in `contrib/`.

**Comment by rbharath** [comment]
Huh, I think you're right. We should add in a real example for ACNN then. PRs very welcome if you've got any interest :-)

**Comment by lilleswing** [comment]
@dr-nate p.s. the issue you are seeing is because you are using python3 for your python and python2 for your jupyter.  The current atomic conv code does not featurize inline and instead uses pre-featurized datasets using python2 (which are not python3 portable).

**Comment by jananikrish92** [comment]
Do you have examples for ACNN or tutorial?

**Comment by rbharath** [comment]
@jananikrish92 Not currently. I've opened out an issue (https://github.com/deepchem/deepchem/issues/1179) to coordinate the construction of such a tutorial.

**Comment by rbharath** [comment]
Closing out this issue. We can continue discussion in #1179 if there's interest
