### ISSUE TITLE
failed to run pdbbind_tf.py

### ISSUE THREAD

**Issue by nagaokatakuya** [deepchem/deepchem#878]
When I run pdbbind_tf.py, the following error occured

```
Loading dataset from disk.
Traceback (most recent call last):
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle_compat.py", line 226, in load_compatibility
    obj = unpickler.load()
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1185, in load_binstring
    self.append(self._decode_string(data))
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1167, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 861387: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 115, in load_from_disk
    return joblib.load(filename)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle.py", line 576, in load
    return load_compatibility(fobj)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/joblib/numpy_pickle_compat.py", line 235, in load_compatibility
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 226, in load_compatibility
    obj = unpickler.load()
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1043, in load
    dispatch[key[0]](self)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1185, in load_binstring
    self.append(self._decode_string(data))
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/pickle.py", line 1167, in _decode_string
    return value.decode(self.encoding, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x84 in position 861387: ordinal not in range(128)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pdbbind_tf.py", line 25, in <module>
    split=split, subset=subset)
  File "/Users/nagaoka/deepchem/examples/pdbbind/pdbbind_datasets.py", line 188, in load_pdbbind_grid
    dataset.w
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 1018, in w
    for (_, _, w_b, _) in self.itershards():
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/data/datasets.py", line 610, in iterate
    X = np.array(load_from_disk(os.path.join(dataset.data_dir, row['X'])))
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/deepchem/utils/save.py", line 120, in load_from_disk
    return old_joblib.load(filename)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle.py", line 573, in load
    return load_compatibility(fobj)
  File "/Users/nagaoka/anaconda3/envs/deepchem/lib/python3.5/site-packages/sklearn/externals/joblib/numpy_pickle_compat.py", line 235, in load_compatibility
    raise new_exc
ValueError: You may be trying to read with python 3 a joblib pickle generated with python 2. This feature is not supported by joblib.
```

I guess the cause of this problem is trying to load a joblib pickle generated with python2 in the environment using python3.

My environment is following plugins.

```
backports                 1.0                      py35_1    conda-forge
backports.weakref         1.0rc1                   py35_1    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    1.5.0                    py35_0    conda-forge
boost                     1.56.0                   py35_3    rdkit
bzip2                     1.0.6                h92991f9_1  
ca-certificates           2017.08.26           ha1e5d58_0  
cairo                     1.14.6                        3    conda-forge
certifi                   2017.7.27.1      py35h0fdde5e_0  
decorator                 4.1.2                    py35_0    conda-forge
deepchem                  1.2.1.dev515              <pip>
fftw3f                    3.3.4                         2    omnia
flaky                     3.3.0                    py35_0    conda-forge
fontconfig                2.12.1                        3    conda-forge
freetype                  2.7                           1    conda-forge
gettext                   0.19.8.1             hb0f4f8b_2  
glib                      2.51.4                        0    conda-forge
h5py                      2.7.1                    py35_1    conda-forge
hdf5                      1.8.18                        0    conda-forge
html5lib                  0.9999999                py35_0    conda-forge
icu                       56.1                          4    conda-forge
intel-openmp              2018.0.0             hdd0ccc9_7  
joblib                    0.11                     py35_0    conda-forge
jpeg                      9b                   haccd157_1  
keras                     1.0.7                    py35_0    conda-forge
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                hd939716_3  
libgfortran               3.0.1                h93005f0_2  
libgpuarray               0.7.3                         0    conda-forge
libiconv                  1.15                 h99df5da_5  
libpng                    1.6.28                        0    conda-forge
libtiff                   4.0.6                         7    conda-forge
libxml2                   2.9.4                         3    conda-forge
mako                      1.0.7                    py35_0    conda-forge
markdown                  2.6.9                    py35_0    conda-forge
markupsafe                1.0                      py35_0    conda-forge
mdtraj                    1.8.0                    py35_2    conda-forge
mkl                       2017.0.3                      0  
mock                      2.0.0                    py35_0    conda-forge
ncurses                   6.0                  ha932d30_1  
networkx                  1.11                     py35_0    conda-forge
nose                      1.3.7                    py35_2    conda-forge
nose-timer                0.7.0                    py35_1    conda-forge
numexpr                   2.6.4                    py35_0    conda-forge
numpy                     1.11.3          py35_blas_openblas_202  [blas_openblas]  conda-forge
olefile                   0.44             py35h1f523c6_0  
openblas                  0.2.19                        2    conda-forge
openmm                    7.1.1                    py35_0    omnia
openssl                   1.0.2l               h57f3a61_2  
pandas                    0.19.2              np111py35_1    conda-forge
pbr                       3.1.1                    py35_0    conda-forge
pcre                      8.41                 h29eefc5_0  
pdbfixer                  1.4                      py35_0    omnia
pillow                    4.2.1                    py35_0    conda-forge
pip                       9.0.1            py35he52dd69_3  
pixman                    0.34.0               h5b2340f_1  
protobuf                  3.3.2                    py35_0    conda-forge
pygpu                     0.7.3               np111py35_0    conda-forge
pytables                  3.4.2               np111py35_4    conda-forge
python                    3.5.4                         0    conda-forge
python-dateutil           2.6.1            py35h10515e0_1  
pytz                      2017.2           py35h9789cde_1  
pyyaml                    3.12                     py35_1    conda-forge
rdkit                     2017.03.3           np111py35_1    rdkit
readline                  6.2                           2  
scikit-learn              0.18.1          np111py35_blas_openblas_200  [blas_openblas]  conda-forge
scipy                     0.19.1          py35_blas_openblas_202  [blas_openblas]  conda-forge
setuptools                36.2.2                   py35_0    conda-forge
six                       1.10.0                   py35_1    conda-forge
sqlite                    3.13.0                        1    conda-forge
tensorflow                1.3.0                    py35_0    conda-forge
termcolor                 1.1.0                    py35_1    conda-forge
theano                    0.9.0                    py35_1    conda-forge
tk                        8.5.19                        2    conda-forge
webencodings              0.5                      py35_0    conda-forge
werkzeug                  0.12.2                     py_1    conda-forge
wheel                     0.29.0           py35ha7aa5c4_1  
xgboost                   0.6a2                    py35_0    conda-forge
xz                        5.2.3                ha24016e_1  
yaml                      0.1.6                         0    conda-forge
zlib                      1.2.11                        0    conda-forge
```

In order to solve this problem, I need to run this code with python2.
But I want to use deepchem with python3. 
Does anyone have any ideas on what's going on here?

**Comment by rbharath** [comment]
This looks like it might be same issue as #856. Agreed we should definitely fix this, and I think @nhstanley is taking a crack at it.

**Comment by nhstanley** [comment]
Yes, because things are pickled with joblib, it needs to be rerun in python3. This is one of a few things I'm working on. I should have something fixing this in a week or two.

**Comment by rbharath** [comment]
Closing this old issue. Let me know if this is still relevant and should be re-opened.
