### ISSUE TITLE
benchmark.py fails due to TopKKernel Invalid Argument

### ISSUE THREAD

**Issue by LRParser** [deepchem/deepchem#896]
Congrats on the 1.3 release! FYI, when I try to benchmark it fails for me at the hiv dataset with the following error:

```
-------------------------------------
Benchmark on dataset: hiv
-------------------------------------
Splitting function: index
About to featurize hiv dataset.
Loading dataset from disk.
Loading dataset from disk.
Loading dataset from disk.
start similarity calculation
similarity calculation takes 8 s
2017-10-24 21:41:44.347935: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1070, pci bus id: 0000:01:00.0)
2017-10-24 21:41:44.351808: W tensorflow/core/framework/op_kernel.cc:1192] Internal: Could not launch TopKKernel: invalid argument.
Traceback (most recent call last):
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1327, in _do_call
    return fn(*args)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1306, in _run_fn
    status, run_metadata)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.InternalError: Could not launch TopKKernel: invalid argument.
	 [[Node: TopKV2 = TopKV2[T=DT_DOUBLE, sorted=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_0_0/_1, TopKV2/k)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark.py", line 110, in <module>
    [dataset], str(model), split=split, test=test, seed=seed)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/run_benchmark.py", line 190, in run_benchmark
    seed=seed)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/run_benchmark_models.py", line 176, in benchmark_classification
    train_dataset = transformer.transform(train_dataset)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 787, in transform
    X_length), :]))
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 743, in X_transform
    X_target2.append(self.realize(similarity, self.y[:, i], self.w[:, i]))
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 696, in realize
    fetched_values = sess.run([value, top_label], feed_dict=feed_dict)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1124, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1321, in _do_run
    options, run_metadata)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1340, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Could not launch TopKKernel: invalid argument.
	 [[Node: TopKV2 = TopKV2[T=DT_DOUBLE, sorted=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_0_0/_1, TopKV2/k)]]

Caused by op 'TopKV2', defined at:
  File "benchmark.py", line 110, in <module>
    [dataset], str(model), split=split, test=test, seed=seed)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/run_benchmark.py", line 190, in run_benchmark
    seed=seed)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/molnet/run_benchmark_models.py", line 176, in benchmark_classification
    train_dataset = transformer.transform(train_dataset)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 787, in transform
    X_length), :]))
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 743, in X_transform
    X_target2.append(self.realize(similarity, self.y[:, i], self.w[:, i]))
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/deepchem/trans/transformers.py", line 684, in realize
    similarity_placeholder, k=self.K + 1, sorted=True)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/nn_ops.py", line 1949, in top_k
    return gen_nn_ops._top_kv2(input, k=k, sorted=sorted, name=name)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/ops/gen_nn_ops.py", line 2577, in _top_kv2
    name=name)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2630, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/joe/.conda/envs/deepchem/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1204, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InternalError (see above for traceback): Could not launch TopKKernel: invalid argument.
	 [[Node: TopKV2 = TopKV2[T=DT_DOUBLE, sorted=true, _device="/job:localhost/replica:0/task:0/gpu:0"](_arg_Placeholder_0_0/_1, TopKV2/k)]]
```

Can you provide any help or tips for debugging? Just want to make sure there are no new setup reqs. Everything up to this point seemed to run fine.

**Comment by LRParser** [comment]
Have narrowed it down based on stack trace - seems related to the dc.trans.IRVTransformer, but can't see anything clearly wrong...wondering if it's related to TF 1.3?

**Comment by Dgelemi** [comment]
I have the same error

**Comment by miaecle** [comment]
@LRParser I think it is due to `tf.nn.top_k`. It only raises exception on GPU version of tf1.3, changing it temporarily to a CPU operation could work.

**Comment by LRParser** [comment]
I can confirm that this works around the issue successfully. I was able to complete a full benchmark run, getting past hiv tests to PCBA:

```
pcba,index,classification,tf,mean-roc_auc_score,train,0.821734346074,valid,0.799447768391,time_for_running,3253.647607564926
pcba,index,classification,tf_robust,mean-roc_auc_score,train,0.817276072579,valid,0.782783447463,time_for_running,6070.68456029892
```
