### ISSUE TITLE
Docker image needs installation of LibSM6

### ISSUE THREAD

**Issue by BielStela** [deepchem/deepchem#903]
I have pulled the docker image (deepchemio/deepchem) and I get this error when runing benchmark:
```python
>>> import deepchem as dc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/deepchem/deepchem/__init__.py", line 8, in <module>
    import deepchem.data
  File "/deepchem/deepchem/data/__init__.py", line 9, in <module>
    from deepchem.data.datasets import pad_features
  File "/deepchem/deepchem/data/datasets.py", line 11, in <module>
    from deepchem.utils.save import save_to_disk
  File "/deepchem/deepchem/utils/__init__.py", line 17, in <module>
    from rdkit import Chem
  File "/miniconda/lib/python2.7/site-packages/rdkit/Chem/__init__.py", line 28, in <module>
    from rdkit.Chem.rdmolops import *
ImportError: libSM.so.6: cannot open shared object file: No such file or directory
```
it needs an extra lib that have to be installed manually with:

```
apt install libsm6
```
After that everything works.

**Comment by lilleswing** [comment]
Thanks for the report, I have reproed it and am fixing the builds.  Not sure how I missed it in the first place.... :(

**Comment by lilleswing** [comment]
Docker Images Updated.
