### ISSUE TITLE
deepchem.molnet.load_pdbbind_grid() raises an error

### ISSUE THREAD

**Issue by jyn514** [deepchem/deepchem#994]
Version: 1.3.1  
Custom config: `export DEEPCHEM_DATA_DIR="/usr/local/src/research_project"`  
Installation method:  `conda install -c deepchem -c rdkit -c conda-forge -c omnia deepchem=1.3.1`  
uname -a:  
`Linux debian-thinkpad 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux`  
Traceback:

    >>> deepchem.molnet.load_pdbbind_grid()
    Loading dataset from disk.
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/usr/local/lib/miniconda/lib/python3.6/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py", line 55, in load_pdbbind_grid
        dataset, tasks = featurize_pdbbind(feat=featurizer, subset=subset)
    File "/usr/local/lib/miniconda/lib/python3.6/site-packages/deepchem/molnet/load_function/pdbbind_datasets.py", line 46, in featurize_pdbbind
        return deepchem.data.DiskDataset(dataset_dir), tasks
    File "/usr/local/lib/miniconda/lib/python3.6/site-packages/deepchem/data/datasets.py", line 438, in __init__
        raise ValueError("No metadata found on disk.")
    ValueError: No metadata found on disk.

**Comment by jyn514** [comment]
Think I figured this out. The keywords default to `load_ppb(featurizer='ECFP', split='index', reload=True)`. Since I didn't have any history saved, there was nothing to reload. When I ran `deepchem.molnet.load_pdbbind_grid(split="random", featurizer="ECFP")`, it worked beautifully.

 The error was very obscure, but this is a documentation problem, not a library problem.
